// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies;

public class Number extends dynamicform.proxies.Element
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicForm.Number";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NumberValue("NumberValue"),
		VariableName("VariableName"),
		Formula("Formula"),
		Expression("Expression"),
		NameoftheAttribute("NameoftheAttribute"),
		dateandtime("dateandtime"),
		Element_Template("DynamicForm.Element_Template");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Number(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject numberMendixObject)
	{
		super(context, numberMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, numberMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'Number.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicform.proxies.Number initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicform.proxies.Number.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dynamicform.proxies.Number initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicform.proxies.Number(context, mendixObject);
	}

	public static dynamicform.proxies.Number load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicform.proxies.Number.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicform.proxies.Number> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> dynamicform.proxies.Number.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of NumberValue
	 */
	public final java.lang.Integer getNumberValue()
	{
		return getNumberValue(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberValue
	 */
	public final java.lang.Integer getNumberValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberValue.toString());
	}

	/**
	 * Set value of NumberValue
	 * @param numbervalue
	 */
	public final void setNumberValue(java.lang.Integer numbervalue)
	{
		setNumberValue(getContext(), numbervalue);
	}

	/**
	 * Set value of NumberValue
	 * @param context
	 * @param numbervalue
	 */
	public final void setNumberValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numbervalue)
	{
		getMendixObject().setValue(context, MemberNames.NumberValue.toString(), numbervalue);
	}

	/**
	 * @return value of VariableName
	 */
	public final java.lang.String getVariableName()
	{
		return getVariableName(getContext());
	}

	/**
	 * @param context
	 * @return value of VariableName
	 */
	public final java.lang.String getVariableName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VariableName.toString());
	}

	/**
	 * Set value of VariableName
	 * @param variablename
	 */
	public final void setVariableName(java.lang.String variablename)
	{
		setVariableName(getContext(), variablename);
	}

	/**
	 * Set value of VariableName
	 * @param context
	 * @param variablename
	 */
	public final void setVariableName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String variablename)
	{
		getMendixObject().setValue(context, MemberNames.VariableName.toString(), variablename);
	}

	/**
	 * @return value of Formula
	 */
	public final java.lang.Boolean getFormula()
	{
		return getFormula(getContext());
	}

	/**
	 * @param context
	 * @return value of Formula
	 */
	public final java.lang.Boolean getFormula(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Formula.toString());
	}

	/**
	 * Set value of Formula
	 * @param formula
	 */
	public final void setFormula(java.lang.Boolean formula)
	{
		setFormula(getContext(), formula);
	}

	/**
	 * Set value of Formula
	 * @param context
	 * @param formula
	 */
	public final void setFormula(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean formula)
	{
		getMendixObject().setValue(context, MemberNames.Formula.toString(), formula);
	}

	/**
	 * @return value of Expression
	 */
	public final java.lang.String getExpression()
	{
		return getExpression(getContext());
	}

	/**
	 * @param context
	 * @return value of Expression
	 */
	public final java.lang.String getExpression(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Expression.toString());
	}

	/**
	 * Set value of Expression
	 * @param expression
	 */
	public final void setExpression(java.lang.String expression)
	{
		setExpression(getContext(), expression);
	}

	/**
	 * Set value of Expression
	 * @param context
	 * @param expression
	 */
	public final void setExpression(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expression)
	{
		getMendixObject().setValue(context, MemberNames.Expression.toString(), expression);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicform.proxies.Number that = (dynamicform.proxies.Number) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
