// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicworkflow.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the DynamicWorkflow module
	public static void aCT_AddParellelApprovers(IContext context, dynamicworkflow.proxies.WorkflowUsers _workflowUsers)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUsers", _workflowUsers == null ? null : _workflowUsers.getMendixObject());
		Core.microflowCall("DynamicWorkflow.ACT_AddParellelApprovers").withParams(params).execute(context);
	}
	public static java.util.List<dynamicworkflow.proxies.WorkflowUsers> aCT_AddUser(IContext context, dynamicworkflow.proxies.WorkflowUsers _workflowUsers, dynamicworkflow.proxies.DynamicWorkflow _dynamicWorkflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUsers", _workflowUsers == null ? null : _workflowUsers.getMendixObject());
		params.put("DynamicWorkflow", _dynamicWorkflow == null ? null : _dynamicWorkflow.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicWorkflow.ACT_AddUser").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> dynamicworkflow.proxies.WorkflowUsers.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void aCT_AddWorkflowLevels(IContext context, dynamicworkflow.proxies.WorkflowLevel _workflowLevel, dynamicworkflow.proxies.DynamicWorkflow _dynamicWorkflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowLevel", _workflowLevel == null ? null : _workflowLevel.getMendixObject());
		params.put("DynamicWorkflow", _dynamicWorkflow == null ? null : _dynamicWorkflow.getMendixObject());
		Core.microflowCall("DynamicWorkflow.ACT_AddWorkflowLevels").withParams(params).execute(context);
	}
	public static void aCT_create_worflowusers(IContext context, dynamicworkflow.proxies.WorkflowLevel _workflowLevel)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowLevel", _workflowLevel == null ? null : _workflowLevel.getMendixObject());
		Core.microflowCall("DynamicWorkflow.ACT_create_worflowusers").withParams(params).execute(context);
	}
	public static void aCT_create_workflow(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DynamicWorkflow.ACT_create_workflow").withParams(params).execute(context);
	}
	public static void aCT_SAVE_workflowlevel(IContext context, dynamicworkflow.proxies.WorkflowLevel _workflowLevel)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowLevel", _workflowLevel == null ? null : _workflowLevel.getMendixObject());
		Core.microflowCall("DynamicWorkflow.ACT_SAVE_workflowlevel").withParams(params).execute(context);
	}
	public static void aCT_SaveWorkfloUser(IContext context, dynamicworkflow.proxies.WorkflowUsers _workflowUsers)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUsers", _workflowUsers == null ? null : _workflowUsers.getMendixObject());
		Core.microflowCall("DynamicWorkflow.ACT_SaveWorkfloUser").withParams(params).execute(context);
	}
	public static void aCT_SaveWorkflow(IContext context, dynamicworkflow.proxies.DynamicWorkflow _dynamicWorkflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DynamicWorkflow", _dynamicWorkflow == null ? null : _dynamicWorkflow.getMendixObject());
		Core.microflowCall("DynamicWorkflow.ACT_SaveWorkflow").withParams(params).execute(context);
	}
	public static void aCT_SaveWorkflowLevel(IContext context, dynamicworkflow.proxies.WorkflowLevel _workflowLevel)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowLevel", _workflowLevel == null ? null : _workflowLevel.getMendixObject());
		Core.microflowCall("DynamicWorkflow.ACT_SaveWorkflowLevel").withParams(params).execute(context);
	}
	public static void aCT_SaveWorkflowLevels(IContext context, dynamicworkflow.proxies.DynamicWorkflow _dynamicWorkflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DynamicWorkflow", _dynamicWorkflow == null ? null : _dynamicWorkflow.getMendixObject());
		Core.microflowCall("DynamicWorkflow.ACT_SaveWorkflowLevels").withParams(params).execute(context);
	}
	public static void aCT_View_EditDynamicWorkflow(IContext context, dynamicworkflow.proxies.WorkflowUsers _workflowUsers, dynamicworkflow.proxies.DynamicWorkflow _dynamicWorkflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUsers", _workflowUsers == null ? null : _workflowUsers.getMendixObject());
		params.put("DynamicWorkflow", _dynamicWorkflow == null ? null : _dynamicWorkflow.getMendixObject());
		Core.microflowCall("DynamicWorkflow.ACT_View_EditDynamicWorkflow").withParams(params).execute(context);
	}
	public static void act_workflowlevel(IContext context, dynamicworkflow.proxies.WorkflowLevel _workflowLevel)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowLevel", _workflowLevel == null ? null : _workflowLevel.getMendixObject());
		Core.microflowCall("DynamicWorkflow.Act_workflowlevel").withParams(params).execute(context);
	}
	public static void aCT_workflowlevel_create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DynamicWorkflow.ACT_workflowlevel_create").withParams(params).execute(context);
	}
	public static java.util.List<administration.proxies.Account> ds_account_xpath(IContext context, dynamicworkflow.proxies.WorkflowUsers _workflowUsers)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUsers", _workflowUsers == null ? null : _workflowUsers.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicWorkflow.ds_account_xpath").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<dynamicworkflow.proxies.WorkflowUsers> dS_Retreive_WorkflowUSers(IContext context, dynamicworkflow.proxies.WorkflowUsers _workflowUsers)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUsers", _workflowUsers == null ? null : _workflowUsers.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicWorkflow.DS_Retreive_WorkflowUSers").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> dynamicworkflow.proxies.WorkflowUsers.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<dynamicworkflow.proxies.WorkflowUsers> dS_RetreiveWorkflowUsers(IContext context, dynamicworkflow.proxies.DynamicWorkflow _dynamicWorkflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DynamicWorkflow", _dynamicWorkflow == null ? null : _dynamicWorkflow.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicWorkflow.DS_RetreiveWorkflowUsers").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> dynamicworkflow.proxies.WorkflowUsers.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
}
