...
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - IMAGE_REPO_NAME="keerthiikrish/cicd:$BUILD_NUMBER"
      - docker login -u keerthiikrish -p keerthi@22

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME
...
