define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../../../Users/krish/OneDrive/Documents/Mendix/SNTC-main/javascriptsource/myfirstmodule/actions/JS_ToggleNavigation.js":
/*!***************************************************************************************************************************************!*\
  !*** ../../../../../../Users/krish/OneDrive/Documents/Mendix/SNTC-main/javascriptsource/myfirstmodule/actions/JS_ToggleNavigation.js ***!
  \***************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_ToggleNavigation": () => (/* binding */ JS_ToggleNavigation)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.

 // BEGIN EXTRA CODE
// Developer: Sriram  (github.com/sriram-24)

const toggleNavigation = isSidebarOpen => {
  console.error(document.querySelector(".mx-scrollcontainer-shrink").classList.contains('mx-scrollcontainer-open'));

  if (isSidebarOpen) {
    document.querySelector(".mx-scrollcontainer-shrink").classList.add('mx-scrollcontainer-open');
    document.querySelector(".region-sidebar").classList.add('mx-scrollcontainer-move-in');
    document.querySelector(".region-sidebar").style.width = "232px";
  } else {
    document.querySelector(".mx-scrollcontainer-shrink").classList.remove('mx-scrollcontainer-open');
    document.querySelector(".region-sidebar").classList.remove('mx-scrollcontainer-move-in'); // document.querySelector(".region-sidebar").classList.add('mx-scrollcontainer-move-out');

    document.querySelector(".region-sidebar").style.width = "0px";
  }
}; // END EXTRA CODE

/**
 * @param {boolean} isSidebarOpen
 * @returns {Promise.<void>}
 */


async function JS_ToggleNavigation(isSidebarOpen) {
  // BEGIN USER CODE
  toggleNavigation(isSidebarOpen); // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

"use strict";
module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ }),

/***/ "?391f":
/*!**********************************!*\
  !*** mx-global (ignored module) ***!
  \**********************************/
/***/ (() => {

/* empty */

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
/*!*****************************************************************************************************!*\
  !*** ../../../../../../Users/krish/OneDrive/Documents/Mendix/SNTC-main/deployment/tmp/jsactions.js ***!
  \*****************************************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "MyFirstModule$JS_ToggleNavigation": () => (/* binding */ MyFirstModule$JS_ToggleNavigation)
/* harmony export */ });
const MyFirstModule$JS_ToggleNavigation = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/krish/OneDrive/Documents/Mendix/SNTC-main/javascriptsource/myfirstmodule/actions/JS_ToggleNavigation */ "../../../../../../Users/krish/OneDrive/Documents/Mendix/SNTC-main/javascriptsource/myfirstmodule/actions/JS_ToggleNavigation.js"))).JS_ToggleNavigation;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Q0FHQTtBQUNBOztBQUNBLE1BQU1DLGdCQUFnQixHQUFJQyxhQUFELElBQWtCO0FBQzNDQyxFQUFBQSxPQUFPLENBQUNDLEtBQVIsQ0FBY0MsUUFBUSxDQUFDQyxhQUFULENBQXVCLDRCQUF2QixFQUFxREMsU0FBckQsQ0FBK0RDLFFBQS9ELENBQXdFLHlCQUF4RSxDQUFkOztBQUNDLE1BQUlOLGFBQUosRUFBb0I7QUFFcEJHLElBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1Qiw0QkFBdkIsRUFBcURDLFNBQXJELENBQStERSxHQUEvRCxDQUFtRSx5QkFBbkU7QUFDQUosSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGlCQUF2QixFQUEwQ0MsU0FBMUMsQ0FBb0RFLEdBQXBELENBQXdELDRCQUF4RDtBQUNBSixJQUFBQSxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsaUJBQXZCLEVBQTBDSSxLQUExQyxDQUFnREMsS0FBaEQsR0FBc0QsT0FBdEQ7QUFDQSxHQUxBLE1BTUc7QUFDSE4sSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLDRCQUF2QixFQUFxREMsU0FBckQsQ0FBK0RLLE1BQS9ELENBQXNFLHlCQUF0RTtBQUNBUCxJQUFBQSxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsaUJBQXZCLEVBQTBDQyxTQUExQyxDQUFvREssTUFBcEQsQ0FBMkQsNEJBQTNELEVBRkcsQ0FHSDs7QUFDQVAsSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGlCQUF2QixFQUEwQ0ksS0FBMUMsQ0FBZ0RDLEtBQWhELEdBQXNELEtBQXREO0FBQ0E7QUFDQSxDQWRELEVBZUE7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7OztBQUNPLGVBQWVFLG1CQUFmLENBQW1DWCxhQUFuQyxFQUFrRDtBQUN4RDtBQUNBRCxFQUFBQSxnQkFBZ0IsQ0FBQ0MsYUFBRCxDQUFoQixDQUZ3RCxDQUd4RDtBQUNBOzs7Ozs7Ozs7OztBQ3JDRDs7Ozs7Ozs7OztBQ0FBOzs7Ozs7VUNBQTtVQUNBOztVQUVBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBOztVQUVBO1VBQ0E7O1VBRUE7VUFDQTtVQUNBOzs7OztXQ3RCQTtXQUNBO1dBQ0E7V0FDQTtXQUNBO1dBQ0EsaUNBQWlDLFdBQVc7V0FDNUM7V0FDQTs7Ozs7V0NQQTtXQUNBO1dBQ0E7V0FDQTtXQUNBLHlDQUF5Qyx3Q0FBd0M7V0FDakY7V0FDQTtXQUNBOzs7OztXQ1BBOzs7OztXQ0FBO1dBQ0E7V0FDQTtXQUNBLHVEQUF1RCxpQkFBaUI7V0FDeEU7V0FDQSxnREFBZ0QsYUFBYTtXQUM3RDs7Ozs7Ozs7Ozs7Ozs7O0FDTk8sTUFBTVksaUNBQWlDLEdBQUcsWUFBWSxDQUFDLE1BQU0sMlZBQVAsRUFBZ0lELG1CQUF0TCxDIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL2tyaXNoL09uZURyaXZlL0RvY3VtZW50cy9NZW5kaXgvU05UQy1tYWluL2phdmFzY3JpcHRzb3VyY2UvbXlmaXJzdG1vZHVsZS9hY3Rpb25zL0pTX1RvZ2dsZU5hdmlnYXRpb24uanMiLCJ3ZWJwYWNrOi8vL2V4dGVybmFsIGFtZCBcImJpZy5qc1wiIiwid2VicGFjazovLy9teC1nbG9iYWwiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svYm9vdHN0cmFwIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvY29tcGF0IGdldCBkZWZhdWx0IGV4cG9ydCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2RlZmluZSBwcm9wZXJ0eSBnZXR0ZXJzIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvaGFzT3duUHJvcGVydHkgc2hvcnRoYW5kIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvbWFrZSBuYW1lc3BhY2Ugb2JqZWN0Iiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9Vc2Vycy9rcmlzaC9PbmVEcml2ZS9Eb2N1bWVudHMvTWVuZGl4L1NOVEMtbWFpbi9kZXBsb3ltZW50L3RtcC9qc2FjdGlvbnMuanMiXSwic291cmNlc0NvbnRlbnQiOlsiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IFwibXgtZ2xvYmFsXCI7XHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRGV2ZWxvcGVyOiBTcmlyYW0gIChnaXRodWIuY29tL3NyaXJhbS0yNClcclxuY29uc3QgdG9nZ2xlTmF2aWdhdGlvbiA9IChpc1NpZGViYXJPcGVuKSA9PntcclxuY29uc29sZS5lcnJvcihkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiLm14LXNjcm9sbGNvbnRhaW5lci1zaHJpbmtcIikuY2xhc3NMaXN0LmNvbnRhaW5zKCdteC1zY3JvbGxjb250YWluZXItb3BlbicpKVxyXG5cdGlmKFx0aXNTaWRlYmFyT3BlbiAgKXtcclxuXHRcdFxyXG5cdGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIubXgtc2Nyb2xsY29udGFpbmVyLXNocmlua1wiKS5jbGFzc0xpc3QuYWRkKCdteC1zY3JvbGxjb250YWluZXItb3BlbicpXHJcblx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIi5yZWdpb24tc2lkZWJhclwiKS5jbGFzc0xpc3QuYWRkKCdteC1zY3JvbGxjb250YWluZXItbW92ZS1pbicpXHJcblx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIi5yZWdpb24tc2lkZWJhclwiKS5zdHlsZS53aWR0aD1cIjIzMnB4XCI7XHJcbn1cclxuZWxzZXtcclxuXHRkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiLm14LXNjcm9sbGNvbnRhaW5lci1zaHJpbmtcIikuY2xhc3NMaXN0LnJlbW92ZSgnbXgtc2Nyb2xsY29udGFpbmVyLW9wZW4nKVxyXG5cdGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIucmVnaW9uLXNpZGViYXJcIikuY2xhc3NMaXN0LnJlbW92ZSgnbXgtc2Nyb2xsY29udGFpbmVyLW1vdmUtaW4nKTtcclxuXHQvLyBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiLnJlZ2lvbi1zaWRlYmFyXCIpLmNsYXNzTGlzdC5hZGQoJ214LXNjcm9sbGNvbnRhaW5lci1tb3ZlLW91dCcpO1xyXG5cdGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIucmVnaW9uLXNpZGViYXJcIikuc3R5bGUud2lkdGg9XCIwcHhcIjtcclxufVxyXG59XHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHBhcmFtIHtib29sZWFufSBpc1NpZGViYXJPcGVuXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBKU19Ub2dnbGVOYXZpZ2F0aW9uKGlzU2lkZWJhck9wZW4pIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuXHR0b2dnbGVOYXZpZ2F0aW9uKGlzU2lkZWJhck9wZW4pXHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIm1vZHVsZS5leHBvcnRzID0gX19XRUJQQUNLX0VYVEVSTkFMX01PRFVMRV9iaWdfanNfXzsiLCIvKiBlbXB0eSAqLyIsIi8vIFRoZSBtb2R1bGUgY2FjaGVcbnZhciBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX18gPSB7fTtcblxuLy8gVGhlIHJlcXVpcmUgZnVuY3Rpb25cbmZ1bmN0aW9uIF9fd2VicGFja19yZXF1aXJlX18obW9kdWxlSWQpIHtcblx0Ly8gQ2hlY2sgaWYgbW9kdWxlIGlzIGluIGNhY2hlXG5cdHZhciBjYWNoZWRNb2R1bGUgPSBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX19bbW9kdWxlSWRdO1xuXHRpZiAoY2FjaGVkTW9kdWxlICE9PSB1bmRlZmluZWQpIHtcblx0XHRyZXR1cm4gY2FjaGVkTW9kdWxlLmV4cG9ydHM7XG5cdH1cblx0Ly8gQ3JlYXRlIGEgbmV3IG1vZHVsZSAoYW5kIHB1dCBpdCBpbnRvIHRoZSBjYWNoZSlcblx0dmFyIG1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF0gPSB7XG5cdFx0Ly8gbm8gbW9kdWxlLmlkIG5lZWRlZFxuXHRcdC8vIG5vIG1vZHVsZS5sb2FkZWQgbmVlZGVkXG5cdFx0ZXhwb3J0czoge31cblx0fTtcblxuXHQvLyBFeGVjdXRlIHRoZSBtb2R1bGUgZnVuY3Rpb25cblx0X193ZWJwYWNrX21vZHVsZXNfX1ttb2R1bGVJZF0obW9kdWxlLCBtb2R1bGUuZXhwb3J0cywgX193ZWJwYWNrX3JlcXVpcmVfXyk7XG5cblx0Ly8gUmV0dXJuIHRoZSBleHBvcnRzIG9mIHRoZSBtb2R1bGVcblx0cmV0dXJuIG1vZHVsZS5leHBvcnRzO1xufVxuXG4iLCIvLyBnZXREZWZhdWx0RXhwb3J0IGZ1bmN0aW9uIGZvciBjb21wYXRpYmlsaXR5IHdpdGggbm9uLWhhcm1vbnkgbW9kdWxlc1xuX193ZWJwYWNrX3JlcXVpcmVfXy5uID0gKG1vZHVsZSkgPT4ge1xuXHR2YXIgZ2V0dGVyID0gbW9kdWxlICYmIG1vZHVsZS5fX2VzTW9kdWxlID9cblx0XHQoKSA9PiAobW9kdWxlWydkZWZhdWx0J10pIDpcblx0XHQoKSA9PiAobW9kdWxlKTtcblx0X193ZWJwYWNrX3JlcXVpcmVfXy5kKGdldHRlciwgeyBhOiBnZXR0ZXIgfSk7XG5cdHJldHVybiBnZXR0ZXI7XG59OyIsIi8vIGRlZmluZSBnZXR0ZXIgZnVuY3Rpb25zIGZvciBoYXJtb255IGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uZCA9IChleHBvcnRzLCBkZWZpbml0aW9uKSA9PiB7XG5cdGZvcih2YXIga2V5IGluIGRlZmluaXRpb24pIHtcblx0XHRpZihfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZGVmaW5pdGlvbiwga2V5KSAmJiAhX193ZWJwYWNrX3JlcXVpcmVfXy5vKGV4cG9ydHMsIGtleSkpIHtcblx0XHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBrZXksIHsgZW51bWVyYWJsZTogdHJ1ZSwgZ2V0OiBkZWZpbml0aW9uW2tleV0gfSk7XG5cdFx0fVxuXHR9XG59OyIsIl9fd2VicGFja19yZXF1aXJlX18ubyA9IChvYmosIHByb3ApID0+IChPYmplY3QucHJvdG90eXBlLmhhc093blByb3BlcnR5LmNhbGwob2JqLCBwcm9wKSkiLCIvLyBkZWZpbmUgX19lc01vZHVsZSBvbiBleHBvcnRzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLnIgPSAoZXhwb3J0cykgPT4ge1xuXHRpZih0eXBlb2YgU3ltYm9sICE9PSAndW5kZWZpbmVkJyAmJiBTeW1ib2wudG9TdHJpbmdUYWcpIHtcblx0XHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywgU3ltYm9sLnRvU3RyaW5nVGFnLCB7IHZhbHVlOiAnTW9kdWxlJyB9KTtcblx0fVxuXHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywgJ19fZXNNb2R1bGUnLCB7IHZhbHVlOiB0cnVlIH0pO1xufTsiLCJleHBvcnQgY29uc3QgTXlGaXJzdE1vZHVsZSRKU19Ub2dnbGVOYXZpZ2F0aW9uID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL2tyaXNoL09uZURyaXZlL0RvY3VtZW50cy9NZW5kaXgvU05UQy1tYWluL2phdmFzY3JpcHRzb3VyY2UvbXlmaXJzdG1vZHVsZS9hY3Rpb25zL0pTX1RvZ2dsZU5hdmlnYXRpb25cIikpLkpTX1RvZ2dsZU5hdmlnYXRpb247XG4iXSwibmFtZXMiOlsiQmlnIiwidG9nZ2xlTmF2aWdhdGlvbiIsImlzU2lkZWJhck9wZW4iLCJjb25zb2xlIiwiZXJyb3IiLCJkb2N1bWVudCIsInF1ZXJ5U2VsZWN0b3IiLCJjbGFzc0xpc3QiLCJjb250YWlucyIsImFkZCIsInN0eWxlIiwid2lkdGgiLCJyZW1vdmUiLCJKU19Ub2dnbGVOYXZpZ2F0aW9uIiwiTXlGaXJzdE1vZHVsZSRKU19Ub2dnbGVOYXZpZ2F0aW9uIl0sInNvdXJjZVJvb3QiOiIifQ==