// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicform.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the DynamicForm module
	public static dynamicform.proxies.Template act_CreateNewBoolean(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewBoolean").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static dynamicform.proxies.Template act_CreateNewDate(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewDate").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static dynamicform.proxies.Template act_CreateNewDecimal(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewDecimal").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static dynamicform.proxies.Template act_CreateNewDoc_Copy_of_LegalGuardian_Court(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewDoc_Copy_of_LegalGuardian_Court").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static dynamicform.proxies.Template act_CreateNewDoc_Copy_of_NRIC(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewDoc_Copy_of_NRIC").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static dynamicform.proxies.Template act_CreateNewDoc_Copy_of_PSN_BirthCertificate(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewDoc_Copy_of_PSN_BirthCertificate").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static dynamicform.proxies.Template act_CreateNewDoc_Copy_of_PSN_PR_Certificate(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewDoc_Copy_of_PSN_PR_Certificate").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static dynamicform.proxies.Template act_CreateNewDoc_Copy_of_PSN_SPEDCertificate(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewDoc_Copy_of_PSN_SPEDCertificate").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static void act_CreateNewEnum_citizenship(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewEnum_citizenship").withParams(params).execute(context);
	}
	public static void act_CreateNewEnum_gender(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewEnum_gender").withParams(params).execute(context);
	}
	public static void act_CreateNewEnum_PSN_citizenship(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewEnum_PSN_citizenship").withParams(params).execute(context);
	}
	public static void act_CreateNewEnum_PSN_gender(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewEnum_PSN_gender").withParams(params).execute(context);
	}
	public static void act_CreateNewEnum_relationship_to_psn(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewEnum_relationship_to_psn").withParams(params).execute(context);
	}
	public static void act_CreateNewNumber_Applicant_Age(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewNumber_Applicant_Age").withParams(params).execute(context);
	}
	public static dynamicform.proxies.Template act_CreateNewNumber_PSN_Age(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateNewNumber_PSN_Age").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static void act_CreateNewString_Applicant_address(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewString_Applicant_address").withParams(params).execute(context);
	}
	public static void act_CreateNewString_Applicant_Email(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewString_Applicant_Email").withParams(params).execute(context);
	}
	public static void act_CreateNewString_applicant_name(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewString_applicant_name").withParams(params).execute(context);
	}
	public static void act_CreateNewString_Applicant_PhoneNo(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewString_Applicant_PhoneNo").withParams(params).execute(context);
	}
	public static void act_CreateNewString_NRIC(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewString_NRIC").withParams(params).execute(context);
	}
	public static void act_CreateNewString_PSN_DisabilityType(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewString_PSN_DisabilityType").withParams(params).execute(context);
	}
	public static void act_CreateNewString_PSN_name(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewString_PSN_name").withParams(params).execute(context);
	}
	public static void act_CreateNewString_PSN_NRIC(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_CreateNewString_PSN_NRIC").withParams(params).execute(context);
	}
	public static dynamicform.proxies.Template act_CreateTime(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_CreateTime").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static void act_DeleteBoolean(IContext context, dynamicform.proxies.Boolean_ _string, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string == null ? null : _string.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteBoolean").withParams(params).execute(context);
	}
	public static void act_DeleteDate(IContext context, dynamicform.proxies.Date _dateAndTime, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DateAndTime", _dateAndTime == null ? null : _dateAndTime.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteDate").withParams(params).execute(context);
	}
	public static void act_DeleteDecimal(IContext context, dynamicform.proxies.Decimal _string, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string == null ? null : _string.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteDecimal").withParams(params).execute(context);
	}
	public static void act_DeleteDescrpition(IContext context, dynamicform.proxies.Descrpition _string, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string == null ? null : _string.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteDescrpition").withParams(params).execute(context);
	}
	public static void act_DeleteDoc(IContext context, dynamicform.proxies.Doc _string, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string == null ? null : _string.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteDoc").withParams(params).execute(context);
	}
	public static void act_DeleteEnum(IContext context, dynamicform.proxies.Enumeration _enum, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Enum", _enum == null ? null : _enum.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteEnum").withParams(params).execute(context);
	}
	public static void act_DeleteNumber(IContext context, dynamicform.proxies.Number _number, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteNumber").withParams(params).execute(context);
	}
	public static void act_DeleteString(IContext context, dynamicform.proxies.String1 _string, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string == null ? null : _string.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteString").withParams(params).execute(context);
	}
	public static void act_DeleteTime(IContext context, dynamicform.proxies.Time _time, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Time", _time == null ? null : _time.getMendixObject());
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("DynamicForm.Act_DeleteTime").withParams(params).execute(context);
	}
	public static dynamicform.proxies.Template act_Description(IContext context, dynamicform.proxies.Template _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customer", _customer == null ? null : _customer.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.Act_Description").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static void act_MakeActive(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_MakeActive").withParams(params).execute(context);
	}
	public static void act_MakeInactive(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_MakeInactive").withParams(params).execute(context);
	}
	public static void act_SaveTEmplate(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_SaveTEmplate").withParams(params).execute(context);
	}
	public static void aCT_Setting_current_dateTime(IContext context, dynamicform.proxies.Element _element)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element == null ? null : _element.getMendixObject());
		Core.microflowCall("DynamicForm.ACT_Setting_current_dateTime").withParams(params).execute(context);
	}
	public static void act_ShowTemplatePage(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_ShowTemplatePage").withParams(params).execute(context);
	}
	public static void act_Template_save(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Act_Template_save").withParams(params).execute(context);
	}
	public static boolean calculate_all_formulae(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DynamicForm.Calculate_all_formulae").withParams(params).execute(context);
	}
	public static void clone_Template_Cloneobject(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Clone_Template_Cloneobject").withParams(params).execute(context);
	}
	public static void ds_GetDefTemplate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DynamicForm.Ds_GetDefTemplate").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.Element> dS_retreive_template(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.DS_retreive_template").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> dynamicform.proxies.Element.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static dynamicform.proxies.Template ds_rtrvtmplt(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DynamicForm.ds_rtrvtmplt").withParams(params).execute(context);
		return result == null ? null : dynamicform.proxies.Template.initialize(context, result);
	}
	public static void formula_Calculation_MF(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		Core.microflowCall("DynamicForm.Formula_Calculation_MF").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.Number> get_assoc_Numb_Obj_for_Grid(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.Get_assoc_Numb_Obj_for_Grid").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> dynamicform.proxies.Number.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<dynamicform.proxies.Number> get_assoc_Numb_Obj_for_Java(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.Get_assoc_Numb_Obj_for_Java").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> dynamicform.proxies.Number.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void map_EnumValue_to_Enum(IContext context, dynamicform.proxies.Enumeration _enumeration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Enumeration", _enumeration == null ? null : _enumeration.getMendixObject());
		Core.microflowCall("DynamicForm.Map_EnumValue_to_Enum").withParams(params).execute(context);
	}
	public static void oCH_NumberValue(IContext context, dynamicform.proxies.Number _number, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.OCH_NumberValue").withParams(params).execute(context);
	}
	public static void oCH_Open_Dynamic_Page(IContext context, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.OCH_Open_Dynamic_Page").withParams(params).execute(context);
	}
	public static java.util.List<dynamicform.proxies.Enum_Values> retrieve_assoc_Obj(IContext context, dynamicform.proxies.Enumeration _enumeration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Enumeration", _enumeration == null ? null : _enumeration.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DynamicForm.Retrieve_assoc_Obj").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> dynamicform.proxies.Enum_Values.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void save_Number_Value(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		Core.microflowCall("DynamicForm.Save_Number_Value").withParams(params).execute(context);
	}
	public static void save_Number_Value_2(IContext context, dynamicform.proxies.Number _number)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Number", _number == null ? null : _number.getMendixObject());
		Core.microflowCall("DynamicForm.Save_Number_Value_2").withParams(params).execute(context);
	}
	public static void sub_CheckElements(IContext context, java.util.List<dynamicform.proxies.Element> _elementList, dynamicform.proxies.Element _mainElement, java.util.List<dynamicform.proxies.Element> _elementListMain)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> listparam_elementList = null;
		if (_elementList != null)
		{
			listparam_elementList = new java.util.ArrayList<>();
			for (var obj : _elementList) {
				listparam_elementList.add(obj.getMendixObject());
			}
		}
		params.put("ElementList", listparam_elementList);

		params.put("MainElement", _mainElement == null ? null : _mainElement.getMendixObject());
		java.util.List<IMendixObject> listparam_elementListMain = null;
		if (_elementListMain != null)
		{
			listparam_elementListMain = new java.util.ArrayList<>();
			for (var obj : _elementListMain) {
				listparam_elementListMain.add(obj.getMendixObject());
			}
		}
		params.put("ElementListMain", listparam_elementListMain);

		Core.microflowCall("DynamicForm.Sub_CheckElements").withParams(params).execute(context);
	}
	public static void sub_CloneElementObjects(IContext context, dynamicform.proxies.Element _element, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element == null ? null : _element.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("DynamicForm.Sub_CloneElementObjects").withParams(params).execute(context);
	}
}
