// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Accountuser_workflowuser
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject accountuser_workflowuserMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Accountuser_workflowuser";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Approval("Approval"),
		display("display"),
		Order("Order"),
		UserRole("UserRole"),
		Accountuser_workflowuser_Applicant("MyFirstModule.Accountuser_workflowuser_Applicant"),
		Accountuser_workflowuser_WorkflowUsers("MyFirstModule.Accountuser_workflowuser_WorkflowUsers"),
		Accountuser_workflowuser_Account("MyFirstModule.Accountuser_workflowuser_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Accountuser_workflowuser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Accountuser_workflowuser(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountuser_workflowuserMendixObject)
	{
		if (accountuser_workflowuserMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, accountuser_workflowuserMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.accountuser_workflowuserMendixObject = accountuser_workflowuserMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Accountuser_workflowuser.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Accountuser_workflowuser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Accountuser_workflowuser.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Accountuser_workflowuser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Accountuser_workflowuser(context, mendixObject);
	}

	public static myfirstmodule.proxies.Accountuser_workflowuser load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Accountuser_workflowuser.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Accountuser_workflowuser> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Accountuser_workflowuser.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Approval
	 */
	public final java.lang.Boolean getApproval()
	{
		return getApproval(getContext());
	}

	/**
	 * @param context
	 * @return value of Approval
	 */
	public final java.lang.Boolean getApproval(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Approval.toString());
	}

	/**
	 * Set value of Approval
	 * @param approval
	 */
	public final void setApproval(java.lang.Boolean approval)
	{
		setApproval(getContext(), approval);
	}

	/**
	 * Set value of Approval
	 * @param context
	 * @param approval
	 */
	public final void setApproval(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean approval)
	{
		getMendixObject().setValue(context, MemberNames.Approval.toString(), approval);
	}

	/**
	 * @return value of display
	 */
	public final java.lang.Boolean getdisplay()
	{
		return getdisplay(getContext());
	}

	/**
	 * @param context
	 * @return value of display
	 */
	public final java.lang.Boolean getdisplay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.display.toString());
	}

	/**
	 * Set value of display
	 * @param display
	 */
	public final void setdisplay(java.lang.Boolean display)
	{
		setdisplay(getContext(), display);
	}

	/**
	 * Set value of display
	 * @param context
	 * @param display
	 */
	public final void setdisplay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean display)
	{
		getMendixObject().setValue(context, MemberNames.display.toString(), display);
	}

	/**
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder()
	{
		return getOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Order.toString());
	}

	/**
	 * Set value of Order
	 * @param order
	 */
	public final void setOrder(java.lang.Integer order)
	{
		setOrder(getContext(), order);
	}

	/**
	 * Set value of Order
	 * @param context
	 * @param order
	 */
	public final void setOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer order)
	{
		getMendixObject().setValue(context, MemberNames.Order.toString(), order);
	}

	/**
	 * @return value of UserRole
	 */
	public final java.lang.String getUserRole()
	{
		return getUserRole(getContext());
	}

	/**
	 * @param context
	 * @return value of UserRole
	 */
	public final java.lang.String getUserRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserRole.toString());
	}

	/**
	 * Set value of UserRole
	 * @param userrole
	 */
	public final void setUserRole(java.lang.String userrole)
	{
		setUserRole(getContext(), userrole);
	}

	/**
	 * Set value of UserRole
	 * @param context
	 * @param userrole
	 */
	public final void setUserRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userrole)
	{
		getMendixObject().setValue(context, MemberNames.UserRole.toString(), userrole);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Accountuser_workflowuser_Applicant
	 */
	public final myfirstmodule.proxies.Applicant getAccountuser_workflowuser_Applicant() throws com.mendix.core.CoreException
	{
		return getAccountuser_workflowuser_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of Accountuser_workflowuser_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant getAccountuser_workflowuser_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Accountuser_workflowuser_Applicant.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Accountuser_workflowuser_Applicant
	 * @param accountuser_workflowuser_applicant
	 */
	public final void setAccountuser_workflowuser_Applicant(myfirstmodule.proxies.Applicant accountuser_workflowuser_applicant)
	{
		setAccountuser_workflowuser_Applicant(getContext(), accountuser_workflowuser_applicant);
	}

	/**
	 * Set value of Accountuser_workflowuser_Applicant
	 * @param context
	 * @param accountuser_workflowuser_applicant
	 */
	public final void setAccountuser_workflowuser_Applicant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant accountuser_workflowuser_applicant)
	{
		if (accountuser_workflowuser_applicant == null) {
			getMendixObject().setValue(context, MemberNames.Accountuser_workflowuser_Applicant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Accountuser_workflowuser_Applicant.toString(), accountuser_workflowuser_applicant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Accountuser_workflowuser_WorkflowUsers
	 */
	public final dynamicworkflow.proxies.WorkflowUsers getAccountuser_workflowuser_WorkflowUsers() throws com.mendix.core.CoreException
	{
		return getAccountuser_workflowuser_WorkflowUsers(getContext());
	}

	/**
	 * @param context
	 * @return value of Accountuser_workflowuser_WorkflowUsers
	 * @throws com.mendix.core.CoreException
	 */
	public final dynamicworkflow.proxies.WorkflowUsers getAccountuser_workflowuser_WorkflowUsers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicworkflow.proxies.WorkflowUsers result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Accountuser_workflowuser_WorkflowUsers.toString());
		if (identifier != null) {
			result = dynamicworkflow.proxies.WorkflowUsers.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Accountuser_workflowuser_WorkflowUsers
	 * @param accountuser_workflowuser_workflowusers
	 */
	public final void setAccountuser_workflowuser_WorkflowUsers(dynamicworkflow.proxies.WorkflowUsers accountuser_workflowuser_workflowusers)
	{
		setAccountuser_workflowuser_WorkflowUsers(getContext(), accountuser_workflowuser_workflowusers);
	}

	/**
	 * Set value of Accountuser_workflowuser_WorkflowUsers
	 * @param context
	 * @param accountuser_workflowuser_workflowusers
	 */
	public final void setAccountuser_workflowuser_WorkflowUsers(com.mendix.systemwideinterfaces.core.IContext context, dynamicworkflow.proxies.WorkflowUsers accountuser_workflowuser_workflowusers)
	{
		if (accountuser_workflowuser_workflowusers == null) {
			getMendixObject().setValue(context, MemberNames.Accountuser_workflowuser_WorkflowUsers.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Accountuser_workflowuser_WorkflowUsers.toString(), accountuser_workflowuser_workflowusers.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Accountuser_workflowuser_Account
	 */
	public final administration.proxies.Account getAccountuser_workflowuser_Account() throws com.mendix.core.CoreException
	{
		return getAccountuser_workflowuser_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Accountuser_workflowuser_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getAccountuser_workflowuser_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Accountuser_workflowuser_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Accountuser_workflowuser_Account
	 * @param accountuser_workflowuser_account
	 */
	public final void setAccountuser_workflowuser_Account(administration.proxies.Account accountuser_workflowuser_account)
	{
		setAccountuser_workflowuser_Account(getContext(), accountuser_workflowuser_account);
	}

	/**
	 * Set value of Accountuser_workflowuser_Account
	 * @param context
	 * @param accountuser_workflowuser_account
	 */
	public final void setAccountuser_workflowuser_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account accountuser_workflowuser_account)
	{
		if (accountuser_workflowuser_account == null) {
			getMendixObject().setValue(context, MemberNames.Accountuser_workflowuser_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Accountuser_workflowuser_Account.toString(), accountuser_workflowuser_account.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return accountuser_workflowuserMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Accountuser_workflowuser that = (myfirstmodule.proxies.Accountuser_workflowuser) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
