// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class AutoSearch
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject autoSearchMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.AutoSearch";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NRIC_Number("NRIC_Number"),
		AutoSearch_Applicant("MyFirstModule.AutoSearch_Applicant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AutoSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AutoSearch(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject autoSearchMendixObject)
	{
		if (autoSearchMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, autoSearchMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.autoSearchMendixObject = autoSearchMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AutoSearch.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.AutoSearch initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.AutoSearch.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.AutoSearch initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.AutoSearch(context, mendixObject);
	}

	public static myfirstmodule.proxies.AutoSearch load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.AutoSearch.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NRIC_Number
	 */
	public final java.lang.String getNRIC_Number()
	{
		return getNRIC_Number(getContext());
	}

	/**
	 * @param context
	 * @return value of NRIC_Number
	 */
	public final java.lang.String getNRIC_Number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NRIC_Number.toString());
	}

	/**
	 * Set value of NRIC_Number
	 * @param nric_number
	 */
	public final void setNRIC_Number(java.lang.String nric_number)
	{
		setNRIC_Number(getContext(), nric_number);
	}

	/**
	 * Set value of NRIC_Number
	 * @param context
	 * @param nric_number
	 */
	public final void setNRIC_Number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nric_number)
	{
		getMendixObject().setValue(context, MemberNames.NRIC_Number.toString(), nric_number);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AutoSearch_Applicant
	 */
	public final myfirstmodule.proxies.Applicant getAutoSearch_Applicant() throws com.mendix.core.CoreException
	{
		return getAutoSearch_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoSearch_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant getAutoSearch_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutoSearch_Applicant.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AutoSearch_Applicant
	 * @param autosearch_applicant
	 */
	public final void setAutoSearch_Applicant(myfirstmodule.proxies.Applicant autosearch_applicant)
	{
		setAutoSearch_Applicant(getContext(), autosearch_applicant);
	}

	/**
	 * Set value of AutoSearch_Applicant
	 * @param context
	 * @param autosearch_applicant
	 */
	public final void setAutoSearch_Applicant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant autosearch_applicant)
	{
		if (autosearch_applicant == null) {
			getMendixObject().setValue(context, MemberNames.AutoSearch_Applicant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AutoSearch_Applicant.toString(), autosearch_applicant.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return autoSearchMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.AutoSearch that = (myfirstmodule.proxies.AutoSearch) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
