// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class CareGiver
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject careGiverMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.CareGiver";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		NRIC_PassportNo("NRIC_PassportNo"),
		RelationToSettlor("RelationToSettlor"),
		RelationToLB("RelationToLB"),
		Address("Address"),
		Dob("Dob"),
		HomeTel("HomeTel"),
		Mobile("Mobile"),
		Email("Email"),
		CareGiver_Applicant("MyFirstModule.CareGiver_Applicant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CareGiver(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CareGiver(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject careGiverMendixObject)
	{
		if (careGiverMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, careGiverMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.careGiverMendixObject = careGiverMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CareGiver.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.CareGiver initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.CareGiver.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.CareGiver initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.CareGiver(context, mendixObject);
	}

	public static myfirstmodule.proxies.CareGiver load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.CareGiver.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.CareGiver> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.CareGiver.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of NRIC_PassportNo
	 */
	public final java.lang.String getNRIC_PassportNo()
	{
		return getNRIC_PassportNo(getContext());
	}

	/**
	 * @param context
	 * @return value of NRIC_PassportNo
	 */
	public final java.lang.String getNRIC_PassportNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NRIC_PassportNo.toString());
	}

	/**
	 * Set value of NRIC_PassportNo
	 * @param nric_passportno
	 */
	public final void setNRIC_PassportNo(java.lang.String nric_passportno)
	{
		setNRIC_PassportNo(getContext(), nric_passportno);
	}

	/**
	 * Set value of NRIC_PassportNo
	 * @param context
	 * @param nric_passportno
	 */
	public final void setNRIC_PassportNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nric_passportno)
	{
		getMendixObject().setValue(context, MemberNames.NRIC_PassportNo.toString(), nric_passportno);
	}

	/**
	 * @return value of RelationToSettlor
	 */
	public final java.lang.String getRelationToSettlor()
	{
		return getRelationToSettlor(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationToSettlor
	 */
	public final java.lang.String getRelationToSettlor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RelationToSettlor.toString());
	}

	/**
	 * Set value of RelationToSettlor
	 * @param relationtosettlor
	 */
	public final void setRelationToSettlor(java.lang.String relationtosettlor)
	{
		setRelationToSettlor(getContext(), relationtosettlor);
	}

	/**
	 * Set value of RelationToSettlor
	 * @param context
	 * @param relationtosettlor
	 */
	public final void setRelationToSettlor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relationtosettlor)
	{
		getMendixObject().setValue(context, MemberNames.RelationToSettlor.toString(), relationtosettlor);
	}

	/**
	 * @return value of RelationToLB
	 */
	public final java.lang.String getRelationToLB()
	{
		return getRelationToLB(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationToLB
	 */
	public final java.lang.String getRelationToLB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RelationToLB.toString());
	}

	/**
	 * Set value of RelationToLB
	 * @param relationtolb
	 */
	public final void setRelationToLB(java.lang.String relationtolb)
	{
		setRelationToLB(getContext(), relationtolb);
	}

	/**
	 * Set value of RelationToLB
	 * @param context
	 * @param relationtolb
	 */
	public final void setRelationToLB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relationtolb)
	{
		getMendixObject().setValue(context, MemberNames.RelationToLB.toString(), relationtolb);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of Dob
	 */
	public final java.util.Date getDob()
	{
		return getDob(getContext());
	}

	/**
	 * @param context
	 * @return value of Dob
	 */
	public final java.util.Date getDob(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Dob.toString());
	}

	/**
	 * Set value of Dob
	 * @param dob
	 */
	public final void setDob(java.util.Date dob)
	{
		setDob(getContext(), dob);
	}

	/**
	 * Set value of Dob
	 * @param context
	 * @param dob
	 */
	public final void setDob(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dob)
	{
		getMendixObject().setValue(context, MemberNames.Dob.toString(), dob);
	}

	/**
	 * @return value of HomeTel
	 */
	public final java.lang.Integer getHomeTel()
	{
		return getHomeTel(getContext());
	}

	/**
	 * @param context
	 * @return value of HomeTel
	 */
	public final java.lang.Integer getHomeTel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.HomeTel.toString());
	}

	/**
	 * Set value of HomeTel
	 * @param hometel
	 */
	public final void setHomeTel(java.lang.Integer hometel)
	{
		setHomeTel(getContext(), hometel);
	}

	/**
	 * Set value of HomeTel
	 * @param context
	 * @param hometel
	 */
	public final void setHomeTel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer hometel)
	{
		getMendixObject().setValue(context, MemberNames.HomeTel.toString(), hometel);
	}

	/**
	 * @return value of Mobile
	 */
	public final java.lang.Integer getMobile()
	{
		return getMobile(getContext());
	}

	/**
	 * @param context
	 * @return value of Mobile
	 */
	public final java.lang.Integer getMobile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Mobile.toString());
	}

	/**
	 * Set value of Mobile
	 * @param mobile
	 */
	public final void setMobile(java.lang.Integer mobile)
	{
		setMobile(getContext(), mobile);
	}

	/**
	 * Set value of Mobile
	 * @param context
	 * @param mobile
	 */
	public final void setMobile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer mobile)
	{
		getMendixObject().setValue(context, MemberNames.Mobile.toString(), mobile);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CareGiver_Applicant
	 */
	public final myfirstmodule.proxies.Applicant getCareGiver_Applicant() throws com.mendix.core.CoreException
	{
		return getCareGiver_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of CareGiver_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant getCareGiver_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CareGiver_Applicant.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CareGiver_Applicant
	 * @param caregiver_applicant
	 */
	public final void setCareGiver_Applicant(myfirstmodule.proxies.Applicant caregiver_applicant)
	{
		setCareGiver_Applicant(getContext(), caregiver_applicant);
	}

	/**
	 * Set value of CareGiver_Applicant
	 * @param context
	 * @param caregiver_applicant
	 */
	public final void setCareGiver_Applicant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant caregiver_applicant)
	{
		if (caregiver_applicant == null) {
			getMendixObject().setValue(context, MemberNames.CareGiver_Applicant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CareGiver_Applicant.toString(), caregiver_applicant.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return careGiverMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.CareGiver that = (myfirstmodule.proxies.CareGiver) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
