// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Communication extends emailtemplate.proxies.EmailTemplate
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Communication";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		To_("To_"),
		From_("From_"),
		Date("Date"),
		TemplateName_("TemplateName_"),
		UserRoles("UserRoles"),
		Subject_("Subject_"),
		Body("Body"),
		Plain_Text("Plain_Text"),
		Requested_Type("Requested_Type"),
		TemplateName("TemplateName"),
		To("To"),
		From("From"),
		FromDisplayName("FromDisplayName"),
		ReplyTo("ReplyTo"),
		CC("CC"),
		BCC("BCC"),
		Subject("Subject"),
		HtmlBody("HtmlBody"),
		PlainBody("PlainBody"),
		CreationDate("CreationDate"),
		UseOnlyPlainText("UseOnlyPlainText"),
		Communication_Communciation_Template("MyFirstModule.Communication_Communciation_Template"),
		Communication_Applicant_2("MyFirstModule.Communication_Applicant_2"),
		Communication_Account("MyFirstModule.Communication_Account"),
		EmailTemplate_MxObjectType("EmailTemplate.EmailTemplate_MxObjectType"),
		EmailTemplate_Token("EmailTemplate.EmailTemplate_Token");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Communication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Communication(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject communicationMendixObject)
	{
		super(context, communicationMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, communicationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'Communication.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Communication initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Communication.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Communication initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Communication(context, mendixObject);
	}

	public static myfirstmodule.proxies.Communication load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Communication.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Communication> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Communication.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of To_
	 */
	public final java.lang.String getTo_()
	{
		return getTo_(getContext());
	}

	/**
	 * @param context
	 * @return value of To_
	 */
	public final java.lang.String getTo_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.To_.toString());
	}

	/**
	 * Set value of To_
	 * @param to_
	 */
	public final void setTo_(java.lang.String to_)
	{
		setTo_(getContext(), to_);
	}

	/**
	 * Set value of To_
	 * @param context
	 * @param to_
	 */
	public final void setTo_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String to_)
	{
		getMendixObject().setValue(context, MemberNames.To_.toString(), to_);
	}

	/**
	 * @return value of From_
	 */
	public final java.lang.String getFrom_()
	{
		return getFrom_(getContext());
	}

	/**
	 * @param context
	 * @return value of From_
	 */
	public final java.lang.String getFrom_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.From_.toString());
	}

	/**
	 * Set value of From_
	 * @param from_
	 */
	public final void setFrom_(java.lang.String from_)
	{
		setFrom_(getContext(), from_);
	}

	/**
	 * Set value of From_
	 * @param context
	 * @param from_
	 */
	public final void setFrom_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String from_)
	{
		getMendixObject().setValue(context, MemberNames.From_.toString(), from_);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of TemplateName_
	 */
	public final java.lang.String getTemplateName_()
	{
		return getTemplateName_(getContext());
	}

	/**
	 * @param context
	 * @return value of TemplateName_
	 */
	public final java.lang.String getTemplateName_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TemplateName_.toString());
	}

	/**
	 * Set value of TemplateName_
	 * @param templatename_
	 */
	public final void setTemplateName_(java.lang.String templatename_)
	{
		setTemplateName_(getContext(), templatename_);
	}

	/**
	 * Set value of TemplateName_
	 * @param context
	 * @param templatename_
	 */
	public final void setTemplateName_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String templatename_)
	{
		getMendixObject().setValue(context, MemberNames.TemplateName_.toString(), templatename_);
	}

	/**
	 * @return value of UserRoles
	 */
	public final java.lang.String getUserRoles()
	{
		return getUserRoles(getContext());
	}

	/**
	 * @param context
	 * @return value of UserRoles
	 */
	public final java.lang.String getUserRoles(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserRoles.toString());
	}

	/**
	 * Set value of UserRoles
	 * @param userroles
	 */
	public final void setUserRoles(java.lang.String userroles)
	{
		setUserRoles(getContext(), userroles);
	}

	/**
	 * Set value of UserRoles
	 * @param context
	 * @param userroles
	 */
	public final void setUserRoles(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userroles)
	{
		getMendixObject().setValue(context, MemberNames.UserRoles.toString(), userroles);
	}

	/**
	 * @return value of Subject_
	 */
	public final java.lang.String getSubject_()
	{
		return getSubject_(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject_
	 */
	public final java.lang.String getSubject_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject_.toString());
	}

	/**
	 * Set value of Subject_
	 * @param subject_
	 */
	public final void setSubject_(java.lang.String subject_)
	{
		setSubject_(getContext(), subject_);
	}

	/**
	 * Set value of Subject_
	 * @param context
	 * @param subject_
	 */
	public final void setSubject_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject_)
	{
		getMendixObject().setValue(context, MemberNames.Subject_.toString(), subject_);
	}

	/**
	 * @return value of Body
	 */
	public final java.lang.String getBody()
	{
		return getBody(getContext());
	}

	/**
	 * @param context
	 * @return value of Body
	 */
	public final java.lang.String getBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Body.toString());
	}

	/**
	 * Set value of Body
	 * @param body
	 */
	public final void setBody(java.lang.String body)
	{
		setBody(getContext(), body);
	}

	/**
	 * Set value of Body
	 * @param context
	 * @param body
	 */
	public final void setBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String body)
	{
		getMendixObject().setValue(context, MemberNames.Body.toString(), body);
	}

	/**
	 * @return value of Plain_Text
	 */
	public final java.lang.String getPlain_Text()
	{
		return getPlain_Text(getContext());
	}

	/**
	 * @param context
	 * @return value of Plain_Text
	 */
	public final java.lang.String getPlain_Text(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Plain_Text.toString());
	}

	/**
	 * Set value of Plain_Text
	 * @param plain_text
	 */
	public final void setPlain_Text(java.lang.String plain_text)
	{
		setPlain_Text(getContext(), plain_text);
	}

	/**
	 * Set value of Plain_Text
	 * @param context
	 * @param plain_text
	 */
	public final void setPlain_Text(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plain_text)
	{
		getMendixObject().setValue(context, MemberNames.Plain_Text.toString(), plain_text);
	}

	/**
	 * Set value of Requested_Type
	 * @param requested_type
	 */
	public final myfirstmodule.proxies.RequestedType getRequested_Type()
	{
		return getRequested_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Requested_Type
	 */
	public final myfirstmodule.proxies.RequestedType getRequested_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Requested_Type.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.RequestedType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Requested_Type
	 * @param requested_type
	 */
	public final void setRequested_Type(myfirstmodule.proxies.RequestedType requested_type)
	{
		setRequested_Type(getContext(), requested_type);
	}

	/**
	 * Set value of Requested_Type
	 * @param context
	 * @param requested_type
	 */
	public final void setRequested_Type(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RequestedType requested_type)
	{
		if (requested_type != null) {
			getMendixObject().setValue(context, MemberNames.Requested_Type.toString(), requested_type.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Requested_Type.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Communication_Communciation_Template
	 */
	public final myfirstmodule.proxies.Communciation_Template getCommunication_Communciation_Template() throws com.mendix.core.CoreException
	{
		return getCommunication_Communciation_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of Communication_Communciation_Template
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Communciation_Template getCommunication_Communciation_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Communciation_Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Communication_Communciation_Template.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Communciation_Template.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Communication_Communciation_Template
	 * @param communication_communciation_template
	 */
	public final void setCommunication_Communciation_Template(myfirstmodule.proxies.Communciation_Template communication_communciation_template)
	{
		setCommunication_Communciation_Template(getContext(), communication_communciation_template);
	}

	/**
	 * Set value of Communication_Communciation_Template
	 * @param context
	 * @param communication_communciation_template
	 */
	public final void setCommunication_Communciation_Template(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Communciation_Template communication_communciation_template)
	{
		if (communication_communciation_template == null) {
			getMendixObject().setValue(context, MemberNames.Communication_Communciation_Template.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Communication_Communciation_Template.toString(), communication_communciation_template.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Communication_Applicant_2
	 */
	public final myfirstmodule.proxies.Applicant_2 getCommunication_Applicant_2() throws com.mendix.core.CoreException
	{
		return getCommunication_Applicant_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Communication_Applicant_2
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant_2 getCommunication_Applicant_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Communication_Applicant_2.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Communication_Applicant_2
	 * @param communication_applicant_2
	 */
	public final void setCommunication_Applicant_2(myfirstmodule.proxies.Applicant_2 communication_applicant_2)
	{
		setCommunication_Applicant_2(getContext(), communication_applicant_2);
	}

	/**
	 * Set value of Communication_Applicant_2
	 * @param context
	 * @param communication_applicant_2
	 */
	public final void setCommunication_Applicant_2(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant_2 communication_applicant_2)
	{
		if (communication_applicant_2 == null) {
			getMendixObject().setValue(context, MemberNames.Communication_Applicant_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Communication_Applicant_2.toString(), communication_applicant_2.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Communication_Account
	 */
	public final administration.proxies.Account getCommunication_Account() throws com.mendix.core.CoreException
	{
		return getCommunication_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Communication_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getCommunication_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Communication_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Communication_Account
	 * @param communication_account
	 */
	public final void setCommunication_Account(administration.proxies.Account communication_account)
	{
		setCommunication_Account(getContext(), communication_account);
	}

	/**
	 * Set value of Communication_Account
	 * @param context
	 * @param communication_account
	 */
	public final void setCommunication_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account communication_account)
	{
		if (communication_account == null) {
			getMendixObject().setValue(context, MemberNames.Communication_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Communication_Account.toString(), communication_account.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Communication that = (myfirstmodule.proxies.Communication) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
