// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Contacts
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject contactsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Contacts";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Phone_Number("Phone_Number"),
		Email("Email"),
		Relationship_To_Applicant("Relationship_To_Applicant"),
		Contacts_Applicant("MyFirstModule.Contacts_Applicant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Contacts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Contacts(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject contactsMendixObject)
	{
		if (contactsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, contactsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.contactsMendixObject = contactsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Contacts.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Contacts initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Contacts.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Contacts initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Contacts(context, mendixObject);
	}

	public static myfirstmodule.proxies.Contacts load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Contacts.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Contacts> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Contacts.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Phone_Number
	 */
	public final java.lang.Long getPhone_Number()
	{
		return getPhone_Number(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone_Number
	 */
	public final java.lang.Long getPhone_Number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Phone_Number.toString());
	}

	/**
	 * Set value of Phone_Number
	 * @param phone_number
	 */
	public final void setPhone_Number(java.lang.Long phone_number)
	{
		setPhone_Number(getContext(), phone_number);
	}

	/**
	 * Set value of Phone_Number
	 * @param context
	 * @param phone_number
	 */
	public final void setPhone_Number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long phone_number)
	{
		getMendixObject().setValue(context, MemberNames.Phone_Number.toString(), phone_number);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Relationship_To_Applicant
	 */
	public final java.lang.String getRelationship_To_Applicant()
	{
		return getRelationship_To_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of Relationship_To_Applicant
	 */
	public final java.lang.String getRelationship_To_Applicant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Relationship_To_Applicant.toString());
	}

	/**
	 * Set value of Relationship_To_Applicant
	 * @param relationship_to_applicant
	 */
	public final void setRelationship_To_Applicant(java.lang.String relationship_to_applicant)
	{
		setRelationship_To_Applicant(getContext(), relationship_to_applicant);
	}

	/**
	 * Set value of Relationship_To_Applicant
	 * @param context
	 * @param relationship_to_applicant
	 */
	public final void setRelationship_To_Applicant(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relationship_to_applicant)
	{
		getMendixObject().setValue(context, MemberNames.Relationship_To_Applicant.toString(), relationship_to_applicant);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Contacts_Applicant
	 */
	public final myfirstmodule.proxies.Applicant getContacts_Applicant() throws com.mendix.core.CoreException
	{
		return getContacts_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of Contacts_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant getContacts_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Contacts_Applicant.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Contacts_Applicant
	 * @param contacts_applicant
	 */
	public final void setContacts_Applicant(myfirstmodule.proxies.Applicant contacts_applicant)
	{
		setContacts_Applicant(getContext(), contacts_applicant);
	}

	/**
	 * Set value of Contacts_Applicant
	 * @param context
	 * @param contacts_applicant
	 */
	public final void setContacts_Applicant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant contacts_applicant)
	{
		if (contacts_applicant == null) {
			getMendixObject().setValue(context, MemberNames.Contacts_Applicant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Contacts_Applicant.toString(), contacts_applicant.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return contactsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Contacts that = (myfirstmodule.proxies.Contacts) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
