// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Count
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Count";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Inprogress("Inprogress"),
		Approved("Approved"),
		Rejected("Rejected"),
		PendingforAction("PendingforAction"),
		Draft("Draft");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Count(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Count(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countMendixObject)
	{
		if (countMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, countMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.countMendixObject = countMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Count.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Count initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Count.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Count initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Count(context, mendixObject);
	}

	public static myfirstmodule.proxies.Count load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Count.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Count> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Count.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Inprogress
	 */
	public final java.lang.Integer getInprogress()
	{
		return getInprogress(getContext());
	}

	/**
	 * @param context
	 * @return value of Inprogress
	 */
	public final java.lang.Integer getInprogress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Inprogress.toString());
	}

	/**
	 * Set value of Inprogress
	 * @param inprogress
	 */
	public final void setInprogress(java.lang.Integer inprogress)
	{
		setInprogress(getContext(), inprogress);
	}

	/**
	 * Set value of Inprogress
	 * @param context
	 * @param inprogress
	 */
	public final void setInprogress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer inprogress)
	{
		getMendixObject().setValue(context, MemberNames.Inprogress.toString(), inprogress);
	}

	/**
	 * @return value of Approved
	 */
	public final java.lang.Integer getApproved()
	{
		return getApproved(getContext());
	}

	/**
	 * @param context
	 * @return value of Approved
	 */
	public final java.lang.Integer getApproved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Approved.toString());
	}

	/**
	 * Set value of Approved
	 * @param approved
	 */
	public final void setApproved(java.lang.Integer approved)
	{
		setApproved(getContext(), approved);
	}

	/**
	 * Set value of Approved
	 * @param context
	 * @param approved
	 */
	public final void setApproved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer approved)
	{
		getMendixObject().setValue(context, MemberNames.Approved.toString(), approved);
	}

	/**
	 * @return value of Rejected
	 */
	public final java.lang.Integer getRejected()
	{
		return getRejected(getContext());
	}

	/**
	 * @param context
	 * @return value of Rejected
	 */
	public final java.lang.Integer getRejected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rejected.toString());
	}

	/**
	 * Set value of Rejected
	 * @param rejected
	 */
	public final void setRejected(java.lang.Integer rejected)
	{
		setRejected(getContext(), rejected);
	}

	/**
	 * Set value of Rejected
	 * @param context
	 * @param rejected
	 */
	public final void setRejected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rejected)
	{
		getMendixObject().setValue(context, MemberNames.Rejected.toString(), rejected);
	}

	/**
	 * @return value of PendingforAction
	 */
	public final java.lang.Integer getPendingforAction()
	{
		return getPendingforAction(getContext());
	}

	/**
	 * @param context
	 * @return value of PendingforAction
	 */
	public final java.lang.Integer getPendingforAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PendingforAction.toString());
	}

	/**
	 * Set value of PendingforAction
	 * @param pendingforaction
	 */
	public final void setPendingforAction(java.lang.Integer pendingforaction)
	{
		setPendingforAction(getContext(), pendingforaction);
	}

	/**
	 * Set value of PendingforAction
	 * @param context
	 * @param pendingforaction
	 */
	public final void setPendingforAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pendingforaction)
	{
		getMendixObject().setValue(context, MemberNames.PendingforAction.toString(), pendingforaction);
	}

	/**
	 * @return value of Draft
	 */
	public final java.lang.Integer getDraft()
	{
		return getDraft(getContext());
	}

	/**
	 * @param context
	 * @return value of Draft
	 */
	public final java.lang.Integer getDraft(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Draft.toString());
	}

	/**
	 * Set value of Draft
	 * @param draft
	 */
	public final void setDraft(java.lang.Integer draft)
	{
		setDraft(getContext(), draft);
	}

	/**
	 * Set value of Draft
	 * @param context
	 * @param draft
	 */
	public final void setDraft(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer draft)
	{
		getMendixObject().setValue(context, MemberNames.Draft.toString(), draft);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Count that = (myfirstmodule.proxies.Count) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
