// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class CPF_documents extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.CPF_documents";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OwnerName("OwnerName"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		CPF_documents_Applicant("MyFirstModule.CPF_documents_Applicant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CPF_documents(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CPF_documents(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cPF_documentsMendixObject)
	{
		super(context, cPF_documentsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, cPF_documentsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'CPF_documents.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.CPF_documents initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.CPF_documents.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.CPF_documents initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.CPF_documents(context, mendixObject);
	}

	public static myfirstmodule.proxies.CPF_documents load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.CPF_documents.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.CPF_documents> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.CPF_documents.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName()
	{
		return getOwnerName(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OwnerName.toString());
	}

	/**
	 * Set value of OwnerName
	 * @param ownername
	 */
	public final void setOwnerName(java.lang.String ownername)
	{
		setOwnerName(getContext(), ownername);
	}

	/**
	 * Set value of OwnerName
	 * @param context
	 * @param ownername
	 */
	public final void setOwnerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ownername)
	{
		getMendixObject().setValue(context, MemberNames.OwnerName.toString(), ownername);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CPF_documents_Applicant
	 */
	public final java.util.List<myfirstmodule.proxies.Applicant> getCPF_documents_Applicant() throws com.mendix.core.CoreException
	{
		return getCPF_documents_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of CPF_documents_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.Applicant> getCPF_documents_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Applicant> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.CPF_documents_Applicant.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(myfirstmodule.proxies.Applicant.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of CPF_documents_Applicant
	 * @param cpf_documents_applicant
	 */
	public final void setCPF_documents_Applicant(java.util.List<myfirstmodule.proxies.Applicant> cpf_documents_applicant)
	{
		setCPF_documents_Applicant(getContext(), cpf_documents_applicant);
	}

	/**
	 * Set value of CPF_documents_Applicant
	 * @param context
	 * @param cpf_documents_applicant
	 */
	public final void setCPF_documents_Applicant(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.Applicant> cpf_documents_applicant)
	{
		var identifiers = cpf_documents_applicant
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.CPF_documents_Applicant.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.CPF_documents that = (myfirstmodule.proxies.CPF_documents) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
