// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class DeclarationSettlor
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject declarationSettlorMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.DeclarationSettlor";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Beneficiary_is_a_person_with_a_permanent_disability("Beneficiary_is_a_person_with_a_permanent_disability"),
		BeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore("BeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore"),
		Trust_assets_are_in_cash_only("Trust_assets_are_in_cash_only"),
		Assets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash("Assets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash"),
		The_initial_capital_to_setup_the_trust_account_is_atleast_5000("The_initial_capital_to_setup_the_trust_account_is_atleast_5000"),
		No_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary("No_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary"),
		Settlor_is_not_an_undischarged_bankrupt("Settlor_is_not_an_undischarged_bankrupt"),
		Settlor_is_of_sound_mind("Settlor_is_of_sound_mind"),
		The_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will("The_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeclarationSettlor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DeclarationSettlor(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject declarationSettlorMendixObject)
	{
		if (declarationSettlorMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, declarationSettlorMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.declarationSettlorMendixObject = declarationSettlorMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DeclarationSettlor.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.DeclarationSettlor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.DeclarationSettlor.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.DeclarationSettlor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.DeclarationSettlor(context, mendixObject);
	}

	public static myfirstmodule.proxies.DeclarationSettlor load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.DeclarationSettlor.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.DeclarationSettlor> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.DeclarationSettlor.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Beneficiary_is_a_person_with_a_permanent_disability
	 * @param beneficiary_is_a_person_with_a_permanent_disability
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getBeneficiary_is_a_person_with_a_permanent_disability()
	{
		return getBeneficiary_is_a_person_with_a_permanent_disability(getContext());
	}

	/**
	 * @param context
	 * @return value of Beneficiary_is_a_person_with_a_permanent_disability
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getBeneficiary_is_a_person_with_a_permanent_disability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Beneficiary_is_a_person_with_a_permanent_disability.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Declartionsettlor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Beneficiary_is_a_person_with_a_permanent_disability
	 * @param beneficiary_is_a_person_with_a_permanent_disability
	 */
	public final void setBeneficiary_is_a_person_with_a_permanent_disability(myfirstmodule.proxies.Enum_Declartionsettlor beneficiary_is_a_person_with_a_permanent_disability)
	{
		setBeneficiary_is_a_person_with_a_permanent_disability(getContext(), beneficiary_is_a_person_with_a_permanent_disability);
	}

	/**
	 * Set value of Beneficiary_is_a_person_with_a_permanent_disability
	 * @param context
	 * @param beneficiary_is_a_person_with_a_permanent_disability
	 */
	public final void setBeneficiary_is_a_person_with_a_permanent_disability(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Declartionsettlor beneficiary_is_a_person_with_a_permanent_disability)
	{
		if (beneficiary_is_a_person_with_a_permanent_disability != null) {
			getMendixObject().setValue(context, MemberNames.Beneficiary_is_a_person_with_a_permanent_disability.toString(), beneficiary_is_a_person_with_a_permanent_disability.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Beneficiary_is_a_person_with_a_permanent_disability.toString(), null);
		}
	}

	/**
	 * Set value of BeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore
	 * @param beneficiaryisasingaporecitizenorpermanentresidentresidinginsingapore
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getBeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore()
	{
		return getBeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore(getContext());
	}

	/**
	 * @param context
	 * @return value of BeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getBeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Declartionsettlor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore
	 * @param beneficiaryisasingaporecitizenorpermanentresidentresidinginsingapore
	 */
	public final void setBeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore(myfirstmodule.proxies.Enum_Declartionsettlor beneficiaryisasingaporecitizenorpermanentresidentresidinginsingapore)
	{
		setBeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore(getContext(), beneficiaryisasingaporecitizenorpermanentresidentresidinginsingapore);
	}

	/**
	 * Set value of BeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore
	 * @param context
	 * @param beneficiaryisasingaporecitizenorpermanentresidentresidinginsingapore
	 */
	public final void setBeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Declartionsettlor beneficiaryisasingaporecitizenorpermanentresidentresidinginsingapore)
	{
		if (beneficiaryisasingaporecitizenorpermanentresidentresidinginsingapore != null) {
			getMendixObject().setValue(context, MemberNames.BeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore.toString(), beneficiaryisasingaporecitizenorpermanentresidentresidinginsingapore.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.BeneficiaryisaSingaporeCitizenorPermanentResidentresidinginSingapore.toString(), null);
		}
	}

	/**
	 * Set value of Trust_assets_are_in_cash_only
	 * @param trust_assets_are_in_cash_only
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getTrust_assets_are_in_cash_only()
	{
		return getTrust_assets_are_in_cash_only(getContext());
	}

	/**
	 * @param context
	 * @return value of Trust_assets_are_in_cash_only
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getTrust_assets_are_in_cash_only(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Trust_assets_are_in_cash_only.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Declartionsettlor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Trust_assets_are_in_cash_only
	 * @param trust_assets_are_in_cash_only
	 */
	public final void setTrust_assets_are_in_cash_only(myfirstmodule.proxies.Enum_Declartionsettlor trust_assets_are_in_cash_only)
	{
		setTrust_assets_are_in_cash_only(getContext(), trust_assets_are_in_cash_only);
	}

	/**
	 * Set value of Trust_assets_are_in_cash_only
	 * @param context
	 * @param trust_assets_are_in_cash_only
	 */
	public final void setTrust_assets_are_in_cash_only(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Declartionsettlor trust_assets_are_in_cash_only)
	{
		if (trust_assets_are_in_cash_only != null) {
			getMendixObject().setValue(context, MemberNames.Trust_assets_are_in_cash_only.toString(), trust_assets_are_in_cash_only.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Trust_assets_are_in_cash_only.toString(), null);
		}
	}

	/**
	 * Set value of Assets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash
	 * @param assets_that_will_be_realized_for_this_trust_upon_death_of_settlor_will_be_only_in_cash
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getAssets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash()
	{
		return getAssets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash(getContext());
	}

	/**
	 * @param context
	 * @return value of Assets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getAssets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Assets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Declartionsettlor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Assets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash
	 * @param assets_that_will_be_realized_for_this_trust_upon_death_of_settlor_will_be_only_in_cash
	 */
	public final void setAssets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash(myfirstmodule.proxies.Enum_Declartionsettlor assets_that_will_be_realized_for_this_trust_upon_death_of_settlor_will_be_only_in_cash)
	{
		setAssets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash(getContext(), assets_that_will_be_realized_for_this_trust_upon_death_of_settlor_will_be_only_in_cash);
	}

	/**
	 * Set value of Assets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash
	 * @param context
	 * @param assets_that_will_be_realized_for_this_trust_upon_death_of_settlor_will_be_only_in_cash
	 */
	public final void setAssets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Declartionsettlor assets_that_will_be_realized_for_this_trust_upon_death_of_settlor_will_be_only_in_cash)
	{
		if (assets_that_will_be_realized_for_this_trust_upon_death_of_settlor_will_be_only_in_cash != null) {
			getMendixObject().setValue(context, MemberNames.Assets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash.toString(), assets_that_will_be_realized_for_this_trust_upon_death_of_settlor_will_be_only_in_cash.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Assets_that_will_be_realized_for_this_trust_upon_death_of_Settlor_will_be_only_in_cash.toString(), null);
		}
	}

	/**
	 * Set value of The_initial_capital_to_setup_the_trust_account_is_atleast_5000
	 * @param the_initial_capital_to_setup_the_trust_account_is_atleast_5000
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getThe_initial_capital_to_setup_the_trust_account_is_atleast_5000()
	{
		return getThe_initial_capital_to_setup_the_trust_account_is_atleast_5000(getContext());
	}

	/**
	 * @param context
	 * @return value of The_initial_capital_to_setup_the_trust_account_is_atleast_5000
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getThe_initial_capital_to_setup_the_trust_account_is_atleast_5000(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.The_initial_capital_to_setup_the_trust_account_is_atleast_5000.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Declartionsettlor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of The_initial_capital_to_setup_the_trust_account_is_atleast_5000
	 * @param the_initial_capital_to_setup_the_trust_account_is_atleast_5000
	 */
	public final void setThe_initial_capital_to_setup_the_trust_account_is_atleast_5000(myfirstmodule.proxies.Enum_Declartionsettlor the_initial_capital_to_setup_the_trust_account_is_atleast_5000)
	{
		setThe_initial_capital_to_setup_the_trust_account_is_atleast_5000(getContext(), the_initial_capital_to_setup_the_trust_account_is_atleast_5000);
	}

	/**
	 * Set value of The_initial_capital_to_setup_the_trust_account_is_atleast_5000
	 * @param context
	 * @param the_initial_capital_to_setup_the_trust_account_is_atleast_5000
	 */
	public final void setThe_initial_capital_to_setup_the_trust_account_is_atleast_5000(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Declartionsettlor the_initial_capital_to_setup_the_trust_account_is_atleast_5000)
	{
		if (the_initial_capital_to_setup_the_trust_account_is_atleast_5000 != null) {
			getMendixObject().setValue(context, MemberNames.The_initial_capital_to_setup_the_trust_account_is_atleast_5000.toString(), the_initial_capital_to_setup_the_trust_account_is_atleast_5000.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.The_initial_capital_to_setup_the_trust_account_is_atleast_5000.toString(), null);
		}
	}

	/**
	 * Set value of No_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary
	 * @param no_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_letter_of_intent_or_expenses_approved_by_sntc_in_the_interest_of_the_beneficiary
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getNo_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary()
	{
		return getNo_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary(getContext());
	}

	/**
	 * @param context
	 * @return value of No_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getNo_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.No_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Declartionsettlor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of No_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary
	 * @param no_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_letter_of_intent_or_expenses_approved_by_sntc_in_the_interest_of_the_beneficiary
	 */
	public final void setNo_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary(myfirstmodule.proxies.Enum_Declartionsettlor no_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_letter_of_intent_or_expenses_approved_by_sntc_in_the_interest_of_the_beneficiary)
	{
		setNo_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary(getContext(), no_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_letter_of_intent_or_expenses_approved_by_sntc_in_the_interest_of_the_beneficiary);
	}

	/**
	 * Set value of No_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary
	 * @param context
	 * @param no_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_letter_of_intent_or_expenses_approved_by_sntc_in_the_interest_of_the_beneficiary
	 */
	public final void setNo_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Declartionsettlor no_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_letter_of_intent_or_expenses_approved_by_sntc_in_the_interest_of_the_beneficiary)
	{
		if (no_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_letter_of_intent_or_expenses_approved_by_sntc_in_the_interest_of_the_beneficiary != null) {
			getMendixObject().setValue(context, MemberNames.No_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary.toString(), no_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_letter_of_intent_or_expenses_approved_by_sntc_in_the_interest_of_the_beneficiary.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.No_payment_will_be_made_to_thirdparties_from_the_trust_account_other_than_those_statedin_the_Letter_of_Intent_or_expenses_approved_by_SNTC_in_the_interest_of_the_Beneficiary.toString(), null);
		}
	}

	/**
	 * Set value of Settlor_is_not_an_undischarged_bankrupt
	 * @param settlor_is_not_an_undischarged_bankrupt
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getSettlor_is_not_an_undischarged_bankrupt()
	{
		return getSettlor_is_not_an_undischarged_bankrupt(getContext());
	}

	/**
	 * @param context
	 * @return value of Settlor_is_not_an_undischarged_bankrupt
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getSettlor_is_not_an_undischarged_bankrupt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Settlor_is_not_an_undischarged_bankrupt.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Declartionsettlor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Settlor_is_not_an_undischarged_bankrupt
	 * @param settlor_is_not_an_undischarged_bankrupt
	 */
	public final void setSettlor_is_not_an_undischarged_bankrupt(myfirstmodule.proxies.Enum_Declartionsettlor settlor_is_not_an_undischarged_bankrupt)
	{
		setSettlor_is_not_an_undischarged_bankrupt(getContext(), settlor_is_not_an_undischarged_bankrupt);
	}

	/**
	 * Set value of Settlor_is_not_an_undischarged_bankrupt
	 * @param context
	 * @param settlor_is_not_an_undischarged_bankrupt
	 */
	public final void setSettlor_is_not_an_undischarged_bankrupt(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Declartionsettlor settlor_is_not_an_undischarged_bankrupt)
	{
		if (settlor_is_not_an_undischarged_bankrupt != null) {
			getMendixObject().setValue(context, MemberNames.Settlor_is_not_an_undischarged_bankrupt.toString(), settlor_is_not_an_undischarged_bankrupt.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Settlor_is_not_an_undischarged_bankrupt.toString(), null);
		}
	}

	/**
	 * Set value of Settlor_is_of_sound_mind
	 * @param settlor_is_of_sound_mind
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getSettlor_is_of_sound_mind()
	{
		return getSettlor_is_of_sound_mind(getContext());
	}

	/**
	 * @param context
	 * @return value of Settlor_is_of_sound_mind
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getSettlor_is_of_sound_mind(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Settlor_is_of_sound_mind.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Declartionsettlor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Settlor_is_of_sound_mind
	 * @param settlor_is_of_sound_mind
	 */
	public final void setSettlor_is_of_sound_mind(myfirstmodule.proxies.Enum_Declartionsettlor settlor_is_of_sound_mind)
	{
		setSettlor_is_of_sound_mind(getContext(), settlor_is_of_sound_mind);
	}

	/**
	 * Set value of Settlor_is_of_sound_mind
	 * @param context
	 * @param settlor_is_of_sound_mind
	 */
	public final void setSettlor_is_of_sound_mind(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Declartionsettlor settlor_is_of_sound_mind)
	{
		if (settlor_is_of_sound_mind != null) {
			getMendixObject().setValue(context, MemberNames.Settlor_is_of_sound_mind.toString(), settlor_is_of_sound_mind.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Settlor_is_of_sound_mind.toString(), null);
		}
	}

	/**
	 * Set value of The_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will
	 * @param the_public_trustee_is_not_appointed_as_executor_of_settlors_will
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getThe_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will()
	{
		return getThe_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will(getContext());
	}

	/**
	 * @param context
	 * @return value of The_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will
	 */
	public final myfirstmodule.proxies.Enum_Declartionsettlor getThe_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.The_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Declartionsettlor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of The_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will
	 * @param the_public_trustee_is_not_appointed_as_executor_of_settlors_will
	 */
	public final void setThe_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will(myfirstmodule.proxies.Enum_Declartionsettlor the_public_trustee_is_not_appointed_as_executor_of_settlors_will)
	{
		setThe_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will(getContext(), the_public_trustee_is_not_appointed_as_executor_of_settlors_will);
	}

	/**
	 * Set value of The_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will
	 * @param context
	 * @param the_public_trustee_is_not_appointed_as_executor_of_settlors_will
	 */
	public final void setThe_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Declartionsettlor the_public_trustee_is_not_appointed_as_executor_of_settlors_will)
	{
		if (the_public_trustee_is_not_appointed_as_executor_of_settlors_will != null) {
			getMendixObject().setValue(context, MemberNames.The_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will.toString(), the_public_trustee_is_not_appointed_as_executor_of_settlors_will.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.The_Public_Trustee_is_not_appointed_as_Executor_of_Settlors_Will.toString(), null);
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return declarationSettlorMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.DeclarationSettlor that = (myfirstmodule.proxies.DeclarationSettlor) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
