// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class DS_Review_and_Submit_Overview_TemplateGrid extends system.proxies.Paging
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.DS_Review_and_Submit_Overview_TemplateGrid";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		User_Name("User_Name"),
		Revert_Confirmation("Revert_Confirmation"),
		Reason("Reason"),
		Duplicate("Duplicate"),
		Date_and_Time("Date_and_Time"),
		PageNumber("PageNumber"),
		IsSortable("IsSortable"),
		SortAttribute("SortAttribute"),
		SortAscending("SortAscending"),
		HasMoreData("HasMoreData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DS_Review_and_Submit_Overview_TemplateGrid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DS_Review_and_Submit_Overview_TemplateGrid(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dS_Review_and_Submit_Overview_TemplateGridMendixObject)
	{
		super(context, dS_Review_and_Submit_Overview_TemplateGridMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, dS_Review_and_Submit_Overview_TemplateGridMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'DS_Review_and_Submit_Overview_TemplateGrid.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid(context, mendixObject);
	}

	public static myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid.initialize(context, mendixObject);
	}

	/**
	 * @return value of User_Name
	 */
	public final java.lang.String getUser_Name()
	{
		return getUser_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Name
	 */
	public final java.lang.String getUser_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User_Name.toString());
	}

	/**
	 * Set value of User_Name
	 * @param user_name
	 */
	public final void setUser_Name(java.lang.String user_name)
	{
		setUser_Name(getContext(), user_name);
	}

	/**
	 * Set value of User_Name
	 * @param context
	 * @param user_name
	 */
	public final void setUser_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user_name)
	{
		getMendixObject().setValue(context, MemberNames.User_Name.toString(), user_name);
	}

	/**
	 * Set value of Revert_Confirmation
	 * @param revert_confirmation
	 */
	public final myfirstmodule.proxies.Return_Confirmation getRevert_Confirmation()
	{
		return getRevert_Confirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of Revert_Confirmation
	 */
	public final myfirstmodule.proxies.Return_Confirmation getRevert_Confirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Revert_Confirmation.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Return_Confirmation.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Revert_Confirmation
	 * @param revert_confirmation
	 */
	public final void setRevert_Confirmation(myfirstmodule.proxies.Return_Confirmation revert_confirmation)
	{
		setRevert_Confirmation(getContext(), revert_confirmation);
	}

	/**
	 * Set value of Revert_Confirmation
	 * @param context
	 * @param revert_confirmation
	 */
	public final void setRevert_Confirmation(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Return_Confirmation revert_confirmation)
	{
		if (revert_confirmation != null) {
			getMendixObject().setValue(context, MemberNames.Revert_Confirmation.toString(), revert_confirmation.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Revert_Confirmation.toString(), null);
		}
	}

	/**
	 * @return value of Reason
	 */
	public final java.lang.String getReason()
	{
		return getReason(getContext());
	}

	/**
	 * @param context
	 * @return value of Reason
	 */
	public final java.lang.String getReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reason.toString());
	}

	/**
	 * Set value of Reason
	 * @param reason
	 */
	public final void setReason(java.lang.String reason)
	{
		setReason(getContext(), reason);
	}

	/**
	 * Set value of Reason
	 * @param context
	 * @param reason
	 */
	public final void setReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reason)
	{
		getMendixObject().setValue(context, MemberNames.Reason.toString(), reason);
	}

	/**
	 * @return value of Duplicate
	 */
	public final java.lang.String getDuplicate()
	{
		return getDuplicate(getContext());
	}

	/**
	 * @param context
	 * @return value of Duplicate
	 */
	public final java.lang.String getDuplicate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Duplicate.toString());
	}

	/**
	 * Set value of Duplicate
	 * @param duplicate
	 */
	public final void setDuplicate(java.lang.String duplicate)
	{
		setDuplicate(getContext(), duplicate);
	}

	/**
	 * Set value of Duplicate
	 * @param context
	 * @param duplicate
	 */
	public final void setDuplicate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String duplicate)
	{
		getMendixObject().setValue(context, MemberNames.Duplicate.toString(), duplicate);
	}

	/**
	 * @return value of Date_and_Time
	 */
	public final java.util.Date getDate_and_Time()
	{
		return getDate_and_Time(getContext());
	}

	/**
	 * @param context
	 * @return value of Date_and_Time
	 */
	public final java.util.Date getDate_and_Time(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date_and_Time.toString());
	}

	/**
	 * Set value of Date_and_Time
	 * @param date_and_time
	 */
	public final void setDate_and_Time(java.util.Date date_and_time)
	{
		setDate_and_Time(getContext(), date_and_time);
	}

	/**
	 * Set value of Date_and_Time
	 * @param context
	 * @param date_and_time
	 */
	public final void setDate_and_Time(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date_and_time)
	{
		getMendixObject().setValue(context, MemberNames.Date_and_Time.toString(), date_and_time);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid that = (myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
