// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum DynamicForm_Status
{
	Approved(new java.lang.String[][] { new java.lang.String[] { "en_US", "Approved" } }),
	Rejected(new java.lang.String[][] { new java.lang.String[] { "en_US", "Rejected" } }),
	Form_submitted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Form submitted" } }),
	Case_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Case manager accepted" } }),
	Senior_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Senior manager accepted" } }),
	Senior_case_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Senior case manager accepted" } }),
	Trust_admin_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Trust admin accepted" } }),
	General_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "General manager accepted" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private DynamicForm_Status(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
