// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Enum_Religion
{
	Buddhism(new java.lang.String[][] { new java.lang.String[] { "en_US", "Buddhism" }, new java.lang.String[] { "zh_SG", "佛教" } }),
	Christianity(new java.lang.String[][] { new java.lang.String[] { "en_US", "Christianity" }, new java.lang.String[] { "zh_SG", "基督教" } }),
	Hinduism(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hinduism" }, new java.lang.String[] { "zh_SG", "印度教" } }),
	Islam(new java.lang.String[][] { new java.lang.String[] { "en_US", "Islam" }, new java.lang.String[] { "zh_SG", "回教" } }),
	Others(new java.lang.String[][] { new java.lang.String[] { "en_US", "Others" }, new java.lang.String[] { "zh_SG", "其他" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_Religion(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
