// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Enum_Marital
{
	Single(new java.lang.String[][] { new java.lang.String[] { "en_US", "Single" }, new java.lang.String[] { "zh_SG", "单身" } }),
	Married(new java.lang.String[][] { new java.lang.String[] { "en_US", "Married" }, new java.lang.String[] { "zh_SG", "已婚" } }),
	Seperated(new java.lang.String[][] { new java.lang.String[] { "en_US", "Seperated" }, new java.lang.String[] { "zh_SG", "分居" } }),
	Divorced(new java.lang.String[][] { new java.lang.String[] { "en_US", "Divorced" }, new java.lang.String[] { "zh_SG", "离异" } }),
	Widowed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Widowed" }, new java.lang.String[] { "zh_SG", "丧偶" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_Marital(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
