// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Form_Status
{
	forwarded_to_CaseManager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Forwarded to Case Manager" } }),
	forwarded_to_SeniorCaseManager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Forwarded to Senior Case Manager" } }),
	forwarded_to_trustAdmin(new java.lang.String[][] { new java.lang.String[] { "en_US", "Forwarded to Trust Admin" } }),
	Approved(new java.lang.String[][] { new java.lang.String[] { "en_US", "Approved" } }),
	Rejected(new java.lang.String[][] { new java.lang.String[] { "en_US", "Rejected" } }),
	forwarded_to_seniorManager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Forwarded to Senior Manager" } }),
	forwarded_to_GeneralManager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Forwarded to General Manager" } }),
	Returned_to_SNTC_User(new java.lang.String[][] { new java.lang.String[] { "en_US", "Returned to SNTC User" } }),
	Returned_to_Case_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Returned to Case Manager" } }),
	Returned_to_Senior_Case_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Returned to Senior Case Manager" } }),
	Returned_to_Trust_Admin(new java.lang.String[][] { new java.lang.String[] { "en_US", "Returned to Trust Admin" } }),
	Returned_to_Senior_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Returned to Senior Manager" } }),
	Form_submited(new java.lang.String[][] { new java.lang.String[] { "en_US", "Form submited" } }),
	Case_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Case manager accepted" } }),
	Senior_case_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Senior case manager accepted" } }),
	senior_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "senior manager accepted" } }),
	Trust_admin_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Trust admin accepted" } }),
	General_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "General manager accepted" } }),
	Returned(new java.lang.String[][] { new java.lang.String[] { "en_US", "Returned" } }),
	Save_as_Draft(new java.lang.String[][] { new java.lang.String[] { "en_US", "Save as Draft" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Form_Status(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
