// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum History_Enumeration
{
	Form_submitted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Form submitted" } }),
	SNTC_forwarded(new java.lang.String[][] { new java.lang.String[] { "en_US", "SNTC forwarded" } }),
	Case_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Case manager accepted" } }),
	case_manager_forwarded(new java.lang.String[][] { new java.lang.String[] { "en_US", "case manager forwarded" } }),
	Case_manager_returned(new java.lang.String[][] { new java.lang.String[] { "en_US", "Case manager returned" } }),
	Senior_case_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Senior case manager accepted" } }),
	senior_case_manager_forwaded(new java.lang.String[][] { new java.lang.String[] { "en_US", "senior case manager forwarded" } }),
	Senior_case_manager_returned(new java.lang.String[][] { new java.lang.String[] { "en_US", "Senior case manager returned" } }),
	Trust_admin_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Trust admin accepted" } }),
	trust_admin_forwarded(new java.lang.String[][] { new java.lang.String[] { "en_US", "trust admin forwarded" } }),
	Trust_admin_returned(new java.lang.String[][] { new java.lang.String[] { "en_US", "Trust admin returned" } }),
	Senior_manager_accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Senior manager accepted" } }),
	senior_manager_forwaded(new java.lang.String[][] { new java.lang.String[] { "en_US", "senior manager forwaded" } }),
	senior_manager_returned(new java.lang.String[][] { new java.lang.String[] { "en_US", "Senior manager returned" } }),
	Accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Accepted" } }),
	Rejected(new java.lang.String[][] { new java.lang.String[] { "en_US", "Rejected" } }),
	General_manager_returned(new java.lang.String[][] { new java.lang.String[] { "en_US", "General manager returned" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private History_Enumeration(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
