// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class History
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject historyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.History";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		Sender("Sender"),
		Receiver("Receiver"),
		sent_date_time("sent_date_time"),
		Received_Date_time("Received_Date_time"),
		TimeTaken("TimeTaken"),
		DeadLine("DeadLine"),
		SLA_Met("SLA_Met"),
		Status("Status"),
		History_Applicant("MyFirstModule.History_Applicant"),
		History_Account("MyFirstModule.History_Account"),
		History_FileDocument_2("MyFirstModule.History_FileDocument_2");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public History(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected History(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject historyMendixObject)
	{
		if (historyMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, historyMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.historyMendixObject = historyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'History.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.History initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.History.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.History initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.History(context, mendixObject);
	}

	public static myfirstmodule.proxies.History load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.History.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.History> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.History.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Sender
	 */
	public final java.lang.String getSender()
	{
		return getSender(getContext());
	}

	/**
	 * @param context
	 * @return value of Sender
	 */
	public final java.lang.String getSender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sender.toString());
	}

	/**
	 * Set value of Sender
	 * @param sender
	 */
	public final void setSender(java.lang.String sender)
	{
		setSender(getContext(), sender);
	}

	/**
	 * Set value of Sender
	 * @param context
	 * @param sender
	 */
	public final void setSender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sender)
	{
		getMendixObject().setValue(context, MemberNames.Sender.toString(), sender);
	}

	/**
	 * @return value of Receiver
	 */
	public final java.lang.String getReceiver()
	{
		return getReceiver(getContext());
	}

	/**
	 * @param context
	 * @return value of Receiver
	 */
	public final java.lang.String getReceiver(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Receiver.toString());
	}

	/**
	 * Set value of Receiver
	 * @param receiver
	 */
	public final void setReceiver(java.lang.String receiver)
	{
		setReceiver(getContext(), receiver);
	}

	/**
	 * Set value of Receiver
	 * @param context
	 * @param receiver
	 */
	public final void setReceiver(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String receiver)
	{
		getMendixObject().setValue(context, MemberNames.Receiver.toString(), receiver);
	}

	/**
	 * @return value of sent_date_time
	 */
	public final java.util.Date getsent_date_time()
	{
		return getsent_date_time(getContext());
	}

	/**
	 * @param context
	 * @return value of sent_date_time
	 */
	public final java.util.Date getsent_date_time(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.sent_date_time.toString());
	}

	/**
	 * Set value of sent_date_time
	 * @param sent_date_time
	 */
	public final void setsent_date_time(java.util.Date sent_date_time)
	{
		setsent_date_time(getContext(), sent_date_time);
	}

	/**
	 * Set value of sent_date_time
	 * @param context
	 * @param sent_date_time
	 */
	public final void setsent_date_time(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date sent_date_time)
	{
		getMendixObject().setValue(context, MemberNames.sent_date_time.toString(), sent_date_time);
	}

	/**
	 * @return value of Received_Date_time
	 */
	public final java.util.Date getReceived_Date_time()
	{
		return getReceived_Date_time(getContext());
	}

	/**
	 * @param context
	 * @return value of Received_Date_time
	 */
	public final java.util.Date getReceived_Date_time(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Received_Date_time.toString());
	}

	/**
	 * Set value of Received_Date_time
	 * @param received_date_time
	 */
	public final void setReceived_Date_time(java.util.Date received_date_time)
	{
		setReceived_Date_time(getContext(), received_date_time);
	}

	/**
	 * Set value of Received_Date_time
	 * @param context
	 * @param received_date_time
	 */
	public final void setReceived_Date_time(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date received_date_time)
	{
		getMendixObject().setValue(context, MemberNames.Received_Date_time.toString(), received_date_time);
	}

	/**
	 * @return value of TimeTaken
	 */
	public final java.math.BigDecimal getTimeTaken()
	{
		return getTimeTaken(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeTaken
	 */
	public final java.math.BigDecimal getTimeTaken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TimeTaken.toString());
	}

	/**
	 * Set value of TimeTaken
	 * @param timetaken
	 */
	public final void setTimeTaken(java.math.BigDecimal timetaken)
	{
		setTimeTaken(getContext(), timetaken);
	}

	/**
	 * Set value of TimeTaken
	 * @param context
	 * @param timetaken
	 */
	public final void setTimeTaken(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal timetaken)
	{
		getMendixObject().setValue(context, MemberNames.TimeTaken.toString(), timetaken);
	}

	/**
	 * @return value of DeadLine
	 */
	public final java.util.Date getDeadLine()
	{
		return getDeadLine(getContext());
	}

	/**
	 * @param context
	 * @return value of DeadLine
	 */
	public final java.util.Date getDeadLine(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DeadLine.toString());
	}

	/**
	 * Set value of DeadLine
	 * @param deadline
	 */
	public final void setDeadLine(java.util.Date deadline)
	{
		setDeadLine(getContext(), deadline);
	}

	/**
	 * Set value of DeadLine
	 * @param context
	 * @param deadline
	 */
	public final void setDeadLine(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date deadline)
	{
		getMendixObject().setValue(context, MemberNames.DeadLine.toString(), deadline);
	}

	/**
	 * Set value of SLA_Met
	 * @param sla_met
	 */
	public final myfirstmodule.proxies.SLAMet getSLA_Met()
	{
		return getSLA_Met(getContext());
	}

	/**
	 * @param context
	 * @return value of SLA_Met
	 */
	public final myfirstmodule.proxies.SLAMet getSLA_Met(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SLA_Met.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.SLAMet.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SLA_Met
	 * @param sla_met
	 */
	public final void setSLA_Met(myfirstmodule.proxies.SLAMet sla_met)
	{
		setSLA_Met(getContext(), sla_met);
	}

	/**
	 * Set value of SLA_Met
	 * @param context
	 * @param sla_met
	 */
	public final void setSLA_Met(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.SLAMet sla_met)
	{
		if (sla_met != null) {
			getMendixObject().setValue(context, MemberNames.SLA_Met.toString(), sla_met.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SLA_Met.toString(), null);
		}
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final myfirstmodule.proxies.History_Enumeration getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final myfirstmodule.proxies.History_Enumeration getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.History_Enumeration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(myfirstmodule.proxies.History_Enumeration status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.History_Enumeration status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of History_Applicant
	 */
	public final myfirstmodule.proxies.Applicant getHistory_Applicant() throws com.mendix.core.CoreException
	{
		return getHistory_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of History_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant getHistory_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.History_Applicant.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of History_Applicant
	 * @param history_applicant
	 */
	public final void setHistory_Applicant(myfirstmodule.proxies.Applicant history_applicant)
	{
		setHistory_Applicant(getContext(), history_applicant);
	}

	/**
	 * Set value of History_Applicant
	 * @param context
	 * @param history_applicant
	 */
	public final void setHistory_Applicant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant history_applicant)
	{
		if (history_applicant == null) {
			getMendixObject().setValue(context, MemberNames.History_Applicant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.History_Applicant.toString(), history_applicant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of History_Account
	 */
	public final administration.proxies.Account getHistory_Account() throws com.mendix.core.CoreException
	{
		return getHistory_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of History_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getHistory_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.History_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of History_Account
	 * @param history_account
	 */
	public final void setHistory_Account(administration.proxies.Account history_account)
	{
		setHistory_Account(getContext(), history_account);
	}

	/**
	 * Set value of History_Account
	 * @param context
	 * @param history_account
	 */
	public final void setHistory_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account history_account)
	{
		if (history_account == null) {
			getMendixObject().setValue(context, MemberNames.History_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.History_Account.toString(), history_account.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of History_FileDocument_2
	 */
	public final system.proxies.FileDocument getHistory_FileDocument_2() throws com.mendix.core.CoreException
	{
		return getHistory_FileDocument_2(getContext());
	}

	/**
	 * @param context
	 * @return value of History_FileDocument_2
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.FileDocument getHistory_FileDocument_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.FileDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.History_FileDocument_2.toString());
		if (identifier != null) {
			result = system.proxies.FileDocument.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of History_FileDocument_2
	 * @param history_filedocument_2
	 */
	public final void setHistory_FileDocument_2(system.proxies.FileDocument history_filedocument_2)
	{
		setHistory_FileDocument_2(getContext(), history_filedocument_2);
	}

	/**
	 * Set value of History_FileDocument_2
	 * @param context
	 * @param history_filedocument_2
	 */
	public final void setHistory_FileDocument_2(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.FileDocument history_filedocument_2)
	{
		if (history_filedocument_2 == null) {
			getMendixObject().setValue(context, MemberNames.History_FileDocument_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.History_FileDocument_2.toString(), history_filedocument_2.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return historyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.History that = (myfirstmodule.proxies.History) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
