// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Life_Beneficiary
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject life_BeneficiaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Life_Beneficiary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Citizeinship_or_Nationality("Citizeinship_or_Nationality"),
		Gender("Gender"),
		NRIC_or_Birth_Certificate_No("NRIC_or_Birth_Certificate_No"),
		Date_Of_Birth("Date_Of_Birth"),
		Marital_Status("Marital_Status"),
		Race("Race"),
		Religion("Religion"),
		Language_Spoken("Language_Spoken"),
		Description_of_Permanent_Disability("Description_of_Permanent_Disability"),
		Address("Address"),
		Home_Telephone("Home_Telephone"),
		Mobile("Mobile"),
		Email("Email"),
		Current_VWO_or_School_or_Employment_Centre("Current_VWO_or_School_or_Employment_Centre"),
		Current_Care_Arrangement("Current_Care_Arrangement"),
		Others("Others"),
		Life_Beneficiary_Settlor("MyFirstModule.Life_Beneficiary_Settlor"),
		Life_Beneficiary_Settlors_Spouse("MyFirstModule.Life_Beneficiary_Settlors_Spouse"),
		Life_Beneficiary_Others_Designated_Person("MyFirstModule.Life_Beneficiary_Others_Designated_Person"),
		Life_Beneficiary_Applicant("MyFirstModule.Life_Beneficiary_Applicant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Life_Beneficiary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Life_Beneficiary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject life_BeneficiaryMendixObject)
	{
		if (life_BeneficiaryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, life_BeneficiaryMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.life_BeneficiaryMendixObject = life_BeneficiaryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Life_Beneficiary.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Life_Beneficiary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Life_Beneficiary.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Life_Beneficiary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Life_Beneficiary(context, mendixObject);
	}

	public static myfirstmodule.proxies.Life_Beneficiary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Life_Beneficiary.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Life_Beneficiary> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Life_Beneficiary.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of Citizeinship_or_Nationality
	 * @param citizeinship_or_nationality
	 */
	public final myfirstmodule.proxies.Enum_Citizen getCitizeinship_or_Nationality()
	{
		return getCitizeinship_or_Nationality(getContext());
	}

	/**
	 * @param context
	 * @return value of Citizeinship_or_Nationality
	 */
	public final myfirstmodule.proxies.Enum_Citizen getCitizeinship_or_Nationality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Citizeinship_or_Nationality.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Citizen.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Citizeinship_or_Nationality
	 * @param citizeinship_or_nationality
	 */
	public final void setCitizeinship_or_Nationality(myfirstmodule.proxies.Enum_Citizen citizeinship_or_nationality)
	{
		setCitizeinship_or_Nationality(getContext(), citizeinship_or_nationality);
	}

	/**
	 * Set value of Citizeinship_or_Nationality
	 * @param context
	 * @param citizeinship_or_nationality
	 */
	public final void setCitizeinship_or_Nationality(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Citizen citizeinship_or_nationality)
	{
		if (citizeinship_or_nationality != null) {
			getMendixObject().setValue(context, MemberNames.Citizeinship_or_Nationality.toString(), citizeinship_or_nationality.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Citizeinship_or_Nationality.toString(), null);
		}
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final myfirstmodule.proxies.Enum_Gender getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final myfirstmodule.proxies.Enum_Gender getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Gender.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Gender.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(myfirstmodule.proxies.Enum_Gender gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Gender gender)
	{
		if (gender != null) {
			getMendixObject().setValue(context, MemberNames.Gender.toString(), gender.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Gender.toString(), null);
		}
	}

	/**
	 * @return value of NRIC_or_Birth_Certificate_No
	 */
	public final java.lang.Long getNRIC_or_Birth_Certificate_No()
	{
		return getNRIC_or_Birth_Certificate_No(getContext());
	}

	/**
	 * @param context
	 * @return value of NRIC_or_Birth_Certificate_No
	 */
	public final java.lang.Long getNRIC_or_Birth_Certificate_No(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.NRIC_or_Birth_Certificate_No.toString());
	}

	/**
	 * Set value of NRIC_or_Birth_Certificate_No
	 * @param nric_or_birth_certificate_no
	 */
	public final void setNRIC_or_Birth_Certificate_No(java.lang.Long nric_or_birth_certificate_no)
	{
		setNRIC_or_Birth_Certificate_No(getContext(), nric_or_birth_certificate_no);
	}

	/**
	 * Set value of NRIC_or_Birth_Certificate_No
	 * @param context
	 * @param nric_or_birth_certificate_no
	 */
	public final void setNRIC_or_Birth_Certificate_No(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long nric_or_birth_certificate_no)
	{
		getMendixObject().setValue(context, MemberNames.NRIC_or_Birth_Certificate_No.toString(), nric_or_birth_certificate_no);
	}

	/**
	 * @return value of Date_Of_Birth
	 */
	public final java.util.Date getDate_Of_Birth()
	{
		return getDate_Of_Birth(getContext());
	}

	/**
	 * @param context
	 * @return value of Date_Of_Birth
	 */
	public final java.util.Date getDate_Of_Birth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date_Of_Birth.toString());
	}

	/**
	 * Set value of Date_Of_Birth
	 * @param date_of_birth
	 */
	public final void setDate_Of_Birth(java.util.Date date_of_birth)
	{
		setDate_Of_Birth(getContext(), date_of_birth);
	}

	/**
	 * Set value of Date_Of_Birth
	 * @param context
	 * @param date_of_birth
	 */
	public final void setDate_Of_Birth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date_of_birth)
	{
		getMendixObject().setValue(context, MemberNames.Date_Of_Birth.toString(), date_of_birth);
	}

	/**
	 * Set value of Marital_Status
	 * @param marital_status
	 */
	public final myfirstmodule.proxies.Enum_Marital getMarital_Status()
	{
		return getMarital_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of Marital_Status
	 */
	public final myfirstmodule.proxies.Enum_Marital getMarital_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Marital_Status.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Marital.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Marital_Status
	 * @param marital_status
	 */
	public final void setMarital_Status(myfirstmodule.proxies.Enum_Marital marital_status)
	{
		setMarital_Status(getContext(), marital_status);
	}

	/**
	 * Set value of Marital_Status
	 * @param context
	 * @param marital_status
	 */
	public final void setMarital_Status(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Marital marital_status)
	{
		if (marital_status != null) {
			getMendixObject().setValue(context, MemberNames.Marital_Status.toString(), marital_status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Marital_Status.toString(), null);
		}
	}

	/**
	 * Set value of Race
	 * @param race
	 */
	public final myfirstmodule.proxies.Enum_Race getRace()
	{
		return getRace(getContext());
	}

	/**
	 * @param context
	 * @return value of Race
	 */
	public final myfirstmodule.proxies.Enum_Race getRace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Race.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Race.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Race
	 * @param race
	 */
	public final void setRace(myfirstmodule.proxies.Enum_Race race)
	{
		setRace(getContext(), race);
	}

	/**
	 * Set value of Race
	 * @param context
	 * @param race
	 */
	public final void setRace(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Race race)
	{
		if (race != null) {
			getMendixObject().setValue(context, MemberNames.Race.toString(), race.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Race.toString(), null);
		}
	}

	/**
	 * Set value of Religion
	 * @param religion
	 */
	public final myfirstmodule.proxies.Enum_Religion getReligion()
	{
		return getReligion(getContext());
	}

	/**
	 * @param context
	 * @return value of Religion
	 */
	public final myfirstmodule.proxies.Enum_Religion getReligion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Religion.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Religion.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Religion
	 * @param religion
	 */
	public final void setReligion(myfirstmodule.proxies.Enum_Religion religion)
	{
		setReligion(getContext(), religion);
	}

	/**
	 * Set value of Religion
	 * @param context
	 * @param religion
	 */
	public final void setReligion(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Religion religion)
	{
		if (religion != null) {
			getMendixObject().setValue(context, MemberNames.Religion.toString(), religion.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Religion.toString(), null);
		}
	}

	/**
	 * Set value of Language_Spoken
	 * @param language_spoken
	 */
	public final myfirstmodule.proxies.Enum_Language getLanguage_Spoken()
	{
		return getLanguage_Spoken(getContext());
	}

	/**
	 * @param context
	 * @return value of Language_Spoken
	 */
	public final myfirstmodule.proxies.Enum_Language getLanguage_Spoken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Language_Spoken.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_Language.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Language_Spoken
	 * @param language_spoken
	 */
	public final void setLanguage_Spoken(myfirstmodule.proxies.Enum_Language language_spoken)
	{
		setLanguage_Spoken(getContext(), language_spoken);
	}

	/**
	 * Set value of Language_Spoken
	 * @param context
	 * @param language_spoken
	 */
	public final void setLanguage_Spoken(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_Language language_spoken)
	{
		if (language_spoken != null) {
			getMendixObject().setValue(context, MemberNames.Language_Spoken.toString(), language_spoken.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Language_Spoken.toString(), null);
		}
	}

	/**
	 * @return value of Description_of_Permanent_Disability
	 */
	public final java.lang.String getDescription_of_Permanent_Disability()
	{
		return getDescription_of_Permanent_Disability(getContext());
	}

	/**
	 * @param context
	 * @return value of Description_of_Permanent_Disability
	 */
	public final java.lang.String getDescription_of_Permanent_Disability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description_of_Permanent_Disability.toString());
	}

	/**
	 * Set value of Description_of_Permanent_Disability
	 * @param description_of_permanent_disability
	 */
	public final void setDescription_of_Permanent_Disability(java.lang.String description_of_permanent_disability)
	{
		setDescription_of_Permanent_Disability(getContext(), description_of_permanent_disability);
	}

	/**
	 * Set value of Description_of_Permanent_Disability
	 * @param context
	 * @param description_of_permanent_disability
	 */
	public final void setDescription_of_Permanent_Disability(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description_of_permanent_disability)
	{
		getMendixObject().setValue(context, MemberNames.Description_of_Permanent_Disability.toString(), description_of_permanent_disability);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of Home_Telephone
	 */
	public final java.lang.Long getHome_Telephone()
	{
		return getHome_Telephone(getContext());
	}

	/**
	 * @param context
	 * @return value of Home_Telephone
	 */
	public final java.lang.Long getHome_Telephone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Home_Telephone.toString());
	}

	/**
	 * Set value of Home_Telephone
	 * @param home_telephone
	 */
	public final void setHome_Telephone(java.lang.Long home_telephone)
	{
		setHome_Telephone(getContext(), home_telephone);
	}

	/**
	 * Set value of Home_Telephone
	 * @param context
	 * @param home_telephone
	 */
	public final void setHome_Telephone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long home_telephone)
	{
		getMendixObject().setValue(context, MemberNames.Home_Telephone.toString(), home_telephone);
	}

	/**
	 * @return value of Mobile
	 */
	public final java.lang.Long getMobile()
	{
		return getMobile(getContext());
	}

	/**
	 * @param context
	 * @return value of Mobile
	 */
	public final java.lang.Long getMobile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Mobile.toString());
	}

	/**
	 * Set value of Mobile
	 * @param mobile
	 */
	public final void setMobile(java.lang.Long mobile)
	{
		setMobile(getContext(), mobile);
	}

	/**
	 * Set value of Mobile
	 * @param context
	 * @param mobile
	 */
	public final void setMobile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long mobile)
	{
		getMendixObject().setValue(context, MemberNames.Mobile.toString(), mobile);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Current_VWO_or_School_or_Employment_Centre
	 */
	public final java.lang.String getCurrent_VWO_or_School_or_Employment_Centre()
	{
		return getCurrent_VWO_or_School_or_Employment_Centre(getContext());
	}

	/**
	 * @param context
	 * @return value of Current_VWO_or_School_or_Employment_Centre
	 */
	public final java.lang.String getCurrent_VWO_or_School_or_Employment_Centre(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Current_VWO_or_School_or_Employment_Centre.toString());
	}

	/**
	 * Set value of Current_VWO_or_School_or_Employment_Centre
	 * @param current_vwo_or_school_or_employment_centre
	 */
	public final void setCurrent_VWO_or_School_or_Employment_Centre(java.lang.String current_vwo_or_school_or_employment_centre)
	{
		setCurrent_VWO_or_School_or_Employment_Centre(getContext(), current_vwo_or_school_or_employment_centre);
	}

	/**
	 * Set value of Current_VWO_or_School_or_Employment_Centre
	 * @param context
	 * @param current_vwo_or_school_or_employment_centre
	 */
	public final void setCurrent_VWO_or_School_or_Employment_Centre(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String current_vwo_or_school_or_employment_centre)
	{
		getMendixObject().setValue(context, MemberNames.Current_VWO_or_School_or_Employment_Centre.toString(), current_vwo_or_school_or_employment_centre);
	}

	/**
	 * @return value of Current_Care_Arrangement
	 */
	public final java.lang.String getCurrent_Care_Arrangement()
	{
		return getCurrent_Care_Arrangement(getContext());
	}

	/**
	 * @param context
	 * @return value of Current_Care_Arrangement
	 */
	public final java.lang.String getCurrent_Care_Arrangement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Current_Care_Arrangement.toString());
	}

	/**
	 * Set value of Current_Care_Arrangement
	 * @param current_care_arrangement
	 */
	public final void setCurrent_Care_Arrangement(java.lang.String current_care_arrangement)
	{
		setCurrent_Care_Arrangement(getContext(), current_care_arrangement);
	}

	/**
	 * Set value of Current_Care_Arrangement
	 * @param context
	 * @param current_care_arrangement
	 */
	public final void setCurrent_Care_Arrangement(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String current_care_arrangement)
	{
		getMendixObject().setValue(context, MemberNames.Current_Care_Arrangement.toString(), current_care_arrangement);
	}

	/**
	 * @return value of Others
	 */
	public final java.lang.String getOthers()
	{
		return getOthers(getContext());
	}

	/**
	 * @param context
	 * @return value of Others
	 */
	public final java.lang.String getOthers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Others.toString());
	}

	/**
	 * Set value of Others
	 * @param others
	 */
	public final void setOthers(java.lang.String others)
	{
		setOthers(getContext(), others);
	}

	/**
	 * Set value of Others
	 * @param context
	 * @param others
	 */
	public final void setOthers(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String others)
	{
		getMendixObject().setValue(context, MemberNames.Others.toString(), others);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Life_Beneficiary_Settlor
	 */
	public final myfirstmodule.proxies.Settlor getLife_Beneficiary_Settlor() throws com.mendix.core.CoreException
	{
		return getLife_Beneficiary_Settlor(getContext());
	}

	/**
	 * @param context
	 * @return value of Life_Beneficiary_Settlor
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Settlor getLife_Beneficiary_Settlor(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Settlor result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Life_Beneficiary_Settlor.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Settlor.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Life_Beneficiary_Settlor
	 * @param life_beneficiary_settlor
	 */
	public final void setLife_Beneficiary_Settlor(myfirstmodule.proxies.Settlor life_beneficiary_settlor)
	{
		setLife_Beneficiary_Settlor(getContext(), life_beneficiary_settlor);
	}

	/**
	 * Set value of Life_Beneficiary_Settlor
	 * @param context
	 * @param life_beneficiary_settlor
	 */
	public final void setLife_Beneficiary_Settlor(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Settlor life_beneficiary_settlor)
	{
		if (life_beneficiary_settlor == null) {
			getMendixObject().setValue(context, MemberNames.Life_Beneficiary_Settlor.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Life_Beneficiary_Settlor.toString(), life_beneficiary_settlor.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Life_Beneficiary_Settlors_Spouse
	 */
	public final myfirstmodule.proxies.Settlors_Spouse getLife_Beneficiary_Settlors_Spouse() throws com.mendix.core.CoreException
	{
		return getLife_Beneficiary_Settlors_Spouse(getContext());
	}

	/**
	 * @param context
	 * @return value of Life_Beneficiary_Settlors_Spouse
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Settlors_Spouse getLife_Beneficiary_Settlors_Spouse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Settlors_Spouse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Life_Beneficiary_Settlors_Spouse.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Settlors_Spouse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Life_Beneficiary_Settlors_Spouse
	 * @param life_beneficiary_settlors_spouse
	 */
	public final void setLife_Beneficiary_Settlors_Spouse(myfirstmodule.proxies.Settlors_Spouse life_beneficiary_settlors_spouse)
	{
		setLife_Beneficiary_Settlors_Spouse(getContext(), life_beneficiary_settlors_spouse);
	}

	/**
	 * Set value of Life_Beneficiary_Settlors_Spouse
	 * @param context
	 * @param life_beneficiary_settlors_spouse
	 */
	public final void setLife_Beneficiary_Settlors_Spouse(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Settlors_Spouse life_beneficiary_settlors_spouse)
	{
		if (life_beneficiary_settlors_spouse == null) {
			getMendixObject().setValue(context, MemberNames.Life_Beneficiary_Settlors_Spouse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Life_Beneficiary_Settlors_Spouse.toString(), life_beneficiary_settlors_spouse.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Life_Beneficiary_Others_Designated_Person
	 */
	public final myfirstmodule.proxies.Others_Designated_Person getLife_Beneficiary_Others_Designated_Person() throws com.mendix.core.CoreException
	{
		return getLife_Beneficiary_Others_Designated_Person(getContext());
	}

	/**
	 * @param context
	 * @return value of Life_Beneficiary_Others_Designated_Person
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Others_Designated_Person getLife_Beneficiary_Others_Designated_Person(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Others_Designated_Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Life_Beneficiary_Others_Designated_Person.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Others_Designated_Person.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Life_Beneficiary_Others_Designated_Person
	 * @param life_beneficiary_others_designated_person
	 */
	public final void setLife_Beneficiary_Others_Designated_Person(myfirstmodule.proxies.Others_Designated_Person life_beneficiary_others_designated_person)
	{
		setLife_Beneficiary_Others_Designated_Person(getContext(), life_beneficiary_others_designated_person);
	}

	/**
	 * Set value of Life_Beneficiary_Others_Designated_Person
	 * @param context
	 * @param life_beneficiary_others_designated_person
	 */
	public final void setLife_Beneficiary_Others_Designated_Person(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Others_Designated_Person life_beneficiary_others_designated_person)
	{
		if (life_beneficiary_others_designated_person == null) {
			getMendixObject().setValue(context, MemberNames.Life_Beneficiary_Others_Designated_Person.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Life_Beneficiary_Others_Designated_Person.toString(), life_beneficiary_others_designated_person.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Life_Beneficiary_Applicant
	 */
	public final myfirstmodule.proxies.Applicant getLife_Beneficiary_Applicant() throws com.mendix.core.CoreException
	{
		return getLife_Beneficiary_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of Life_Beneficiary_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant getLife_Beneficiary_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Life_Beneficiary_Applicant.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Life_Beneficiary_Applicant
	 * @param life_beneficiary_applicant
	 */
	public final void setLife_Beneficiary_Applicant(myfirstmodule.proxies.Applicant life_beneficiary_applicant)
	{
		setLife_Beneficiary_Applicant(getContext(), life_beneficiary_applicant);
	}

	/**
	 * Set value of Life_Beneficiary_Applicant
	 * @param context
	 * @param life_beneficiary_applicant
	 */
	public final void setLife_Beneficiary_Applicant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant life_beneficiary_applicant)
	{
		if (life_beneficiary_applicant == null) {
			getMendixObject().setValue(context, MemberNames.Life_Beneficiary_Applicant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Life_Beneficiary_Applicant.toString(), life_beneficiary_applicant.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return life_BeneficiaryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Life_Beneficiary that = (myfirstmodule.proxies.Life_Beneficiary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
