// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class month
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject monthMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.month";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Approved("Approved"),
		Rejected("Rejected"),
		Inprogress("Inprogress"),
		Pending("Pending"),
		jan("jan"),
		Feb("Feb"),
		mar("mar"),
		Apr("Apr"),
		May("May"),
		Jun("Jun"),
		july("july"),
		Aug("Aug"),
		sep("sep"),
		oct("oct"),
		Nov("Nov"),
		Dec("Dec"),
		R_Jan("R_Jan"),
		R_Feb("R_Feb"),
		R_Mar("R_Mar"),
		R_Apr("R_Apr"),
		R_May("R_May"),
		R_Jun("R_Jun"),
		R_Jul("R_Jul"),
		R_Aug("R_Aug"),
		R_Sep("R_Sep"),
		R_oct("R_oct"),
		R_Nov("R_Nov"),
		R_Dec("R_Dec"),
		In_Jan("In_Jan"),
		In_Feb("In_Feb"),
		In_Mar("In_Mar"),
		In_Apr("In_Apr"),
		In_May("In_May"),
		In_Jun("In_Jun"),
		In_Jul("In_Jul"),
		In_Aug("In_Aug"),
		In_Sep("In_Sep"),
		In_Nov("In_Nov"),
		In_Dec("In_Dec"),
		P_Jan("P_Jan"),
		P_Feb("P_Feb"),
		P_Mar("P_Mar"),
		P_Apr("P_Apr"),
		P_May("P_May"),
		P_Jun("P_Jun"),
		P_Jul("P_Jul"),
		P_Aug("P_Aug"),
		P_Sep("P_Sep"),
		P_Oct("P_Oct"),
		P_Nov("P_Nov"),
		P_Dec("P_Dec"),
		In_Oct("In_Oct");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public month(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected month(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject monthMendixObject)
	{
		if (monthMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, monthMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.monthMendixObject = monthMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'month.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.month initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.month.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.month initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.month(context, mendixObject);
	}

	public static myfirstmodule.proxies.month load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.month.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.month> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.month.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Approved
	 */
	public final java.lang.Integer getApproved()
	{
		return getApproved(getContext());
	}

	/**
	 * @param context
	 * @return value of Approved
	 */
	public final java.lang.Integer getApproved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Approved.toString());
	}

	/**
	 * Set value of Approved
	 * @param approved
	 */
	public final void setApproved(java.lang.Integer approved)
	{
		setApproved(getContext(), approved);
	}

	/**
	 * Set value of Approved
	 * @param context
	 * @param approved
	 */
	public final void setApproved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer approved)
	{
		getMendixObject().setValue(context, MemberNames.Approved.toString(), approved);
	}

	/**
	 * @return value of Rejected
	 */
	public final java.lang.Integer getRejected()
	{
		return getRejected(getContext());
	}

	/**
	 * @param context
	 * @return value of Rejected
	 */
	public final java.lang.Integer getRejected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rejected.toString());
	}

	/**
	 * Set value of Rejected
	 * @param rejected
	 */
	public final void setRejected(java.lang.Integer rejected)
	{
		setRejected(getContext(), rejected);
	}

	/**
	 * Set value of Rejected
	 * @param context
	 * @param rejected
	 */
	public final void setRejected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rejected)
	{
		getMendixObject().setValue(context, MemberNames.Rejected.toString(), rejected);
	}

	/**
	 * @return value of Inprogress
	 */
	public final java.lang.Integer getInprogress()
	{
		return getInprogress(getContext());
	}

	/**
	 * @param context
	 * @return value of Inprogress
	 */
	public final java.lang.Integer getInprogress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Inprogress.toString());
	}

	/**
	 * Set value of Inprogress
	 * @param inprogress
	 */
	public final void setInprogress(java.lang.Integer inprogress)
	{
		setInprogress(getContext(), inprogress);
	}

	/**
	 * Set value of Inprogress
	 * @param context
	 * @param inprogress
	 */
	public final void setInprogress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer inprogress)
	{
		getMendixObject().setValue(context, MemberNames.Inprogress.toString(), inprogress);
	}

	/**
	 * @return value of Pending
	 */
	public final java.lang.Integer getPending()
	{
		return getPending(getContext());
	}

	/**
	 * @param context
	 * @return value of Pending
	 */
	public final java.lang.Integer getPending(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Pending.toString());
	}

	/**
	 * Set value of Pending
	 * @param pending
	 */
	public final void setPending(java.lang.Integer pending)
	{
		setPending(getContext(), pending);
	}

	/**
	 * Set value of Pending
	 * @param context
	 * @param pending
	 */
	public final void setPending(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pending)
	{
		getMendixObject().setValue(context, MemberNames.Pending.toString(), pending);
	}

	/**
	 * @return value of jan
	 */
	public final java.lang.Integer getjan()
	{
		return getjan(getContext());
	}

	/**
	 * @param context
	 * @return value of jan
	 */
	public final java.lang.Integer getjan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.jan.toString());
	}

	/**
	 * Set value of jan
	 * @param jan
	 */
	public final void setjan(java.lang.Integer jan)
	{
		setjan(getContext(), jan);
	}

	/**
	 * Set value of jan
	 * @param context
	 * @param jan
	 */
	public final void setjan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer jan)
	{
		getMendixObject().setValue(context, MemberNames.jan.toString(), jan);
	}

	/**
	 * @return value of Feb
	 */
	public final java.lang.Integer getFeb()
	{
		return getFeb(getContext());
	}

	/**
	 * @param context
	 * @return value of Feb
	 */
	public final java.lang.Integer getFeb(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Feb.toString());
	}

	/**
	 * Set value of Feb
	 * @param feb
	 */
	public final void setFeb(java.lang.Integer feb)
	{
		setFeb(getContext(), feb);
	}

	/**
	 * Set value of Feb
	 * @param context
	 * @param feb
	 */
	public final void setFeb(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer feb)
	{
		getMendixObject().setValue(context, MemberNames.Feb.toString(), feb);
	}

	/**
	 * @return value of mar
	 */
	public final java.lang.Integer getmar()
	{
		return getmar(getContext());
	}

	/**
	 * @param context
	 * @return value of mar
	 */
	public final java.lang.Integer getmar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.mar.toString());
	}

	/**
	 * Set value of mar
	 * @param mar
	 */
	public final void setmar(java.lang.Integer mar)
	{
		setmar(getContext(), mar);
	}

	/**
	 * Set value of mar
	 * @param context
	 * @param mar
	 */
	public final void setmar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer mar)
	{
		getMendixObject().setValue(context, MemberNames.mar.toString(), mar);
	}

	/**
	 * @return value of Apr
	 */
	public final java.lang.Integer getApr()
	{
		return getApr(getContext());
	}

	/**
	 * @param context
	 * @return value of Apr
	 */
	public final java.lang.Integer getApr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Apr.toString());
	}

	/**
	 * Set value of Apr
	 * @param apr
	 */
	public final void setApr(java.lang.Integer apr)
	{
		setApr(getContext(), apr);
	}

	/**
	 * Set value of Apr
	 * @param context
	 * @param apr
	 */
	public final void setApr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer apr)
	{
		getMendixObject().setValue(context, MemberNames.Apr.toString(), apr);
	}

	/**
	 * @return value of May
	 */
	public final java.lang.Integer getMay()
	{
		return getMay(getContext());
	}

	/**
	 * @param context
	 * @return value of May
	 */
	public final java.lang.Integer getMay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.May.toString());
	}

	/**
	 * Set value of May
	 * @param may
	 */
	public final void setMay(java.lang.Integer may)
	{
		setMay(getContext(), may);
	}

	/**
	 * Set value of May
	 * @param context
	 * @param may
	 */
	public final void setMay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer may)
	{
		getMendixObject().setValue(context, MemberNames.May.toString(), may);
	}

	/**
	 * @return value of Jun
	 */
	public final java.lang.Integer getJun()
	{
		return getJun(getContext());
	}

	/**
	 * @param context
	 * @return value of Jun
	 */
	public final java.lang.Integer getJun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Jun.toString());
	}

	/**
	 * Set value of Jun
	 * @param jun
	 */
	public final void setJun(java.lang.Integer jun)
	{
		setJun(getContext(), jun);
	}

	/**
	 * Set value of Jun
	 * @param context
	 * @param jun
	 */
	public final void setJun(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer jun)
	{
		getMendixObject().setValue(context, MemberNames.Jun.toString(), jun);
	}

	/**
	 * @return value of july
	 */
	public final java.lang.Integer getjuly()
	{
		return getjuly(getContext());
	}

	/**
	 * @param context
	 * @return value of july
	 */
	public final java.lang.Integer getjuly(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.july.toString());
	}

	/**
	 * Set value of july
	 * @param july
	 */
	public final void setjuly(java.lang.Integer july)
	{
		setjuly(getContext(), july);
	}

	/**
	 * Set value of july
	 * @param context
	 * @param july
	 */
	public final void setjuly(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer july)
	{
		getMendixObject().setValue(context, MemberNames.july.toString(), july);
	}

	/**
	 * @return value of Aug
	 */
	public final java.lang.Integer getAug()
	{
		return getAug(getContext());
	}

	/**
	 * @param context
	 * @return value of Aug
	 */
	public final java.lang.Integer getAug(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Aug.toString());
	}

	/**
	 * Set value of Aug
	 * @param aug
	 */
	public final void setAug(java.lang.Integer aug)
	{
		setAug(getContext(), aug);
	}

	/**
	 * Set value of Aug
	 * @param context
	 * @param aug
	 */
	public final void setAug(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer aug)
	{
		getMendixObject().setValue(context, MemberNames.Aug.toString(), aug);
	}

	/**
	 * @return value of sep
	 */
	public final java.lang.Integer getsep()
	{
		return getsep(getContext());
	}

	/**
	 * @param context
	 * @return value of sep
	 */
	public final java.lang.Integer getsep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.sep.toString());
	}

	/**
	 * Set value of sep
	 * @param sep
	 */
	public final void setsep(java.lang.Integer sep)
	{
		setsep(getContext(), sep);
	}

	/**
	 * Set value of sep
	 * @param context
	 * @param sep
	 */
	public final void setsep(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sep)
	{
		getMendixObject().setValue(context, MemberNames.sep.toString(), sep);
	}

	/**
	 * @return value of oct
	 */
	public final java.lang.Integer getoct()
	{
		return getoct(getContext());
	}

	/**
	 * @param context
	 * @return value of oct
	 */
	public final java.lang.Integer getoct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.oct.toString());
	}

	/**
	 * Set value of oct
	 * @param oct
	 */
	public final void setoct(java.lang.Integer oct)
	{
		setoct(getContext(), oct);
	}

	/**
	 * Set value of oct
	 * @param context
	 * @param oct
	 */
	public final void setoct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer oct)
	{
		getMendixObject().setValue(context, MemberNames.oct.toString(), oct);
	}

	/**
	 * @return value of Nov
	 */
	public final java.lang.Integer getNov()
	{
		return getNov(getContext());
	}

	/**
	 * @param context
	 * @return value of Nov
	 */
	public final java.lang.Integer getNov(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Nov.toString());
	}

	/**
	 * Set value of Nov
	 * @param nov
	 */
	public final void setNov(java.lang.Integer nov)
	{
		setNov(getContext(), nov);
	}

	/**
	 * Set value of Nov
	 * @param context
	 * @param nov
	 */
	public final void setNov(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nov)
	{
		getMendixObject().setValue(context, MemberNames.Nov.toString(), nov);
	}

	/**
	 * @return value of Dec
	 */
	public final java.lang.Integer getDec()
	{
		return getDec(getContext());
	}

	/**
	 * @param context
	 * @return value of Dec
	 */
	public final java.lang.Integer getDec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Dec.toString());
	}

	/**
	 * Set value of Dec
	 * @param dec
	 */
	public final void setDec(java.lang.Integer dec)
	{
		setDec(getContext(), dec);
	}

	/**
	 * Set value of Dec
	 * @param context
	 * @param dec
	 */
	public final void setDec(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dec)
	{
		getMendixObject().setValue(context, MemberNames.Dec.toString(), dec);
	}

	/**
	 * @return value of R_Jan
	 */
	public final java.lang.Integer getR_Jan()
	{
		return getR_Jan(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Jan
	 */
	public final java.lang.Integer getR_Jan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Jan.toString());
	}

	/**
	 * Set value of R_Jan
	 * @param r_jan
	 */
	public final void setR_Jan(java.lang.Integer r_jan)
	{
		setR_Jan(getContext(), r_jan);
	}

	/**
	 * Set value of R_Jan
	 * @param context
	 * @param r_jan
	 */
	public final void setR_Jan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_jan)
	{
		getMendixObject().setValue(context, MemberNames.R_Jan.toString(), r_jan);
	}

	/**
	 * @return value of R_Feb
	 */
	public final java.lang.Integer getR_Feb()
	{
		return getR_Feb(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Feb
	 */
	public final java.lang.Integer getR_Feb(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Feb.toString());
	}

	/**
	 * Set value of R_Feb
	 * @param r_feb
	 */
	public final void setR_Feb(java.lang.Integer r_feb)
	{
		setR_Feb(getContext(), r_feb);
	}

	/**
	 * Set value of R_Feb
	 * @param context
	 * @param r_feb
	 */
	public final void setR_Feb(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_feb)
	{
		getMendixObject().setValue(context, MemberNames.R_Feb.toString(), r_feb);
	}

	/**
	 * @return value of R_Mar
	 */
	public final java.lang.Integer getR_Mar()
	{
		return getR_Mar(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Mar
	 */
	public final java.lang.Integer getR_Mar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Mar.toString());
	}

	/**
	 * Set value of R_Mar
	 * @param r_mar
	 */
	public final void setR_Mar(java.lang.Integer r_mar)
	{
		setR_Mar(getContext(), r_mar);
	}

	/**
	 * Set value of R_Mar
	 * @param context
	 * @param r_mar
	 */
	public final void setR_Mar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_mar)
	{
		getMendixObject().setValue(context, MemberNames.R_Mar.toString(), r_mar);
	}

	/**
	 * @return value of R_Apr
	 */
	public final java.lang.Integer getR_Apr()
	{
		return getR_Apr(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Apr
	 */
	public final java.lang.Integer getR_Apr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Apr.toString());
	}

	/**
	 * Set value of R_Apr
	 * @param r_apr
	 */
	public final void setR_Apr(java.lang.Integer r_apr)
	{
		setR_Apr(getContext(), r_apr);
	}

	/**
	 * Set value of R_Apr
	 * @param context
	 * @param r_apr
	 */
	public final void setR_Apr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_apr)
	{
		getMendixObject().setValue(context, MemberNames.R_Apr.toString(), r_apr);
	}

	/**
	 * @return value of R_May
	 */
	public final java.lang.Integer getR_May()
	{
		return getR_May(getContext());
	}

	/**
	 * @param context
	 * @return value of R_May
	 */
	public final java.lang.Integer getR_May(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_May.toString());
	}

	/**
	 * Set value of R_May
	 * @param r_may
	 */
	public final void setR_May(java.lang.Integer r_may)
	{
		setR_May(getContext(), r_may);
	}

	/**
	 * Set value of R_May
	 * @param context
	 * @param r_may
	 */
	public final void setR_May(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_may)
	{
		getMendixObject().setValue(context, MemberNames.R_May.toString(), r_may);
	}

	/**
	 * @return value of R_Jun
	 */
	public final java.lang.Integer getR_Jun()
	{
		return getR_Jun(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Jun
	 */
	public final java.lang.Integer getR_Jun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Jun.toString());
	}

	/**
	 * Set value of R_Jun
	 * @param r_jun
	 */
	public final void setR_Jun(java.lang.Integer r_jun)
	{
		setR_Jun(getContext(), r_jun);
	}

	/**
	 * Set value of R_Jun
	 * @param context
	 * @param r_jun
	 */
	public final void setR_Jun(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_jun)
	{
		getMendixObject().setValue(context, MemberNames.R_Jun.toString(), r_jun);
	}

	/**
	 * @return value of R_Jul
	 */
	public final java.lang.Integer getR_Jul()
	{
		return getR_Jul(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Jul
	 */
	public final java.lang.Integer getR_Jul(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Jul.toString());
	}

	/**
	 * Set value of R_Jul
	 * @param r_jul
	 */
	public final void setR_Jul(java.lang.Integer r_jul)
	{
		setR_Jul(getContext(), r_jul);
	}

	/**
	 * Set value of R_Jul
	 * @param context
	 * @param r_jul
	 */
	public final void setR_Jul(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_jul)
	{
		getMendixObject().setValue(context, MemberNames.R_Jul.toString(), r_jul);
	}

	/**
	 * @return value of R_Aug
	 */
	public final java.lang.Integer getR_Aug()
	{
		return getR_Aug(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Aug
	 */
	public final java.lang.Integer getR_Aug(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Aug.toString());
	}

	/**
	 * Set value of R_Aug
	 * @param r_aug
	 */
	public final void setR_Aug(java.lang.Integer r_aug)
	{
		setR_Aug(getContext(), r_aug);
	}

	/**
	 * Set value of R_Aug
	 * @param context
	 * @param r_aug
	 */
	public final void setR_Aug(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_aug)
	{
		getMendixObject().setValue(context, MemberNames.R_Aug.toString(), r_aug);
	}

	/**
	 * @return value of R_Sep
	 */
	public final java.lang.Integer getR_Sep()
	{
		return getR_Sep(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Sep
	 */
	public final java.lang.Integer getR_Sep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Sep.toString());
	}

	/**
	 * Set value of R_Sep
	 * @param r_sep
	 */
	public final void setR_Sep(java.lang.Integer r_sep)
	{
		setR_Sep(getContext(), r_sep);
	}

	/**
	 * Set value of R_Sep
	 * @param context
	 * @param r_sep
	 */
	public final void setR_Sep(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_sep)
	{
		getMendixObject().setValue(context, MemberNames.R_Sep.toString(), r_sep);
	}

	/**
	 * @return value of R_oct
	 */
	public final java.lang.Integer getR_oct()
	{
		return getR_oct(getContext());
	}

	/**
	 * @param context
	 * @return value of R_oct
	 */
	public final java.lang.Integer getR_oct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_oct.toString());
	}

	/**
	 * Set value of R_oct
	 * @param r_oct
	 */
	public final void setR_oct(java.lang.Integer r_oct)
	{
		setR_oct(getContext(), r_oct);
	}

	/**
	 * Set value of R_oct
	 * @param context
	 * @param r_oct
	 */
	public final void setR_oct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_oct)
	{
		getMendixObject().setValue(context, MemberNames.R_oct.toString(), r_oct);
	}

	/**
	 * @return value of R_Nov
	 */
	public final java.lang.Integer getR_Nov()
	{
		return getR_Nov(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Nov
	 */
	public final java.lang.Integer getR_Nov(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Nov.toString());
	}

	/**
	 * Set value of R_Nov
	 * @param r_nov
	 */
	public final void setR_Nov(java.lang.Integer r_nov)
	{
		setR_Nov(getContext(), r_nov);
	}

	/**
	 * Set value of R_Nov
	 * @param context
	 * @param r_nov
	 */
	public final void setR_Nov(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_nov)
	{
		getMendixObject().setValue(context, MemberNames.R_Nov.toString(), r_nov);
	}

	/**
	 * @return value of R_Dec
	 */
	public final java.lang.Integer getR_Dec()
	{
		return getR_Dec(getContext());
	}

	/**
	 * @param context
	 * @return value of R_Dec
	 */
	public final java.lang.Integer getR_Dec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.R_Dec.toString());
	}

	/**
	 * Set value of R_Dec
	 * @param r_dec
	 */
	public final void setR_Dec(java.lang.Integer r_dec)
	{
		setR_Dec(getContext(), r_dec);
	}

	/**
	 * Set value of R_Dec
	 * @param context
	 * @param r_dec
	 */
	public final void setR_Dec(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer r_dec)
	{
		getMendixObject().setValue(context, MemberNames.R_Dec.toString(), r_dec);
	}

	/**
	 * @return value of In_Jan
	 */
	public final java.lang.Integer getIn_Jan()
	{
		return getIn_Jan(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Jan
	 */
	public final java.lang.Integer getIn_Jan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Jan.toString());
	}

	/**
	 * Set value of In_Jan
	 * @param in_jan
	 */
	public final void setIn_Jan(java.lang.Integer in_jan)
	{
		setIn_Jan(getContext(), in_jan);
	}

	/**
	 * Set value of In_Jan
	 * @param context
	 * @param in_jan
	 */
	public final void setIn_Jan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_jan)
	{
		getMendixObject().setValue(context, MemberNames.In_Jan.toString(), in_jan);
	}

	/**
	 * @return value of In_Feb
	 */
	public final java.lang.Integer getIn_Feb()
	{
		return getIn_Feb(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Feb
	 */
	public final java.lang.Integer getIn_Feb(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Feb.toString());
	}

	/**
	 * Set value of In_Feb
	 * @param in_feb
	 */
	public final void setIn_Feb(java.lang.Integer in_feb)
	{
		setIn_Feb(getContext(), in_feb);
	}

	/**
	 * Set value of In_Feb
	 * @param context
	 * @param in_feb
	 */
	public final void setIn_Feb(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_feb)
	{
		getMendixObject().setValue(context, MemberNames.In_Feb.toString(), in_feb);
	}

	/**
	 * @return value of In_Mar
	 */
	public final java.lang.Integer getIn_Mar()
	{
		return getIn_Mar(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Mar
	 */
	public final java.lang.Integer getIn_Mar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Mar.toString());
	}

	/**
	 * Set value of In_Mar
	 * @param in_mar
	 */
	public final void setIn_Mar(java.lang.Integer in_mar)
	{
		setIn_Mar(getContext(), in_mar);
	}

	/**
	 * Set value of In_Mar
	 * @param context
	 * @param in_mar
	 */
	public final void setIn_Mar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_mar)
	{
		getMendixObject().setValue(context, MemberNames.In_Mar.toString(), in_mar);
	}

	/**
	 * @return value of In_Apr
	 */
	public final java.lang.Integer getIn_Apr()
	{
		return getIn_Apr(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Apr
	 */
	public final java.lang.Integer getIn_Apr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Apr.toString());
	}

	/**
	 * Set value of In_Apr
	 * @param in_apr
	 */
	public final void setIn_Apr(java.lang.Integer in_apr)
	{
		setIn_Apr(getContext(), in_apr);
	}

	/**
	 * Set value of In_Apr
	 * @param context
	 * @param in_apr
	 */
	public final void setIn_Apr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_apr)
	{
		getMendixObject().setValue(context, MemberNames.In_Apr.toString(), in_apr);
	}

	/**
	 * @return value of In_May
	 */
	public final java.lang.Integer getIn_May()
	{
		return getIn_May(getContext());
	}

	/**
	 * @param context
	 * @return value of In_May
	 */
	public final java.lang.Integer getIn_May(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_May.toString());
	}

	/**
	 * Set value of In_May
	 * @param in_may
	 */
	public final void setIn_May(java.lang.Integer in_may)
	{
		setIn_May(getContext(), in_may);
	}

	/**
	 * Set value of In_May
	 * @param context
	 * @param in_may
	 */
	public final void setIn_May(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_may)
	{
		getMendixObject().setValue(context, MemberNames.In_May.toString(), in_may);
	}

	/**
	 * @return value of In_Jun
	 */
	public final java.lang.Integer getIn_Jun()
	{
		return getIn_Jun(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Jun
	 */
	public final java.lang.Integer getIn_Jun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Jun.toString());
	}

	/**
	 * Set value of In_Jun
	 * @param in_jun
	 */
	public final void setIn_Jun(java.lang.Integer in_jun)
	{
		setIn_Jun(getContext(), in_jun);
	}

	/**
	 * Set value of In_Jun
	 * @param context
	 * @param in_jun
	 */
	public final void setIn_Jun(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_jun)
	{
		getMendixObject().setValue(context, MemberNames.In_Jun.toString(), in_jun);
	}

	/**
	 * @return value of In_Jul
	 */
	public final java.lang.Integer getIn_Jul()
	{
		return getIn_Jul(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Jul
	 */
	public final java.lang.Integer getIn_Jul(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Jul.toString());
	}

	/**
	 * Set value of In_Jul
	 * @param in_jul
	 */
	public final void setIn_Jul(java.lang.Integer in_jul)
	{
		setIn_Jul(getContext(), in_jul);
	}

	/**
	 * Set value of In_Jul
	 * @param context
	 * @param in_jul
	 */
	public final void setIn_Jul(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_jul)
	{
		getMendixObject().setValue(context, MemberNames.In_Jul.toString(), in_jul);
	}

	/**
	 * @return value of In_Aug
	 */
	public final java.lang.Integer getIn_Aug()
	{
		return getIn_Aug(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Aug
	 */
	public final java.lang.Integer getIn_Aug(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Aug.toString());
	}

	/**
	 * Set value of In_Aug
	 * @param in_aug
	 */
	public final void setIn_Aug(java.lang.Integer in_aug)
	{
		setIn_Aug(getContext(), in_aug);
	}

	/**
	 * Set value of In_Aug
	 * @param context
	 * @param in_aug
	 */
	public final void setIn_Aug(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_aug)
	{
		getMendixObject().setValue(context, MemberNames.In_Aug.toString(), in_aug);
	}

	/**
	 * @return value of In_Sep
	 */
	public final java.lang.Integer getIn_Sep()
	{
		return getIn_Sep(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Sep
	 */
	public final java.lang.Integer getIn_Sep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Sep.toString());
	}

	/**
	 * Set value of In_Sep
	 * @param in_sep
	 */
	public final void setIn_Sep(java.lang.Integer in_sep)
	{
		setIn_Sep(getContext(), in_sep);
	}

	/**
	 * Set value of In_Sep
	 * @param context
	 * @param in_sep
	 */
	public final void setIn_Sep(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_sep)
	{
		getMendixObject().setValue(context, MemberNames.In_Sep.toString(), in_sep);
	}

	/**
	 * @return value of In_Nov
	 */
	public final java.lang.Integer getIn_Nov()
	{
		return getIn_Nov(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Nov
	 */
	public final java.lang.Integer getIn_Nov(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Nov.toString());
	}

	/**
	 * Set value of In_Nov
	 * @param in_nov
	 */
	public final void setIn_Nov(java.lang.Integer in_nov)
	{
		setIn_Nov(getContext(), in_nov);
	}

	/**
	 * Set value of In_Nov
	 * @param context
	 * @param in_nov
	 */
	public final void setIn_Nov(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_nov)
	{
		getMendixObject().setValue(context, MemberNames.In_Nov.toString(), in_nov);
	}

	/**
	 * @return value of In_Dec
	 */
	public final java.lang.Integer getIn_Dec()
	{
		return getIn_Dec(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Dec
	 */
	public final java.lang.Integer getIn_Dec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Dec.toString());
	}

	/**
	 * Set value of In_Dec
	 * @param in_dec
	 */
	public final void setIn_Dec(java.lang.Integer in_dec)
	{
		setIn_Dec(getContext(), in_dec);
	}

	/**
	 * Set value of In_Dec
	 * @param context
	 * @param in_dec
	 */
	public final void setIn_Dec(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_dec)
	{
		getMendixObject().setValue(context, MemberNames.In_Dec.toString(), in_dec);
	}

	/**
	 * @return value of P_Jan
	 */
	public final java.lang.Integer getP_Jan()
	{
		return getP_Jan(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Jan
	 */
	public final java.lang.Integer getP_Jan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Jan.toString());
	}

	/**
	 * Set value of P_Jan
	 * @param p_jan
	 */
	public final void setP_Jan(java.lang.Integer p_jan)
	{
		setP_Jan(getContext(), p_jan);
	}

	/**
	 * Set value of P_Jan
	 * @param context
	 * @param p_jan
	 */
	public final void setP_Jan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_jan)
	{
		getMendixObject().setValue(context, MemberNames.P_Jan.toString(), p_jan);
	}

	/**
	 * @return value of P_Feb
	 */
	public final java.lang.Integer getP_Feb()
	{
		return getP_Feb(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Feb
	 */
	public final java.lang.Integer getP_Feb(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Feb.toString());
	}

	/**
	 * Set value of P_Feb
	 * @param p_feb
	 */
	public final void setP_Feb(java.lang.Integer p_feb)
	{
		setP_Feb(getContext(), p_feb);
	}

	/**
	 * Set value of P_Feb
	 * @param context
	 * @param p_feb
	 */
	public final void setP_Feb(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_feb)
	{
		getMendixObject().setValue(context, MemberNames.P_Feb.toString(), p_feb);
	}

	/**
	 * @return value of P_Mar
	 */
	public final java.lang.Integer getP_Mar()
	{
		return getP_Mar(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Mar
	 */
	public final java.lang.Integer getP_Mar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Mar.toString());
	}

	/**
	 * Set value of P_Mar
	 * @param p_mar
	 */
	public final void setP_Mar(java.lang.Integer p_mar)
	{
		setP_Mar(getContext(), p_mar);
	}

	/**
	 * Set value of P_Mar
	 * @param context
	 * @param p_mar
	 */
	public final void setP_Mar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_mar)
	{
		getMendixObject().setValue(context, MemberNames.P_Mar.toString(), p_mar);
	}

	/**
	 * @return value of P_Apr
	 */
	public final java.lang.Integer getP_Apr()
	{
		return getP_Apr(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Apr
	 */
	public final java.lang.Integer getP_Apr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Apr.toString());
	}

	/**
	 * Set value of P_Apr
	 * @param p_apr
	 */
	public final void setP_Apr(java.lang.Integer p_apr)
	{
		setP_Apr(getContext(), p_apr);
	}

	/**
	 * Set value of P_Apr
	 * @param context
	 * @param p_apr
	 */
	public final void setP_Apr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_apr)
	{
		getMendixObject().setValue(context, MemberNames.P_Apr.toString(), p_apr);
	}

	/**
	 * @return value of P_May
	 */
	public final java.lang.Integer getP_May()
	{
		return getP_May(getContext());
	}

	/**
	 * @param context
	 * @return value of P_May
	 */
	public final java.lang.Integer getP_May(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_May.toString());
	}

	/**
	 * Set value of P_May
	 * @param p_may
	 */
	public final void setP_May(java.lang.Integer p_may)
	{
		setP_May(getContext(), p_may);
	}

	/**
	 * Set value of P_May
	 * @param context
	 * @param p_may
	 */
	public final void setP_May(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_may)
	{
		getMendixObject().setValue(context, MemberNames.P_May.toString(), p_may);
	}

	/**
	 * @return value of P_Jun
	 */
	public final java.lang.Integer getP_Jun()
	{
		return getP_Jun(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Jun
	 */
	public final java.lang.Integer getP_Jun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Jun.toString());
	}

	/**
	 * Set value of P_Jun
	 * @param p_jun
	 */
	public final void setP_Jun(java.lang.Integer p_jun)
	{
		setP_Jun(getContext(), p_jun);
	}

	/**
	 * Set value of P_Jun
	 * @param context
	 * @param p_jun
	 */
	public final void setP_Jun(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_jun)
	{
		getMendixObject().setValue(context, MemberNames.P_Jun.toString(), p_jun);
	}

	/**
	 * @return value of P_Jul
	 */
	public final java.lang.Integer getP_Jul()
	{
		return getP_Jul(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Jul
	 */
	public final java.lang.Integer getP_Jul(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Jul.toString());
	}

	/**
	 * Set value of P_Jul
	 * @param p_jul
	 */
	public final void setP_Jul(java.lang.Integer p_jul)
	{
		setP_Jul(getContext(), p_jul);
	}

	/**
	 * Set value of P_Jul
	 * @param context
	 * @param p_jul
	 */
	public final void setP_Jul(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_jul)
	{
		getMendixObject().setValue(context, MemberNames.P_Jul.toString(), p_jul);
	}

	/**
	 * @return value of P_Aug
	 */
	public final java.lang.Integer getP_Aug()
	{
		return getP_Aug(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Aug
	 */
	public final java.lang.Integer getP_Aug(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Aug.toString());
	}

	/**
	 * Set value of P_Aug
	 * @param p_aug
	 */
	public final void setP_Aug(java.lang.Integer p_aug)
	{
		setP_Aug(getContext(), p_aug);
	}

	/**
	 * Set value of P_Aug
	 * @param context
	 * @param p_aug
	 */
	public final void setP_Aug(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_aug)
	{
		getMendixObject().setValue(context, MemberNames.P_Aug.toString(), p_aug);
	}

	/**
	 * @return value of P_Sep
	 */
	public final java.lang.Integer getP_Sep()
	{
		return getP_Sep(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Sep
	 */
	public final java.lang.Integer getP_Sep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Sep.toString());
	}

	/**
	 * Set value of P_Sep
	 * @param p_sep
	 */
	public final void setP_Sep(java.lang.Integer p_sep)
	{
		setP_Sep(getContext(), p_sep);
	}

	/**
	 * Set value of P_Sep
	 * @param context
	 * @param p_sep
	 */
	public final void setP_Sep(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_sep)
	{
		getMendixObject().setValue(context, MemberNames.P_Sep.toString(), p_sep);
	}

	/**
	 * @return value of P_Oct
	 */
	public final java.lang.Integer getP_Oct()
	{
		return getP_Oct(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Oct
	 */
	public final java.lang.Integer getP_Oct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Oct.toString());
	}

	/**
	 * Set value of P_Oct
	 * @param p_oct
	 */
	public final void setP_Oct(java.lang.Integer p_oct)
	{
		setP_Oct(getContext(), p_oct);
	}

	/**
	 * Set value of P_Oct
	 * @param context
	 * @param p_oct
	 */
	public final void setP_Oct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_oct)
	{
		getMendixObject().setValue(context, MemberNames.P_Oct.toString(), p_oct);
	}

	/**
	 * @return value of P_Nov
	 */
	public final java.lang.Integer getP_Nov()
	{
		return getP_Nov(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Nov
	 */
	public final java.lang.Integer getP_Nov(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Nov.toString());
	}

	/**
	 * Set value of P_Nov
	 * @param p_nov
	 */
	public final void setP_Nov(java.lang.Integer p_nov)
	{
		setP_Nov(getContext(), p_nov);
	}

	/**
	 * Set value of P_Nov
	 * @param context
	 * @param p_nov
	 */
	public final void setP_Nov(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_nov)
	{
		getMendixObject().setValue(context, MemberNames.P_Nov.toString(), p_nov);
	}

	/**
	 * @return value of P_Dec
	 */
	public final java.lang.Integer getP_Dec()
	{
		return getP_Dec(getContext());
	}

	/**
	 * @param context
	 * @return value of P_Dec
	 */
	public final java.lang.Integer getP_Dec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.P_Dec.toString());
	}

	/**
	 * Set value of P_Dec
	 * @param p_dec
	 */
	public final void setP_Dec(java.lang.Integer p_dec)
	{
		setP_Dec(getContext(), p_dec);
	}

	/**
	 * Set value of P_Dec
	 * @param context
	 * @param p_dec
	 */
	public final void setP_Dec(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer p_dec)
	{
		getMendixObject().setValue(context, MemberNames.P_Dec.toString(), p_dec);
	}

	/**
	 * @return value of In_Oct
	 */
	public final java.lang.Integer getIn_Oct()
	{
		return getIn_Oct(getContext());
	}

	/**
	 * @param context
	 * @return value of In_Oct
	 */
	public final java.lang.Integer getIn_Oct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.In_Oct.toString());
	}

	/**
	 * Set value of In_Oct
	 * @param in_oct
	 */
	public final void setIn_Oct(java.lang.Integer in_oct)
	{
		setIn_Oct(getContext(), in_oct);
	}

	/**
	 * Set value of In_Oct
	 * @param context
	 * @param in_oct
	 */
	public final void setIn_Oct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer in_oct)
	{
		getMendixObject().setValue(context, MemberNames.In_Oct.toString(), in_oct);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return monthMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.month that = (myfirstmodule.proxies.month) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
