// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class PowerBI
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject powerBIMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.PowerBI";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GroupID("GroupID"),
		ReportID("ReportID"),
		EmbedURL("EmbedURL"),
		AccessToken("AccessToken"),
		DatasetID("DatasetID"),
		EmbedToken("EmbedToken");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PowerBI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PowerBI(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject powerBIMendixObject)
	{
		if (powerBIMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, powerBIMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.powerBIMendixObject = powerBIMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PowerBI.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.PowerBI initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.PowerBI.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.PowerBI initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.PowerBI(context, mendixObject);
	}

	public static myfirstmodule.proxies.PowerBI load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.PowerBI.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of GroupID
	 */
	public final java.lang.String getGroupID()
	{
		return getGroupID(getContext());
	}

	/**
	 * @param context
	 * @return value of GroupID
	 */
	public final java.lang.String getGroupID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GroupID.toString());
	}

	/**
	 * Set value of GroupID
	 * @param groupid
	 */
	public final void setGroupID(java.lang.String groupid)
	{
		setGroupID(getContext(), groupid);
	}

	/**
	 * Set value of GroupID
	 * @param context
	 * @param groupid
	 */
	public final void setGroupID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String groupid)
	{
		getMendixObject().setValue(context, MemberNames.GroupID.toString(), groupid);
	}

	/**
	 * @return value of ReportID
	 */
	public final java.lang.String getReportID()
	{
		return getReportID(getContext());
	}

	/**
	 * @param context
	 * @return value of ReportID
	 */
	public final java.lang.String getReportID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReportID.toString());
	}

	/**
	 * Set value of ReportID
	 * @param reportid
	 */
	public final void setReportID(java.lang.String reportid)
	{
		setReportID(getContext(), reportid);
	}

	/**
	 * Set value of ReportID
	 * @param context
	 * @param reportid
	 */
	public final void setReportID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reportid)
	{
		getMendixObject().setValue(context, MemberNames.ReportID.toString(), reportid);
	}

	/**
	 * @return value of EmbedURL
	 */
	public final java.lang.String getEmbedURL()
	{
		return getEmbedURL(getContext());
	}

	/**
	 * @param context
	 * @return value of EmbedURL
	 */
	public final java.lang.String getEmbedURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmbedURL.toString());
	}

	/**
	 * Set value of EmbedURL
	 * @param embedurl
	 */
	public final void setEmbedURL(java.lang.String embedurl)
	{
		setEmbedURL(getContext(), embedurl);
	}

	/**
	 * Set value of EmbedURL
	 * @param context
	 * @param embedurl
	 */
	public final void setEmbedURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String embedurl)
	{
		getMendixObject().setValue(context, MemberNames.EmbedURL.toString(), embedurl);
	}

	/**
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken()
	{
		return getAccessToken(getContext());
	}

	/**
	 * @param context
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccessToken.toString());
	}

	/**
	 * Set value of AccessToken
	 * @param accesstoken
	 */
	public final void setAccessToken(java.lang.String accesstoken)
	{
		setAccessToken(getContext(), accesstoken);
	}

	/**
	 * Set value of AccessToken
	 * @param context
	 * @param accesstoken
	 */
	public final void setAccessToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accesstoken)
	{
		getMendixObject().setValue(context, MemberNames.AccessToken.toString(), accesstoken);
	}

	/**
	 * @return value of DatasetID
	 */
	public final java.lang.String getDatasetID()
	{
		return getDatasetID(getContext());
	}

	/**
	 * @param context
	 * @return value of DatasetID
	 */
	public final java.lang.String getDatasetID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DatasetID.toString());
	}

	/**
	 * Set value of DatasetID
	 * @param datasetid
	 */
	public final void setDatasetID(java.lang.String datasetid)
	{
		setDatasetID(getContext(), datasetid);
	}

	/**
	 * Set value of DatasetID
	 * @param context
	 * @param datasetid
	 */
	public final void setDatasetID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datasetid)
	{
		getMendixObject().setValue(context, MemberNames.DatasetID.toString(), datasetid);
	}

	/**
	 * @return value of EmbedToken
	 */
	public final java.lang.String getEmbedToken()
	{
		return getEmbedToken(getContext());
	}

	/**
	 * @param context
	 * @return value of EmbedToken
	 */
	public final java.lang.String getEmbedToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmbedToken.toString());
	}

	/**
	 * Set value of EmbedToken
	 * @param embedtoken
	 */
	public final void setEmbedToken(java.lang.String embedtoken)
	{
		setEmbedToken(getContext(), embedtoken);
	}

	/**
	 * Set value of EmbedToken
	 * @param context
	 * @param embedtoken
	 */
	public final void setEmbedToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String embedtoken)
	{
		getMendixObject().setValue(context, MemberNames.EmbedToken.toString(), embedtoken);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return powerBIMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.PowerBI that = (myfirstmodule.proxies.PowerBI) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
