// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Priority
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject priorityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Priority";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Prioity_Enum("Prioity_Enum"),
		Prioity_Low("Prioity_Low"),
		Prioity_Medium("Prioity_Medium"),
		Priority_high("Priority_high"),
		Priority_Applicant("MyFirstModule.Priority_Applicant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Priority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Priority(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject priorityMendixObject)
	{
		if (priorityMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, priorityMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.priorityMendixObject = priorityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Priority.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Priority initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Priority.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Priority initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Priority(context, mendixObject);
	}

	public static myfirstmodule.proxies.Priority load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Priority.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Priority> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Priority.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Prioity_Enum
	 * @param prioity_enum
	 */
	public final myfirstmodule.proxies.Prioity_Enum getPrioity_Enum()
	{
		return getPrioity_Enum(getContext());
	}

	/**
	 * @param context
	 * @return value of Prioity_Enum
	 */
	public final myfirstmodule.proxies.Prioity_Enum getPrioity_Enum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Prioity_Enum.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Prioity_Enum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Prioity_Enum
	 * @param prioity_enum
	 */
	public final void setPrioity_Enum(myfirstmodule.proxies.Prioity_Enum prioity_enum)
	{
		setPrioity_Enum(getContext(), prioity_enum);
	}

	/**
	 * Set value of Prioity_Enum
	 * @param context
	 * @param prioity_enum
	 */
	public final void setPrioity_Enum(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Prioity_Enum prioity_enum)
	{
		if (prioity_enum != null) {
			getMendixObject().setValue(context, MemberNames.Prioity_Enum.toString(), prioity_enum.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Prioity_Enum.toString(), null);
		}
	}

	/**
	 * @return value of Prioity_Low
	 */
	public final java.lang.Boolean getPrioity_Low()
	{
		return getPrioity_Low(getContext());
	}

	/**
	 * @param context
	 * @return value of Prioity_Low
	 */
	public final java.lang.Boolean getPrioity_Low(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Prioity_Low.toString());
	}

	/**
	 * Set value of Prioity_Low
	 * @param prioity_low
	 */
	public final void setPrioity_Low(java.lang.Boolean prioity_low)
	{
		setPrioity_Low(getContext(), prioity_low);
	}

	/**
	 * Set value of Prioity_Low
	 * @param context
	 * @param prioity_low
	 */
	public final void setPrioity_Low(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean prioity_low)
	{
		getMendixObject().setValue(context, MemberNames.Prioity_Low.toString(), prioity_low);
	}

	/**
	 * @return value of Prioity_Medium
	 */
	public final java.lang.Boolean getPrioity_Medium()
	{
		return getPrioity_Medium(getContext());
	}

	/**
	 * @param context
	 * @return value of Prioity_Medium
	 */
	public final java.lang.Boolean getPrioity_Medium(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Prioity_Medium.toString());
	}

	/**
	 * Set value of Prioity_Medium
	 * @param prioity_medium
	 */
	public final void setPrioity_Medium(java.lang.Boolean prioity_medium)
	{
		setPrioity_Medium(getContext(), prioity_medium);
	}

	/**
	 * Set value of Prioity_Medium
	 * @param context
	 * @param prioity_medium
	 */
	public final void setPrioity_Medium(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean prioity_medium)
	{
		getMendixObject().setValue(context, MemberNames.Prioity_Medium.toString(), prioity_medium);
	}

	/**
	 * @return value of Priority_high
	 */
	public final java.lang.Boolean getPriority_high()
	{
		return getPriority_high(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority_high
	 */
	public final java.lang.Boolean getPriority_high(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Priority_high.toString());
	}

	/**
	 * Set value of Priority_high
	 * @param priority_high
	 */
	public final void setPriority_high(java.lang.Boolean priority_high)
	{
		setPriority_high(getContext(), priority_high);
	}

	/**
	 * Set value of Priority_high
	 * @param context
	 * @param priority_high
	 */
	public final void setPriority_high(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean priority_high)
	{
		getMendixObject().setValue(context, MemberNames.Priority_high.toString(), priority_high);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Priority_Applicant
	 */
	public final myfirstmodule.proxies.Applicant getPriority_Applicant() throws com.mendix.core.CoreException
	{
		return getPriority_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant getPriority_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Priority_Applicant.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Priority_Applicant
	 * @param priority_applicant
	 */
	public final void setPriority_Applicant(myfirstmodule.proxies.Applicant priority_applicant)
	{
		setPriority_Applicant(getContext(), priority_applicant);
	}

	/**
	 * Set value of Priority_Applicant
	 * @param context
	 * @param priority_applicant
	 */
	public final void setPriority_Applicant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant priority_applicant)
	{
		if (priority_applicant == null) {
			getMendixObject().setValue(context, MemberNames.Priority_Applicant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Priority_Applicant.toString(), priority_applicant.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return priorityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Priority that = (myfirstmodule.proxies.Priority) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
