// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Profile
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject profileMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Profile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Age("Age"),
		Country("Country"),
		Marital_Status("Marital_Status"),
		Phone_Number("Phone_Number"),
		Profile_Account("MyFirstModule.Profile_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Profile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Profile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject profileMendixObject)
	{
		if (profileMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, profileMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.profileMendixObject = profileMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Profile.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Profile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Profile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Profile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Profile(context, mendixObject);
	}

	public static myfirstmodule.proxies.Profile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Profile.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Profile> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Profile.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Age
	 */
	public final java.lang.Integer getAge()
	{
		return getAge(getContext());
	}

	/**
	 * @param context
	 * @return value of Age
	 */
	public final java.lang.Integer getAge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Age.toString());
	}

	/**
	 * Set value of Age
	 * @param age
	 */
	public final void setAge(java.lang.Integer age)
	{
		setAge(getContext(), age);
	}

	/**
	 * Set value of Age
	 * @param context
	 * @param age
	 */
	public final void setAge(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer age)
	{
		getMendixObject().setValue(context, MemberNames.Age.toString(), age);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * Set value of Marital_Status
	 * @param marital_status
	 */
	public final myfirstmodule.proxies.Marital_Status_Enumeration getMarital_Status()
	{
		return getMarital_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of Marital_Status
	 */
	public final myfirstmodule.proxies.Marital_Status_Enumeration getMarital_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Marital_Status.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Marital_Status_Enumeration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Marital_Status
	 * @param marital_status
	 */
	public final void setMarital_Status(myfirstmodule.proxies.Marital_Status_Enumeration marital_status)
	{
		setMarital_Status(getContext(), marital_status);
	}

	/**
	 * Set value of Marital_Status
	 * @param context
	 * @param marital_status
	 */
	public final void setMarital_Status(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Marital_Status_Enumeration marital_status)
	{
		if (marital_status != null) {
			getMendixObject().setValue(context, MemberNames.Marital_Status.toString(), marital_status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Marital_Status.toString(), null);
		}
	}

	/**
	 * @return value of Phone_Number
	 */
	public final java.lang.Long getPhone_Number()
	{
		return getPhone_Number(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone_Number
	 */
	public final java.lang.Long getPhone_Number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Phone_Number.toString());
	}

	/**
	 * Set value of Phone_Number
	 * @param phone_number
	 */
	public final void setPhone_Number(java.lang.Long phone_number)
	{
		setPhone_Number(getContext(), phone_number);
	}

	/**
	 * Set value of Phone_Number
	 * @param context
	 * @param phone_number
	 */
	public final void setPhone_Number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long phone_number)
	{
		getMendixObject().setValue(context, MemberNames.Phone_Number.toString(), phone_number);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Profile_Account
	 */
	public final administration.proxies.Account getProfile_Account() throws com.mendix.core.CoreException
	{
		return getProfile_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Profile_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getProfile_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Profile_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Profile_Account
	 * @param profile_account
	 */
	public final void setProfile_Account(administration.proxies.Account profile_account)
	{
		setProfile_Account(getContext(), profile_account);
	}

	/**
	 * Set value of Profile_Account
	 * @param context
	 * @param profile_account
	 */
	public final void setProfile_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account profile_account)
	{
		if (profile_account == null) {
			getMendixObject().setValue(context, MemberNames.Profile_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Profile_Account.toString(), profile_account.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return profileMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Profile that = (myfirstmodule.proxies.Profile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
