// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Revert
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject revertMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Revert";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		User_Name("User_Name"),
		Revert_Confirmation("Revert_Confirmation"),
		Reason("Reason"),
		Duplicate("Duplicate"),
		Date_and_Time("Date_and_Time"),
		IsSelected("IsSelected"),
		Revert_Applicant("MyFirstModule.Revert_Applicant"),
		Revert_CaseNote("MyFirstModule.Revert_CaseNote"),
		Revert_Account("MyFirstModule.Revert_Account"),
		Revert_Account_2("MyFirstModule.Revert_Account_2");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Revert(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Revert(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject revertMendixObject)
	{
		if (revertMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, revertMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.revertMendixObject = revertMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Revert.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Revert initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Revert.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Revert initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Revert(context, mendixObject);
	}

	public static myfirstmodule.proxies.Revert load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Revert.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Revert> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Revert.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of User_Name
	 */
	public final java.lang.String getUser_Name()
	{
		return getUser_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Name
	 */
	public final java.lang.String getUser_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User_Name.toString());
	}

	/**
	 * Set value of User_Name
	 * @param user_name
	 */
	public final void setUser_Name(java.lang.String user_name)
	{
		setUser_Name(getContext(), user_name);
	}

	/**
	 * Set value of User_Name
	 * @param context
	 * @param user_name
	 */
	public final void setUser_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user_name)
	{
		getMendixObject().setValue(context, MemberNames.User_Name.toString(), user_name);
	}

	/**
	 * Set value of Revert_Confirmation
	 * @param revert_confirmation
	 */
	public final myfirstmodule.proxies.Return_Confirmation getRevert_Confirmation()
	{
		return getRevert_Confirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of Revert_Confirmation
	 */
	public final myfirstmodule.proxies.Return_Confirmation getRevert_Confirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Revert_Confirmation.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Return_Confirmation.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Revert_Confirmation
	 * @param revert_confirmation
	 */
	public final void setRevert_Confirmation(myfirstmodule.proxies.Return_Confirmation revert_confirmation)
	{
		setRevert_Confirmation(getContext(), revert_confirmation);
	}

	/**
	 * Set value of Revert_Confirmation
	 * @param context
	 * @param revert_confirmation
	 */
	public final void setRevert_Confirmation(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Return_Confirmation revert_confirmation)
	{
		if (revert_confirmation != null) {
			getMendixObject().setValue(context, MemberNames.Revert_Confirmation.toString(), revert_confirmation.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Revert_Confirmation.toString(), null);
		}
	}

	/**
	 * @return value of Reason
	 */
	public final java.lang.String getReason()
	{
		return getReason(getContext());
	}

	/**
	 * @param context
	 * @return value of Reason
	 */
	public final java.lang.String getReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reason.toString());
	}

	/**
	 * Set value of Reason
	 * @param reason
	 */
	public final void setReason(java.lang.String reason)
	{
		setReason(getContext(), reason);
	}

	/**
	 * Set value of Reason
	 * @param context
	 * @param reason
	 */
	public final void setReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reason)
	{
		getMendixObject().setValue(context, MemberNames.Reason.toString(), reason);
	}

	/**
	 * @return value of Duplicate
	 */
	public final java.lang.String getDuplicate()
	{
		return getDuplicate(getContext());
	}

	/**
	 * @param context
	 * @return value of Duplicate
	 */
	public final java.lang.String getDuplicate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Duplicate.toString());
	}

	/**
	 * Set value of Duplicate
	 * @param duplicate
	 */
	public final void setDuplicate(java.lang.String duplicate)
	{
		setDuplicate(getContext(), duplicate);
	}

	/**
	 * Set value of Duplicate
	 * @param context
	 * @param duplicate
	 */
	public final void setDuplicate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String duplicate)
	{
		getMendixObject().setValue(context, MemberNames.Duplicate.toString(), duplicate);
	}

	/**
	 * @return value of Date_and_Time
	 */
	public final java.util.Date getDate_and_Time()
	{
		return getDate_and_Time(getContext());
	}

	/**
	 * @param context
	 * @return value of Date_and_Time
	 */
	public final java.util.Date getDate_and_Time(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date_and_Time.toString());
	}

	/**
	 * Set value of Date_and_Time
	 * @param date_and_time
	 */
	public final void setDate_and_Time(java.util.Date date_and_time)
	{
		setDate_and_Time(getContext(), date_and_time);
	}

	/**
	 * Set value of Date_and_Time
	 * @param context
	 * @param date_and_time
	 */
	public final void setDate_and_Time(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date_and_time)
	{
		getMendixObject().setValue(context, MemberNames.Date_and_Time.toString(), date_and_time);
	}

	/**
	 * @return value of IsSelected
	 */
	public final java.lang.Boolean getIsSelected()
	{
		return getIsSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSelected
	 */
	public final java.lang.Boolean getIsSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSelected.toString());
	}

	/**
	 * Set value of IsSelected
	 * @param isselected
	 */
	public final void setIsSelected(java.lang.Boolean isselected)
	{
		setIsSelected(getContext(), isselected);
	}

	/**
	 * Set value of IsSelected
	 * @param context
	 * @param isselected
	 */
	public final void setIsSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isselected)
	{
		getMendixObject().setValue(context, MemberNames.IsSelected.toString(), isselected);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Revert_Applicant
	 */
	public final myfirstmodule.proxies.Applicant getRevert_Applicant() throws com.mendix.core.CoreException
	{
		return getRevert_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of Revert_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant getRevert_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Revert_Applicant.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Revert_Applicant
	 * @param revert_applicant
	 */
	public final void setRevert_Applicant(myfirstmodule.proxies.Applicant revert_applicant)
	{
		setRevert_Applicant(getContext(), revert_applicant);
	}

	/**
	 * Set value of Revert_Applicant
	 * @param context
	 * @param revert_applicant
	 */
	public final void setRevert_Applicant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant revert_applicant)
	{
		if (revert_applicant == null) {
			getMendixObject().setValue(context, MemberNames.Revert_Applicant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Revert_Applicant.toString(), revert_applicant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Revert_CaseNote
	 */
	public final java.util.List<myfirstmodule.proxies.CaseNote> getRevert_CaseNote() throws com.mendix.core.CoreException
	{
		return getRevert_CaseNote(getContext());
	}

	/**
	 * @param context
	 * @return value of Revert_CaseNote
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.CaseNote> getRevert_CaseNote(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.CaseNote> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Revert_CaseNote.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(myfirstmodule.proxies.CaseNote.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Revert_CaseNote
	 * @param revert_casenote
	 */
	public final void setRevert_CaseNote(java.util.List<myfirstmodule.proxies.CaseNote> revert_casenote)
	{
		setRevert_CaseNote(getContext(), revert_casenote);
	}

	/**
	 * Set value of Revert_CaseNote
	 * @param context
	 * @param revert_casenote
	 */
	public final void setRevert_CaseNote(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.CaseNote> revert_casenote)
	{
		var identifiers = revert_casenote
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Revert_CaseNote.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Revert_Account
	 */
	public final administration.proxies.Account getRevert_Account() throws com.mendix.core.CoreException
	{
		return getRevert_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Revert_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getRevert_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Revert_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Revert_Account
	 * @param revert_account
	 */
	public final void setRevert_Account(administration.proxies.Account revert_account)
	{
		setRevert_Account(getContext(), revert_account);
	}

	/**
	 * Set value of Revert_Account
	 * @param context
	 * @param revert_account
	 */
	public final void setRevert_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account revert_account)
	{
		if (revert_account == null) {
			getMendixObject().setValue(context, MemberNames.Revert_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Revert_Account.toString(), revert_account.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Revert_Account_2
	 */
	public final administration.proxies.Account getRevert_Account_2() throws com.mendix.core.CoreException
	{
		return getRevert_Account_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Revert_Account_2
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getRevert_Account_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Revert_Account_2.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Revert_Account_2
	 * @param revert_account_2
	 */
	public final void setRevert_Account_2(administration.proxies.Account revert_account_2)
	{
		setRevert_Account_2(getContext(), revert_account_2);
	}

	/**
	 * Set value of Revert_Account_2
	 * @param context
	 * @param revert_account_2
	 */
	public final void setRevert_Account_2(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account revert_account_2)
	{
		if (revert_account_2 == null) {
			getMendixObject().setValue(context, MemberNames.Revert_Account_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Revert_Account_2.toString(), revert_account_2.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return revertMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Revert that = (myfirstmodule.proxies.Revert) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
