// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Token_type("Token_type"),
		Scope("Scope"),
		Expires_in("Expires_in"),
		Ext_expires_in("Ext_expires_in"),
		Expires_on("Expires_on"),
		Not_before("Not_before"),
		Resource("Resource"),
		Access_token("Access_token"),
		Refresh_token("Refresh_token"),
		Id_token("Id_token"),
		_odata_context("_odata_context"),
		Token("Token"),
		TokenId("TokenId"),
		Expiration("Expiration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject)
	{
		if (rootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, rootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.rootMendixObject = rootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Root(context, mendixObject);
	}

	public static myfirstmodule.proxies.Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type()
	{
		return getToken_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_type.toString());
	}

	/**
	 * Set value of Token_type
	 * @param token_type
	 */
	public final void setToken_type(java.lang.String token_type)
	{
		setToken_type(getContext(), token_type);
	}

	/**
	 * Set value of Token_type
	 * @param context
	 * @param token_type
	 */
	public final void setToken_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_type)
	{
		getMendixObject().setValue(context, MemberNames.Token_type.toString(), token_type);
	}

	/**
	 * @return value of Scope
	 */
	public final java.lang.String getScope()
	{
		return getScope(getContext());
	}

	/**
	 * @param context
	 * @return value of Scope
	 */
	public final java.lang.String getScope(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Scope.toString());
	}

	/**
	 * Set value of Scope
	 * @param scope
	 */
	public final void setScope(java.lang.String scope)
	{
		setScope(getContext(), scope);
	}

	/**
	 * Set value of Scope
	 * @param context
	 * @param scope
	 */
	public final void setScope(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scope)
	{
		getMendixObject().setValue(context, MemberNames.Scope.toString(), scope);
	}

	/**
	 * @return value of Expires_in
	 */
	public final java.lang.String getExpires_in()
	{
		return getExpires_in(getContext());
	}

	/**
	 * @param context
	 * @return value of Expires_in
	 */
	public final java.lang.String getExpires_in(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Expires_in.toString());
	}

	/**
	 * Set value of Expires_in
	 * @param expires_in
	 */
	public final void setExpires_in(java.lang.String expires_in)
	{
		setExpires_in(getContext(), expires_in);
	}

	/**
	 * Set value of Expires_in
	 * @param context
	 * @param expires_in
	 */
	public final void setExpires_in(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expires_in)
	{
		getMendixObject().setValue(context, MemberNames.Expires_in.toString(), expires_in);
	}

	/**
	 * @return value of Ext_expires_in
	 */
	public final java.lang.String getExt_expires_in()
	{
		return getExt_expires_in(getContext());
	}

	/**
	 * @param context
	 * @return value of Ext_expires_in
	 */
	public final java.lang.String getExt_expires_in(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ext_expires_in.toString());
	}

	/**
	 * Set value of Ext_expires_in
	 * @param ext_expires_in
	 */
	public final void setExt_expires_in(java.lang.String ext_expires_in)
	{
		setExt_expires_in(getContext(), ext_expires_in);
	}

	/**
	 * Set value of Ext_expires_in
	 * @param context
	 * @param ext_expires_in
	 */
	public final void setExt_expires_in(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ext_expires_in)
	{
		getMendixObject().setValue(context, MemberNames.Ext_expires_in.toString(), ext_expires_in);
	}

	/**
	 * @return value of Expires_on
	 */
	public final java.lang.String getExpires_on()
	{
		return getExpires_on(getContext());
	}

	/**
	 * @param context
	 * @return value of Expires_on
	 */
	public final java.lang.String getExpires_on(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Expires_on.toString());
	}

	/**
	 * Set value of Expires_on
	 * @param expires_on
	 */
	public final void setExpires_on(java.lang.String expires_on)
	{
		setExpires_on(getContext(), expires_on);
	}

	/**
	 * Set value of Expires_on
	 * @param context
	 * @param expires_on
	 */
	public final void setExpires_on(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expires_on)
	{
		getMendixObject().setValue(context, MemberNames.Expires_on.toString(), expires_on);
	}

	/**
	 * @return value of Not_before
	 */
	public final java.lang.String getNot_before()
	{
		return getNot_before(getContext());
	}

	/**
	 * @param context
	 * @return value of Not_before
	 */
	public final java.lang.String getNot_before(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Not_before.toString());
	}

	/**
	 * Set value of Not_before
	 * @param not_before
	 */
	public final void setNot_before(java.lang.String not_before)
	{
		setNot_before(getContext(), not_before);
	}

	/**
	 * Set value of Not_before
	 * @param context
	 * @param not_before
	 */
	public final void setNot_before(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String not_before)
	{
		getMendixObject().setValue(context, MemberNames.Not_before.toString(), not_before);
	}

	/**
	 * @return value of Resource
	 */
	public final java.lang.String getResource()
	{
		return getResource(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource
	 */
	public final java.lang.String getResource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Resource.toString());
	}

	/**
	 * Set value of Resource
	 * @param resource
	 */
	public final void setResource(java.lang.String resource)
	{
		setResource(getContext(), resource);
	}

	/**
	 * Set value of Resource
	 * @param context
	 * @param resource
	 */
	public final void setResource(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resource)
	{
		getMendixObject().setValue(context, MemberNames.Resource.toString(), resource);
	}

	/**
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token()
	{
		return getAccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_token.toString());
	}

	/**
	 * Set value of Access_token
	 * @param access_token
	 */
	public final void setAccess_token(java.lang.String access_token)
	{
		setAccess_token(getContext(), access_token);
	}

	/**
	 * Set value of Access_token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_token.toString(), access_token);
	}

	/**
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token()
	{
		return getRefresh_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Refresh_token.toString());
	}

	/**
	 * Set value of Refresh_token
	 * @param refresh_token
	 */
	public final void setRefresh_token(java.lang.String refresh_token)
	{
		setRefresh_token(getContext(), refresh_token);
	}

	/**
	 * Set value of Refresh_token
	 * @param context
	 * @param refresh_token
	 */
	public final void setRefresh_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refresh_token)
	{
		getMendixObject().setValue(context, MemberNames.Refresh_token.toString(), refresh_token);
	}

	/**
	 * @return value of Id_token
	 */
	public final java.lang.String getId_token()
	{
		return getId_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Id_token
	 */
	public final java.lang.String getId_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Id_token.toString());
	}

	/**
	 * Set value of Id_token
	 * @param id_token
	 */
	public final void setId_token(java.lang.String id_token)
	{
		setId_token(getContext(), id_token);
	}

	/**
	 * Set value of Id_token
	 * @param context
	 * @param id_token
	 */
	public final void setId_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String id_token)
	{
		getMendixObject().setValue(context, MemberNames.Id_token.toString(), id_token);
	}

	/**
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context()
	{
		return get_odata_context(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_context.toString());
	}

	/**
	 * Set value of _odata_context
	 * @param _odata_context
	 */
	public final void set_odata_context(java.lang.String _odata_context)
	{
		set_odata_context(getContext(), _odata_context);
	}

	/**
	 * Set value of _odata_context
	 * @param context
	 * @param _odata_context
	 */
	public final void set_odata_context(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_context)
	{
		getMendixObject().setValue(context, MemberNames._odata_context.toString(), _odata_context);
	}

	/**
	 * @return value of Token
	 */
	public final java.lang.String getToken()
	{
		return getToken(getContext());
	}

	/**
	 * @param context
	 * @return value of Token
	 */
	public final java.lang.String getToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token.toString());
	}

	/**
	 * Set value of Token
	 * @param token
	 */
	public final void setToken(java.lang.String token)
	{
		setToken(getContext(), token);
	}

	/**
	 * Set value of Token
	 * @param context
	 * @param token
	 */
	public final void setToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token)
	{
		getMendixObject().setValue(context, MemberNames.Token.toString(), token);
	}

	/**
	 * @return value of TokenId
	 */
	public final java.lang.String getTokenId()
	{
		return getTokenId(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenId
	 */
	public final java.lang.String getTokenId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TokenId.toString());
	}

	/**
	 * Set value of TokenId
	 * @param tokenid
	 */
	public final void setTokenId(java.lang.String tokenid)
	{
		setTokenId(getContext(), tokenid);
	}

	/**
	 * Set value of TokenId
	 * @param context
	 * @param tokenid
	 */
	public final void setTokenId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tokenid)
	{
		getMendixObject().setValue(context, MemberNames.TokenId.toString(), tokenid);
	}

	/**
	 * @return value of Expiration
	 */
	public final java.util.Date getExpiration()
	{
		return getExpiration(getContext());
	}

	/**
	 * @param context
	 * @return value of Expiration
	 */
	public final java.util.Date getExpiration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Expiration.toString());
	}

	/**
	 * Set value of Expiration
	 * @param expiration
	 */
	public final void setExpiration(java.util.Date expiration)
	{
		setExpiration(getContext(), expiration);
	}

	/**
	 * Set value of Expiration
	 * @param context
	 * @param expiration
	 */
	public final void setExpiration(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expiration)
	{
		getMendixObject().setValue(context, MemberNames.Expiration.toString(), expiration);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Root that = (myfirstmodule.proxies.Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
