// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class UserGreetConfig
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userGreetConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.UserGreetConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MorningStartTime("MorningStartTime"),
		MorningEndTime("MorningEndTime"),
		AfternoonStartTime("AfternoonStartTime"),
		AfternoonEndTime("AfternoonEndTime"),
		EveningStartTime("EveningStartTime"),
		EveningEndTime("EveningEndTime");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserGreetConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UserGreetConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userGreetConfigMendixObject)
	{
		if (userGreetConfigMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, userGreetConfigMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.userGreetConfigMendixObject = userGreetConfigMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserGreetConfig.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.UserGreetConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.UserGreetConfig.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.UserGreetConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.UserGreetConfig(context, mendixObject);
	}

	public static myfirstmodule.proxies.UserGreetConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.UserGreetConfig.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.UserGreetConfig> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.UserGreetConfig.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MorningStartTime
	 */
	public final java.util.Date getMorningStartTime()
	{
		return getMorningStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of MorningStartTime
	 */
	public final java.util.Date getMorningStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MorningStartTime.toString());
	}

	/**
	 * Set value of MorningStartTime
	 * @param morningstarttime
	 */
	public final void setMorningStartTime(java.util.Date morningstarttime)
	{
		setMorningStartTime(getContext(), morningstarttime);
	}

	/**
	 * Set value of MorningStartTime
	 * @param context
	 * @param morningstarttime
	 */
	public final void setMorningStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date morningstarttime)
	{
		getMendixObject().setValue(context, MemberNames.MorningStartTime.toString(), morningstarttime);
	}

	/**
	 * @return value of MorningEndTime
	 */
	public final java.util.Date getMorningEndTime()
	{
		return getMorningEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of MorningEndTime
	 */
	public final java.util.Date getMorningEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MorningEndTime.toString());
	}

	/**
	 * Set value of MorningEndTime
	 * @param morningendtime
	 */
	public final void setMorningEndTime(java.util.Date morningendtime)
	{
		setMorningEndTime(getContext(), morningendtime);
	}

	/**
	 * Set value of MorningEndTime
	 * @param context
	 * @param morningendtime
	 */
	public final void setMorningEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date morningendtime)
	{
		getMendixObject().setValue(context, MemberNames.MorningEndTime.toString(), morningendtime);
	}

	/**
	 * @return value of AfternoonStartTime
	 */
	public final java.util.Date getAfternoonStartTime()
	{
		return getAfternoonStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of AfternoonStartTime
	 */
	public final java.util.Date getAfternoonStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.AfternoonStartTime.toString());
	}

	/**
	 * Set value of AfternoonStartTime
	 * @param afternoonstarttime
	 */
	public final void setAfternoonStartTime(java.util.Date afternoonstarttime)
	{
		setAfternoonStartTime(getContext(), afternoonstarttime);
	}

	/**
	 * Set value of AfternoonStartTime
	 * @param context
	 * @param afternoonstarttime
	 */
	public final void setAfternoonStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date afternoonstarttime)
	{
		getMendixObject().setValue(context, MemberNames.AfternoonStartTime.toString(), afternoonstarttime);
	}

	/**
	 * @return value of AfternoonEndTime
	 */
	public final java.util.Date getAfternoonEndTime()
	{
		return getAfternoonEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of AfternoonEndTime
	 */
	public final java.util.Date getAfternoonEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.AfternoonEndTime.toString());
	}

	/**
	 * Set value of AfternoonEndTime
	 * @param afternoonendtime
	 */
	public final void setAfternoonEndTime(java.util.Date afternoonendtime)
	{
		setAfternoonEndTime(getContext(), afternoonendtime);
	}

	/**
	 * Set value of AfternoonEndTime
	 * @param context
	 * @param afternoonendtime
	 */
	public final void setAfternoonEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date afternoonendtime)
	{
		getMendixObject().setValue(context, MemberNames.AfternoonEndTime.toString(), afternoonendtime);
	}

	/**
	 * @return value of EveningStartTime
	 */
	public final java.util.Date getEveningStartTime()
	{
		return getEveningStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EveningStartTime
	 */
	public final java.util.Date getEveningStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EveningStartTime.toString());
	}

	/**
	 * Set value of EveningStartTime
	 * @param eveningstarttime
	 */
	public final void setEveningStartTime(java.util.Date eveningstarttime)
	{
		setEveningStartTime(getContext(), eveningstarttime);
	}

	/**
	 * Set value of EveningStartTime
	 * @param context
	 * @param eveningstarttime
	 */
	public final void setEveningStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date eveningstarttime)
	{
		getMendixObject().setValue(context, MemberNames.EveningStartTime.toString(), eveningstarttime);
	}

	/**
	 * @return value of EveningEndTime
	 */
	public final java.util.Date getEveningEndTime()
	{
		return getEveningEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EveningEndTime
	 */
	public final java.util.Date getEveningEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EveningEndTime.toString());
	}

	/**
	 * Set value of EveningEndTime
	 * @param eveningendtime
	 */
	public final void setEveningEndTime(java.util.Date eveningendtime)
	{
		setEveningEndTime(getContext(), eveningendtime);
	}

	/**
	 * Set value of EveningEndTime
	 * @param context
	 * @param eveningendtime
	 */
	public final void setEveningEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date eveningendtime)
	{
		getMendixObject().setValue(context, MemberNames.EveningEndTime.toString(), eveningendtime);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userGreetConfigMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.UserGreetConfig that = (myfirstmodule.proxies.UserGreetConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
