// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicworkflow.proxies;

public enum UserRole_Enum
{
	Case_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Case Manager" } }),
	Community_Engagement_Officer(new java.lang.String[][] { new java.lang.String[] { "en_US", "Community Engagement Officer" } }),
	General_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "General Manager" } }),
	Senior_Case_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Senior Case Manager" } }),
	Senior_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Senior Manager" } }),
	Settlor(new java.lang.String[][] { new java.lang.String[] { "en_US", "Settlor" } }),
	Tenderer(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tenderer" } }),
	Trust_Admin(new java.lang.String[][] { new java.lang.String[] { "en_US", "Trust Admin" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private UserRole_Enum(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
