// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicworkflow.proxies;

public class WorkflowUsers
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowUsersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicWorkflow.WorkflowUsers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Order("Order"),
		User_Role("User_Role"),
		Is_Next_Parallel_Workflow("Is_Next_Parallel_Workflow"),
		Scheme("Scheme"),
		WorkflowLevel("WorkflowLevel"),
		Parallel_Workflow("Parallel_Workflow"),
		IsObjectCreated("IsObjectCreated"),
		UserRole("UserRole"),
		Show_workflowLevel("Show_workflowLevel"),
		ShowScheme("ShowScheme"),
		Flag("Flag"),
		Approval("Approval"),
		WorkflowUsers_WorkflowUsers("DynamicWorkflow.WorkflowUsers_WorkflowUsers"),
		WorkflowUsers_WorkflowLevel("DynamicWorkflow.WorkflowUsers_WorkflowLevel"),
		WorkflowUsers_Dynamic_Status("DynamicWorkflow.WorkflowUsers_Dynamic_Status"),
		WorkflowUsers_DynamicWorkflow("DynamicWorkflow.WorkflowUsers_DynamicWorkflow"),
		WorkflowUsers_Template("DynamicWorkflow.WorkflowUsers_Template"),
		WorkflowUsers_Applicant("DynamicWorkflow.WorkflowUsers_Applicant"),
		WorkflowUsers_Account("DynamicWorkflow.WorkflowUsers_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowUsers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowUsers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowUsersMendixObject)
	{
		if (workflowUsersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workflowUsersMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowUsersMendixObject = workflowUsersMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WorkflowUsers.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dynamicworkflow.proxies.WorkflowUsers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dynamicworkflow.proxies.WorkflowUsers.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dynamicworkflow.proxies.WorkflowUsers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicworkflow.proxies.WorkflowUsers(context, mendixObject);
	}

	public static dynamicworkflow.proxies.WorkflowUsers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicworkflow.proxies.WorkflowUsers.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicworkflow.proxies.WorkflowUsers> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> dynamicworkflow.proxies.WorkflowUsers.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder()
	{
		return getOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Order.toString());
	}

	/**
	 * Set value of Order
	 * @param order
	 */
	public final void setOrder(java.lang.Integer order)
	{
		setOrder(getContext(), order);
	}

	/**
	 * Set value of Order
	 * @param context
	 * @param order
	 */
	public final void setOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer order)
	{
		getMendixObject().setValue(context, MemberNames.Order.toString(), order);
	}

	/**
	 * Set value of User_Role
	 * @param user_role
	 */
	public final dynamicworkflow.proxies.UserRole_Enum getUser_Role()
	{
		return getUser_Role(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Role
	 */
	public final dynamicworkflow.proxies.UserRole_Enum getUser_Role(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.User_Role.toString());
		if (obj == null) {
			return null;
		}
		return dynamicworkflow.proxies.UserRole_Enum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of User_Role
	 * @param user_role
	 */
	public final void setUser_Role(dynamicworkflow.proxies.UserRole_Enum user_role)
	{
		setUser_Role(getContext(), user_role);
	}

	/**
	 * Set value of User_Role
	 * @param context
	 * @param user_role
	 */
	public final void setUser_Role(com.mendix.systemwideinterfaces.core.IContext context, dynamicworkflow.proxies.UserRole_Enum user_role)
	{
		if (user_role != null) {
			getMendixObject().setValue(context, MemberNames.User_Role.toString(), user_role.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.User_Role.toString(), null);
		}
	}

	/**
	 * @return value of Is_Next_Parallel_Workflow
	 */
	public final java.lang.Boolean getIs_Next_Parallel_Workflow()
	{
		return getIs_Next_Parallel_Workflow(getContext());
	}

	/**
	 * @param context
	 * @return value of Is_Next_Parallel_Workflow
	 */
	public final java.lang.Boolean getIs_Next_Parallel_Workflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Is_Next_Parallel_Workflow.toString());
	}

	/**
	 * Set value of Is_Next_Parallel_Workflow
	 * @param is_next_parallel_workflow
	 */
	public final void setIs_Next_Parallel_Workflow(java.lang.Boolean is_next_parallel_workflow)
	{
		setIs_Next_Parallel_Workflow(getContext(), is_next_parallel_workflow);
	}

	/**
	 * Set value of Is_Next_Parallel_Workflow
	 * @param context
	 * @param is_next_parallel_workflow
	 */
	public final void setIs_Next_Parallel_Workflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean is_next_parallel_workflow)
	{
		getMendixObject().setValue(context, MemberNames.Is_Next_Parallel_Workflow.toString(), is_next_parallel_workflow);
	}

	/**
	 * @return value of Scheme
	 */
	public final java.lang.String getScheme()
	{
		return getScheme(getContext());
	}

	/**
	 * @param context
	 * @return value of Scheme
	 */
	public final java.lang.String getScheme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Scheme.toString());
	}

	/**
	 * Set value of Scheme
	 * @param scheme
	 */
	public final void setScheme(java.lang.String scheme)
	{
		setScheme(getContext(), scheme);
	}

	/**
	 * Set value of Scheme
	 * @param context
	 * @param scheme
	 */
	public final void setScheme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scheme)
	{
		getMendixObject().setValue(context, MemberNames.Scheme.toString(), scheme);
	}

	/**
	 * @return value of WorkflowLevel
	 */
	public final java.lang.String getWorkflowLevel()
	{
		return getWorkflowLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowLevel
	 */
	public final java.lang.String getWorkflowLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkflowLevel.toString());
	}

	/**
	 * Set value of WorkflowLevel
	 * @param workflowlevel
	 */
	public final void setWorkflowLevel(java.lang.String workflowlevel)
	{
		setWorkflowLevel(getContext(), workflowlevel);
	}

	/**
	 * Set value of WorkflowLevel
	 * @param context
	 * @param workflowlevel
	 */
	public final void setWorkflowLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workflowlevel)
	{
		getMendixObject().setValue(context, MemberNames.WorkflowLevel.toString(), workflowlevel);
	}

	/**
	 * @return value of Parallel_Workflow
	 */
	public final java.lang.Boolean getParallel_Workflow()
	{
		return getParallel_Workflow(getContext());
	}

	/**
	 * @param context
	 * @return value of Parallel_Workflow
	 */
	public final java.lang.Boolean getParallel_Workflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Parallel_Workflow.toString());
	}

	/**
	 * Set value of Parallel_Workflow
	 * @param parallel_workflow
	 */
	public final void setParallel_Workflow(java.lang.Boolean parallel_workflow)
	{
		setParallel_Workflow(getContext(), parallel_workflow);
	}

	/**
	 * Set value of Parallel_Workflow
	 * @param context
	 * @param parallel_workflow
	 */
	public final void setParallel_Workflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean parallel_workflow)
	{
		getMendixObject().setValue(context, MemberNames.Parallel_Workflow.toString(), parallel_workflow);
	}

	/**
	 * @return value of IsObjectCreated
	 */
	public final java.lang.Boolean getIsObjectCreated()
	{
		return getIsObjectCreated(getContext());
	}

	/**
	 * @param context
	 * @return value of IsObjectCreated
	 */
	public final java.lang.Boolean getIsObjectCreated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsObjectCreated.toString());
	}

	/**
	 * Set value of IsObjectCreated
	 * @param isobjectcreated
	 */
	public final void setIsObjectCreated(java.lang.Boolean isobjectcreated)
	{
		setIsObjectCreated(getContext(), isobjectcreated);
	}

	/**
	 * Set value of IsObjectCreated
	 * @param context
	 * @param isobjectcreated
	 */
	public final void setIsObjectCreated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isobjectcreated)
	{
		getMendixObject().setValue(context, MemberNames.IsObjectCreated.toString(), isobjectcreated);
	}

	/**
	 * @return value of UserRole
	 */
	public final java.lang.String getUserRole()
	{
		return getUserRole(getContext());
	}

	/**
	 * @param context
	 * @return value of UserRole
	 */
	public final java.lang.String getUserRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserRole.toString());
	}

	/**
	 * Set value of UserRole
	 * @param userrole
	 */
	public final void setUserRole(java.lang.String userrole)
	{
		setUserRole(getContext(), userrole);
	}

	/**
	 * Set value of UserRole
	 * @param context
	 * @param userrole
	 */
	public final void setUserRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userrole)
	{
		getMendixObject().setValue(context, MemberNames.UserRole.toString(), userrole);
	}

	/**
	 * @return value of Show_workflowLevel
	 */
	public final java.lang.Boolean getShow_workflowLevel()
	{
		return getShow_workflowLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of Show_workflowLevel
	 */
	public final java.lang.Boolean getShow_workflowLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Show_workflowLevel.toString());
	}

	/**
	 * Set value of Show_workflowLevel
	 * @param show_workflowlevel
	 */
	public final void setShow_workflowLevel(java.lang.Boolean show_workflowlevel)
	{
		setShow_workflowLevel(getContext(), show_workflowlevel);
	}

	/**
	 * Set value of Show_workflowLevel
	 * @param context
	 * @param show_workflowlevel
	 */
	public final void setShow_workflowLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean show_workflowlevel)
	{
		getMendixObject().setValue(context, MemberNames.Show_workflowLevel.toString(), show_workflowlevel);
	}

	/**
	 * @return value of ShowScheme
	 */
	public final java.lang.Boolean getShowScheme()
	{
		return getShowScheme(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowScheme
	 */
	public final java.lang.Boolean getShowScheme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowScheme.toString());
	}

	/**
	 * Set value of ShowScheme
	 * @param showscheme
	 */
	public final void setShowScheme(java.lang.Boolean showscheme)
	{
		setShowScheme(getContext(), showscheme);
	}

	/**
	 * Set value of ShowScheme
	 * @param context
	 * @param showscheme
	 */
	public final void setShowScheme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showscheme)
	{
		getMendixObject().setValue(context, MemberNames.ShowScheme.toString(), showscheme);
	}

	/**
	 * @return value of Flag
	 */
	public final java.lang.Boolean getFlag()
	{
		return getFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of Flag
	 */
	public final java.lang.Boolean getFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Flag.toString());
	}

	/**
	 * Set value of Flag
	 * @param flag
	 */
	public final void setFlag(java.lang.Boolean flag)
	{
		setFlag(getContext(), flag);
	}

	/**
	 * Set value of Flag
	 * @param context
	 * @param flag
	 */
	public final void setFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean flag)
	{
		getMendixObject().setValue(context, MemberNames.Flag.toString(), flag);
	}

	/**
	 * Set value of Approval
	 * @param approval
	 */
	public final myfirstmodule.proxies.Enum_approval getApproval()
	{
		return getApproval(getContext());
	}

	/**
	 * @param context
	 * @return value of Approval
	 */
	public final myfirstmodule.proxies.Enum_approval getApproval(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Approval.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Enum_approval.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Approval
	 * @param approval
	 */
	public final void setApproval(myfirstmodule.proxies.Enum_approval approval)
	{
		setApproval(getContext(), approval);
	}

	/**
	 * Set value of Approval
	 * @param context
	 * @param approval
	 */
	public final void setApproval(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_approval approval)
	{
		if (approval != null) {
			getMendixObject().setValue(context, MemberNames.Approval.toString(), approval.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Approval.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowUsers_WorkflowUsers
	 */
	public final dynamicworkflow.proxies.WorkflowUsers getWorkflowUsers_WorkflowUsers() throws com.mendix.core.CoreException
	{
		return getWorkflowUsers_WorkflowUsers(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowUsers_WorkflowUsers
	 * @throws com.mendix.core.CoreException
	 */
	public final dynamicworkflow.proxies.WorkflowUsers getWorkflowUsers_WorkflowUsers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicworkflow.proxies.WorkflowUsers result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowUsers_WorkflowUsers.toString());
		if (identifier != null) {
			result = dynamicworkflow.proxies.WorkflowUsers.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowUsers_WorkflowUsers
	 * @param workflowusers_workflowusers
	 */
	public final void setWorkflowUsers_WorkflowUsers(dynamicworkflow.proxies.WorkflowUsers workflowusers_workflowusers)
	{
		setWorkflowUsers_WorkflowUsers(getContext(), workflowusers_workflowusers);
	}

	/**
	 * Set value of WorkflowUsers_WorkflowUsers
	 * @param context
	 * @param workflowusers_workflowusers
	 */
	public final void setWorkflowUsers_WorkflowUsers(com.mendix.systemwideinterfaces.core.IContext context, dynamicworkflow.proxies.WorkflowUsers workflowusers_workflowusers)
	{
		if (workflowusers_workflowusers == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_WorkflowUsers.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_WorkflowUsers.toString(), workflowusers_workflowusers.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowUsers_WorkflowLevel
	 */
	public final dynamicworkflow.proxies.WorkflowLevel getWorkflowUsers_WorkflowLevel() throws com.mendix.core.CoreException
	{
		return getWorkflowUsers_WorkflowLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowUsers_WorkflowLevel
	 * @throws com.mendix.core.CoreException
	 */
	public final dynamicworkflow.proxies.WorkflowLevel getWorkflowUsers_WorkflowLevel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicworkflow.proxies.WorkflowLevel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowUsers_WorkflowLevel.toString());
		if (identifier != null) {
			result = dynamicworkflow.proxies.WorkflowLevel.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowUsers_WorkflowLevel
	 * @param workflowusers_workflowlevel
	 */
	public final void setWorkflowUsers_WorkflowLevel(dynamicworkflow.proxies.WorkflowLevel workflowusers_workflowlevel)
	{
		setWorkflowUsers_WorkflowLevel(getContext(), workflowusers_workflowlevel);
	}

	/**
	 * Set value of WorkflowUsers_WorkflowLevel
	 * @param context
	 * @param workflowusers_workflowlevel
	 */
	public final void setWorkflowUsers_WorkflowLevel(com.mendix.systemwideinterfaces.core.IContext context, dynamicworkflow.proxies.WorkflowLevel workflowusers_workflowlevel)
	{
		if (workflowusers_workflowlevel == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_WorkflowLevel.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_WorkflowLevel.toString(), workflowusers_workflowlevel.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowUsers_Dynamic_Status
	 */
	public final dynamicworkflow.proxies.Dynamic_Status getWorkflowUsers_Dynamic_Status() throws com.mendix.core.CoreException
	{
		return getWorkflowUsers_Dynamic_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowUsers_Dynamic_Status
	 * @throws com.mendix.core.CoreException
	 */
	public final dynamicworkflow.proxies.Dynamic_Status getWorkflowUsers_Dynamic_Status(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicworkflow.proxies.Dynamic_Status result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowUsers_Dynamic_Status.toString());
		if (identifier != null) {
			result = dynamicworkflow.proxies.Dynamic_Status.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowUsers_Dynamic_Status
	 * @param workflowusers_dynamic_status
	 */
	public final void setWorkflowUsers_Dynamic_Status(dynamicworkflow.proxies.Dynamic_Status workflowusers_dynamic_status)
	{
		setWorkflowUsers_Dynamic_Status(getContext(), workflowusers_dynamic_status);
	}

	/**
	 * Set value of WorkflowUsers_Dynamic_Status
	 * @param context
	 * @param workflowusers_dynamic_status
	 */
	public final void setWorkflowUsers_Dynamic_Status(com.mendix.systemwideinterfaces.core.IContext context, dynamicworkflow.proxies.Dynamic_Status workflowusers_dynamic_status)
	{
		if (workflowusers_dynamic_status == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_Dynamic_Status.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_Dynamic_Status.toString(), workflowusers_dynamic_status.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowUsers_DynamicWorkflow
	 */
	public final dynamicworkflow.proxies.DynamicWorkflow getWorkflowUsers_DynamicWorkflow() throws com.mendix.core.CoreException
	{
		return getWorkflowUsers_DynamicWorkflow(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowUsers_DynamicWorkflow
	 * @throws com.mendix.core.CoreException
	 */
	public final dynamicworkflow.proxies.DynamicWorkflow getWorkflowUsers_DynamicWorkflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicworkflow.proxies.DynamicWorkflow result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowUsers_DynamicWorkflow.toString());
		if (identifier != null) {
			result = dynamicworkflow.proxies.DynamicWorkflow.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowUsers_DynamicWorkflow
	 * @param workflowusers_dynamicworkflow
	 */
	public final void setWorkflowUsers_DynamicWorkflow(dynamicworkflow.proxies.DynamicWorkflow workflowusers_dynamicworkflow)
	{
		setWorkflowUsers_DynamicWorkflow(getContext(), workflowusers_dynamicworkflow);
	}

	/**
	 * Set value of WorkflowUsers_DynamicWorkflow
	 * @param context
	 * @param workflowusers_dynamicworkflow
	 */
	public final void setWorkflowUsers_DynamicWorkflow(com.mendix.systemwideinterfaces.core.IContext context, dynamicworkflow.proxies.DynamicWorkflow workflowusers_dynamicworkflow)
	{
		if (workflowusers_dynamicworkflow == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_DynamicWorkflow.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_DynamicWorkflow.toString(), workflowusers_dynamicworkflow.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowUsers_Template
	 */
	public final dynamicform.proxies.Template getWorkflowUsers_Template() throws com.mendix.core.CoreException
	{
		return getWorkflowUsers_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowUsers_Template
	 * @throws com.mendix.core.CoreException
	 */
	public final dynamicform.proxies.Template getWorkflowUsers_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicform.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowUsers_Template.toString());
		if (identifier != null) {
			result = dynamicform.proxies.Template.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowUsers_Template
	 * @param workflowusers_template
	 */
	public final void setWorkflowUsers_Template(dynamicform.proxies.Template workflowusers_template)
	{
		setWorkflowUsers_Template(getContext(), workflowusers_template);
	}

	/**
	 * Set value of WorkflowUsers_Template
	 * @param context
	 * @param workflowusers_template
	 */
	public final void setWorkflowUsers_Template(com.mendix.systemwideinterfaces.core.IContext context, dynamicform.proxies.Template workflowusers_template)
	{
		if (workflowusers_template == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_Template.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_Template.toString(), workflowusers_template.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowUsers_Applicant
	 */
	public final myfirstmodule.proxies.Applicant getWorkflowUsers_Applicant() throws com.mendix.core.CoreException
	{
		return getWorkflowUsers_Applicant(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowUsers_Applicant
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Applicant getWorkflowUsers_Applicant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Applicant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowUsers_Applicant.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Applicant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowUsers_Applicant
	 * @param workflowusers_applicant
	 */
	public final void setWorkflowUsers_Applicant(myfirstmodule.proxies.Applicant workflowusers_applicant)
	{
		setWorkflowUsers_Applicant(getContext(), workflowusers_applicant);
	}

	/**
	 * Set value of WorkflowUsers_Applicant
	 * @param context
	 * @param workflowusers_applicant
	 */
	public final void setWorkflowUsers_Applicant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Applicant workflowusers_applicant)
	{
		if (workflowusers_applicant == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_Applicant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_Applicant.toString(), workflowusers_applicant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowUsers_Account
	 */
	public final administration.proxies.Account getWorkflowUsers_Account() throws com.mendix.core.CoreException
	{
		return getWorkflowUsers_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowUsers_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getWorkflowUsers_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowUsers_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowUsers_Account
	 * @param workflowusers_account
	 */
	public final void setWorkflowUsers_Account(administration.proxies.Account workflowusers_account)
	{
		setWorkflowUsers_Account(getContext(), workflowusers_account);
	}

	/**
	 * Set value of WorkflowUsers_Account
	 * @param context
	 * @param workflowusers_account
	 */
	public final void setWorkflowUsers_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account workflowusers_account)
	{
		if (workflowusers_account == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowUsers_Account.toString(), workflowusers_account.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowUsersMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicworkflow.proxies.WorkflowUsers that = (dynamicworkflow.proxies.WorkflowUsers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
