// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static myfirstmodule.proxies.CaseNote aCT__CreateCaseNote(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT__CreateCaseNote").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.CaseNote.initialize(context, result);
	}
	public static myfirstmodule.proxies.CaseNote aCT_Add_CaseNote(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Add_CaseNote").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.CaseNote.initialize(context, result);
	}
	public static void aCT_AddCaseNote(IContext context, myfirstmodule.proxies.CaseNote _caseNote)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CaseNote", _caseNote == null ? null : _caseNote.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_AddCaseNote").withParams(params).execute(context);
	}
	public static void aCT_Approved(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Approved").withParams(params).execute(context);
	}
	public static void aCT_Assigntonextuserrole(IContext context, myfirstmodule.proxies.Applicant _applicant, java.lang.String _needUserRole, java.lang.String _currentUserRole)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		params.put("NeedUserRole", _needUserRole);
		params.put("CurrentUserRole", _currentUserRole);
		Core.microflowCall("MyFirstModule.ACT_Assigntonextuserrole").withParams(params).execute(context);
	}
	public static java.util.List<myfirstmodule.proxies.Applicant> aCT_AutoSearch_Applicant(IContext context, myfirstmodule.proxies.AutoSearch _autoSearch)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AutoSearch", _autoSearch == null ? null : _autoSearch.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_AutoSearch_Applicant").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.Applicant.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void aCT_ChangeLanguage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_ChangeLanguage").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Count aCT_Chart_Count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chart_Count").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static myfirstmodule.proxies.Count aCT_Chart_Count_2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chart_Count_2").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static myfirstmodule.proxies.month aCT_Chartmonthcount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chartmonthcount").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.month.initialize(context, result);
	}
	public static myfirstmodule.proxies.month aCT_Chartmonthcount_Ceo(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chartmonthcount_Ceo").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.month.initialize(context, result);
	}
	public static myfirstmodule.proxies.caseManagermonth aCT_Chartmonthcount_General(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chartmonthcount_General").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.caseManagermonth.initialize(context, result);
	}
	public static myfirstmodule.proxies.caseManagermonth aCT_Chartmonthcount_Seniormanager(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chartmonthcount_Seniormanager").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.caseManagermonth.initialize(context, result);
	}
	public static myfirstmodule.proxies.month aCT_Chartmonthcount_Settlor(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chartmonthcount_Settlor").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.month.initialize(context, result);
	}
	public static myfirstmodule.proxies.month aCT_Chartmonthcount_sntc_user(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chartmonthcount_sntc_user").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.month.initialize(context, result);
	}
	public static myfirstmodule.proxies.caseManagermonth aCT_Chartmonthcount_Trust(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chartmonthcount_Trust").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.caseManagermonth.initialize(context, result);
	}
	public static myfirstmodule.proxies.caseManagermonth aCT_Chartmonthcountcasemanager(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chartmonthcountcasemanager").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.caseManagermonth.initialize(context, result);
	}
	public static myfirstmodule.proxies.caseManagermonth aCT_Chartmonthcountsenior(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Chartmonthcountsenior").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.caseManagermonth.initialize(context, result);
	}
	public static void aCT_CommitRemarks(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CommitRemarks").withParams(params).execute(context);
	}
	public static void aCT_CommunicationTemplate_Save(IContext context, myfirstmodule.proxies.Communciation_Template _communciation_Template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Communciation_Template", _communciation_Template == null ? null : _communciation_Template.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CommunicationTemplate_Save").withParams(params).execute(context);
	}
	public static void aCT_create_contacts(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_create_contacts").withParams(params).execute(context);
	}
	public static dynamicworkflow.proxies.WorkflowUsers aCT_Create_Workflowuser(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Create_Workflowuser").withParams(params).execute(context);
		return result == null ? null : dynamicworkflow.proxies.WorkflowUsers.initialize(context, result);
	}
	public static dynamicworkflow.proxies.WorkflowUsers aCT_create_workflowusers_add(IContext context, dynamicworkflow.proxies.WorkflowUsers _workflowUsers)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUsers", _workflowUsers == null ? null : _workflowUsers.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_create_workflowusers_add").withParams(params).execute(context);
		return result == null ? null : dynamicworkflow.proxies.WorkflowUsers.initialize(context, result);
	}
	public static void act_createApplication(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.Act_createApplication").withParams(params).execute(context);
	}
	public static void aCT_CreateObject(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_CreateObject").withParams(params).execute(context);
	}
	public static void aCT_Decide_ViewPage_CaseManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Decide_ViewPage_CaseManager").withParams(params).execute(context);
	}
	public static void aCT_Decide_ViewPage_CommunityEngagementOfficer(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Decide_ViewPage_CommunityEngagementOfficer").withParams(params).execute(context);
	}
	public static void aCT_Decide_ViewPage_GeneralManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Decide_ViewPage_GeneralManager").withParams(params).execute(context);
	}
	public static void aCT_Decide_ViewPage_SeniorCaseManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Decide_ViewPage_SeniorCaseManager").withParams(params).execute(context);
	}
	public static void aCT_Decide_ViewPage_SeniorManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Decide_ViewPage_SeniorManager").withParams(params).execute(context);
	}
	public static void aCT_Decide_ViewPage_SNTC(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Decide_ViewPage_SNTC").withParams(params).execute(context);
	}
	public static void aCT_Decide_ViewPage_TrustAdmin(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Decide_ViewPage_TrustAdmin").withParams(params).execute(context);
	}
	public static void aCT_Final_Accept(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Final_Accept").withParams(params).execute(context);
	}
	public static void aCT_forward_casemanager_button(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_forward_casemanager_button").withParams(params).execute(context);
	}
	public static void aCT_forward_seniorcasemanager_button(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_forward_seniorcasemanager_button").withParams(params).execute(context);
	}
	public static void aCT_forward_seniormanager_button(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_forward_seniormanager_button").withParams(params).execute(context);
	}
	public static void aCT_forward_sntc_button(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_forward_sntc_button").withParams(params).execute(context);
	}
	public static void aCT_forward_to_casemanager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_forward_to_casemanager").withParams(params).execute(context);
	}
	public static void aCT_forward_to_casemanager_2(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_forward_to_casemanager_2").withParams(params).execute(context);
	}
	public static void aCT_forward_to_casemanager_settlor(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_forward_to_casemanager_settlor").withParams(params).execute(context);
	}
	public static void aCT_Forward_To_GeneralManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Forward_To_GeneralManager").withParams(params).execute(context);
	}
	public static void aCT_Forward_To_TrustAdmin(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Forward_To_TrustAdmin").withParams(params).execute(context);
	}
	public static void aCT_Forward_ToSeniorCaseManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Forward_ToSeniorCaseManager").withParams(params).execute(context);
	}
	public static void aCT_Forward_ToSeniorManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Forward_ToSeniorManager").withParams(params).execute(context);
	}
	public static void aCT_Forward_ToTrustAdmin(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Forward_ToTrustAdmin").withParams(params).execute(context);
	}
	public static void aCT_forward_Trustadmin_button(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_forward_Trustadmin_button").withParams(params).execute(context);
	}
	public static void aCT_ForwardToCaseManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ForwardToCaseManager").withParams(params).execute(context);
	}
	public static void aCT_ForwardToCaseManager_Defaultflow(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ForwardToCaseManager_Defaultflow").withParams(params).execute(context);
	}
	public static void aCT_ForwardToCaseManager_Defaultflow_2(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ForwardToCaseManager_Defaultflow_2").withParams(params).execute(context);
	}
	public static void aCT_ForwardToGeneralManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ForwardToGeneralManager").withParams(params).execute(context);
	}
	public static void aCT_ForwardToSeniorCaseManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ForwardToSeniorCaseManager").withParams(params).execute(context);
	}
	public static void aCT_ForwardToSeniorManager(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ForwardToSeniorManager").withParams(params).execute(context);
	}
	public static void aCT_ForwardToTrustAdmin(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ForwardToTrustAdmin").withParams(params).execute(context);
	}
	public static administration.proxies.Account act_GetCurrentuser(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.Act_GetCurrentuser").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static myfirstmodule.proxies.Greetings_message aCT_Greetings_Message(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Greetings_Message").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Greetings_message.initialize(context, result);
	}
	public static void aCT_HISTORY_popup(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_HISTORY_popup").withParams(params).execute(context);
	}
	public static java.util.List<myfirstmodule.proxies.Count> aCT_InprogressCount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_InprogressCount").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.Count.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static boolean aCT_Life_Beneficary_Validation(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.ACT_Life_Beneficary_Validation").withParams(params).execute(context);
	}
	public static void aCT_OtherDesignated_save(IContext context, myfirstmodule.proxies.Others_Designated_Person _others_Designated_Person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Others_Designated_Person", _others_Designated_Person == null ? null : _others_Designated_Person.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_OtherDesignated_save").withParams(params).execute(context);
	}
	public static void aCT_PersonalDeatils(IContext context, myfirstmodule.proxies.Profile _profile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Profile", _profile == null ? null : _profile.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_PersonalDeatils").withParams(params).execute(context);
	}
	public static void aCT_Rejected(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Rejected").withParams(params).execute(context);
	}
	public static boolean aCT_Report(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.ACT_Report").withParams(params).execute(context);
	}
	public static void aCT_Returned(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Returned").withParams(params).execute(context);
	}
	public static void aCT_Returned_CaseManager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Returned_CaseManager").withParams(params).execute(context);
	}
	public static void aCT_Returned_GeneralMamager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Returned_GeneralMamager").withParams(params).execute(context);
	}
	public static void aCT_Returned_SeniorCaseManager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Returned_SeniorCaseManager").withParams(params).execute(context);
	}
	public static void aCT_Returned_SeniorManager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Returned_SeniorManager").withParams(params).execute(context);
	}
	public static void aCT_Returned_SNTC(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Returned_SNTC").withParams(params).execute(context);
	}
	public static void aCT_Returned_TrustAdmin(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Returned_TrustAdmin").withParams(params).execute(context);
	}
	public static void aCT_ReturnedtoCaseManager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ReturnedtoCaseManager").withParams(params).execute(context);
	}
	public static void aCT_ReturnedtoSeniorCaseManager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ReturnedtoSeniorCaseManager").withParams(params).execute(context);
	}
	public static void aCT_ReturnedtoSNTCuser(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ReturnedtoSNTCuser").withParams(params).execute(context);
	}
	public static void aCT_ReturnedtoTrustAdmin(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ReturnedtoTrustAdmin").withParams(params).execute(context);
	}
	public static void act_Save_LifeBeneficary(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.Act_Save_LifeBeneficary").withParams(params).execute(context);
	}
	public static void act_Save_OtherDesignatedPerson(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.Act_Save_OtherDesignatedPerson").withParams(params).execute(context);
	}
	public static void aCT_Save_Settlor(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Save_Settlor").withParams(params).execute(context);
	}
	public static void act_Save_SettlorSpouse(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.Act_Save_SettlorSpouse").withParams(params).execute(context);
	}
	public static void aCT_SaveCommunication(IContext context, myfirstmodule.proxies.Communication _communication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Communication", _communication == null ? null : _communication.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SaveCommunication").withParams(params).execute(context);
	}
	public static void aCT_SaveCommunication_2(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SaveCommunication_2").withParams(params).execute(context);
	}
	public static void act_Savename(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.Act_Savename").withParams(params).execute(context);
	}
	public static java.util.List<administration.proxies.Account> aCT_SelectAccountToReturn_CaseManager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_SelectAccountToReturn_CaseManager").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<administration.proxies.Account> aCT_SelectAccountToReturn_GeneralManager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_SelectAccountToReturn_GeneralManager").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<administration.proxies.Account> aCT_SelectAccountToReturn_SeniorCaseManager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_SelectAccountToReturn_SeniorCaseManager").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<administration.proxies.Account> aCT_SelectAccountToReturn_SeniorManager(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_SelectAccountToReturn_SeniorManager").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<administration.proxies.Account> aCT_SelectAccountToReturn_SNTCuser(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_SelectAccountToReturn_SNTCuser").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<administration.proxies.Account> aCT_SelectAccountToReturn_TrustAdmin(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_SelectAccountToReturn_TrustAdmin").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static boolean aCT_SNTC_Report(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.ACT_SNTC_Report").withParams(params).execute(context);
	}
	public static void aCT_TAP_StatusChange(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_TAP_StatusChange").withParams(params).execute(context);
	}
	public static java.util.List<myfirstmodule.proxies.CaseNote> aCT_testCaseNoteHistory(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_testCaseNoteHistory").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.CaseNote.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<myfirstmodule.proxies.Revert> aCT_testReturnHistory(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.ACT_testReturnHistory").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.Revert.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static myfirstmodule.proxies.Communication act_UserSelect(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.Act_UserSelect").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Communication.initialize(context, result);
	}
	public static void aCT_workflowusers_save(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_workflowusers_save").withParams(params).execute(context);
	}
	public static void addBeneficiary(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.AddBeneficiary").withParams(params).execute(context);
	}
	public static void addCareGiver(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.AddCareGiver").withParams(params).execute(context);
	}
	public static void addOtherBeneficiary(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.AddOtherBeneficiary").withParams(params).execute(context);
	}
	public static void application_search(IContext context, myfirstmodule.proxies.SearchHelper _searchHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SearchHelper", _searchHelper == null ? null : _searchHelper.getMendixObject());
		Core.microflowCall("MyFirstModule.Application_search").withParams(params).execute(context);
	}
	public static void aSU_CreateGreeting_Startup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ASU_CreateGreeting_Startup").withParams(params).execute(context);
	}
	public static void banksn_doc_save(IContext context, myfirstmodule.proxies.Bank_statements _bank_statements)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Bank_statements", _bank_statements == null ? null : _bank_statements.getMendixObject());
		Core.microflowCall("MyFirstModule.Banksn_doc_save").withParams(params).execute(context);
	}
	public static void bankStntSettlorAttachment(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.BankStntSettlorAttachment").withParams(params).execute(context);
	}
	public static void beneficiaryEditMicroflow(IContext context, myfirstmodule.proxies.Beneficiary _beneficiary)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Beneficiary", _beneficiary == null ? null : _beneficiary.getMendixObject());
		Core.microflowCall("MyFirstModule.BeneficiaryEditMicroflow").withParams(params).execute(context);
	}
	public static void beneficiaryEditMicroflow_2(IContext context, myfirstmodule.proxies.Beneficiary _beneficiary)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Beneficiary", _beneficiary == null ? null : _beneficiary.getMendixObject());
		Core.microflowCall("MyFirstModule.BeneficiaryEditMicroflow_2").withParams(params).execute(context);
	}
	public static void cancel(IContext context, myfirstmodule.proxies.Others_Designated_Person _others_Designated_Person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Others_Designated_Person", _others_Designated_Person == null ? null : _others_Designated_Person.getMendixObject());
		Core.microflowCall("MyFirstModule.Cancel").withParams(params).execute(context);
	}
	public static void cheques_doc_save(IContext context, myfirstmodule.proxies.cheques _cheques_documents)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("cheques_documents", _cheques_documents == null ? null : _cheques_documents.getMendixObject());
		Core.microflowCall("MyFirstModule.Cheques_doc_save").withParams(params).execute(context);
	}
	public static void chequesSettlorAttachment(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.chequesSettlorAttachment").withParams(params).execute(context);
	}
	public static void clone_Template_Cloneobject(IContext context, dynamicform.proxies.Template _template, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.Clone_Template_Cloneobject").withParams(params).execute(context);
	}
	public static void contactsMicroflow(IContext context, myfirstmodule.proxies.Applicant_2 _applicant_2)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant_2", _applicant_2 == null ? null : _applicant_2.getMendixObject());
		Core.microflowCall("MyFirstModule.contactsMicroflow").withParams(params).execute(context);
	}
	public static void contactsMicroflow_2(IContext context, myfirstmodule.proxies.Applicant_2 _applicant_2)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant_2", _applicant_2 == null ? null : _applicant_2.getMendixObject());
		Core.microflowCall("MyFirstModule.contactsMicroflow_2").withParams(params).execute(context);
	}
	public static void cPF_doc_save(IContext context, myfirstmodule.proxies.CPF_documents _cPF_documents)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CPF_documents", _cPF_documents == null ? null : _cPF_documents.getMendixObject());
		Core.microflowCall("MyFirstModule.CPF_doc_save").withParams(params).execute(context);
	}
	public static void cPFSettlorAttachment(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.CPFSettlorAttachment").withParams(params).execute(context);
	}
	public static void cPFSettlorSpouseAttachment_2(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.CPFSettlorSpouseAttachment_2").withParams(params).execute(context);
	}
	public static boolean dS_associate_account_with_applicant(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.DS_associate_account_with_applicant").withParams(params).execute(context);
	}
	public static void ds_associate_history_account(IContext context, myfirstmodule.proxies.History _history)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("History", _history == null ? null : _history.getMendixObject());
		Core.microflowCall("MyFirstModule.ds_associate_history_account").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Count dS_casemanager_dashboard_count_2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_casemanager_dashboard_count_2").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static java.util.List<myfirstmodule.proxies.Applicant> dS_CaseManager_overview(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_CaseManager_overview").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.Applicant.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static myfirstmodule.proxies.SearchHelper dS_casenager_overview_2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_casenager_overview_2").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.SearchHelper.initialize(context, result);
	}
	public static myfirstmodule.proxies.Applicant dS_CreateApplicant(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_CreateApplicant").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Applicant.initialize(context, result);
	}
	public static void dS_CreateDesignated_Person(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.DS_CreateDesignated_Person").withParams(params).execute(context);
	}
	public static void dS_forward(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.DS_forward").withParams(params).execute(context);
	}
	public static java.util.List<administration.proxies.Account> dS_forward_casemanager(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_forward_casemanager").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<administration.proxies.Account> dS_forward_seniorcasemanager(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_forward_seniorcasemanager").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<administration.proxies.Account> dS_forward_seniormanager(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_forward_seniormanager").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<administration.proxies.Account> dS_forward_sntc(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_forward_sntc").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<administration.proxies.Account> dS_forward_Trustadmin(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_forward_Trustadmin").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> administration.proxies.Account.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static myfirstmodule.proxies.Count dS_Generalmanager_dashboard_count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_Generalmanager_dashboard_count").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static java.util.List<myfirstmodule.proxies.Applicant> dS_Generalmanager_overview(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_Generalmanager_overview").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.Applicant.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<dynamicworkflow.proxies.WorkflowUsers> dS_retreive_workflow_users(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_retreive_workflow_users").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> dynamicworkflow.proxies.WorkflowUsers.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static myfirstmodule.proxies.AutoSearch dS_Retrieve_Applicants(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_Retrieve_Applicants").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.AutoSearch.initialize(context, result);
	}
	public static void dS_SaveAsDraft(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.DS_SaveAsDraft").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Count dS_Seniorcasemanager_dashboard_count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_Seniorcasemanager_dashboard_count").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static java.util.List<myfirstmodule.proxies.Applicant> dS_seniorcasemanager_overview(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_seniorcasemanager_overview").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.Applicant.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static myfirstmodule.proxies.Count dS_Seniormanager_dashboard_count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_Seniormanager_dashboard_count").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static java.util.List<myfirstmodule.proxies.Applicant> dS_seniormanager_overview(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_seniormanager_overview").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.Applicant.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static myfirstmodule.proxies.Count dS_settlor_dashboard_count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_settlor_dashboard_count").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static void dS_ShowDraftViewPage(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.DS_ShowDraftViewPage").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Count dS_sntc_dashboard_count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_sntc_dashboard_count").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static void dS_TEMPLATE(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.DS_TEMPLATE").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Count dS_Trustadmin_dashboard_count(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_Trustadmin_dashboard_count").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static java.util.List<myfirstmodule.proxies.Applicant> dS_TrustAdmin_overview(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_TrustAdmin_overview").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.Applicant.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void editCareGiverMicroflow(IContext context, myfirstmodule.proxies.CareGiver _careGiver)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CareGiver", _careGiver == null ? null : _careGiver.getMendixObject());
		Core.microflowCall("MyFirstModule.EditCareGiverMicroflow").withParams(params).execute(context);
	}
	public static void editCareGiverMicroflow_2(IContext context, myfirstmodule.proxies.CareGiver _careGiver)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CareGiver", _careGiver == null ? null : _careGiver.getMendixObject());
		Core.microflowCall("MyFirstModule.EditCareGiverMicroflow_2").withParams(params).execute(context);
	}
	public static void editOtherBeneficiary(IContext context, myfirstmodule.proxies.Other_Beneficiary _other_Beneficiary)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Other_Beneficiary", _other_Beneficiary == null ? null : _other_Beneficiary.getMendixObject());
		Core.microflowCall("MyFirstModule.EditOtherBeneficiary").withParams(params).execute(context);
	}
	public static void editOtherBeneficiary_2(IContext context, myfirstmodule.proxies.Other_Beneficiary _other_Beneficiary)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Other_Beneficiary", _other_Beneficiary == null ? null : _other_Beneficiary.getMendixObject());
		Core.microflowCall("MyFirstModule.EditOtherBeneficiary_2").withParams(params).execute(context);
	}
	public static void editOtherDesignatedPerson(IContext context, myfirstmodule.proxies.Others_Designated_Person _others_Designated_Person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Others_Designated_Person", _others_Designated_Person == null ? null : _others_Designated_Person.getMendixObject());
		Core.microflowCall("MyFirstModule.EditOtherDesignatedPerson").withParams(params).execute(context);
	}
	public static void editOtherDesignatedPerson_2(IContext context, myfirstmodule.proxies.Others_Designated_Person _others_Designated_Person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Others_Designated_Person", _others_Designated_Person == null ? null : _others_Designated_Person.getMendixObject());
		Core.microflowCall("MyFirstModule.EditOtherDesignatedPerson_2").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid getCurrentUserProfile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.GetCurrentUserProfile").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.DS_Review_and_Submit_Overview_TemplateGrid.initialize(context, result);
	}
	public static void high(IContext context, myfirstmodule.proxies.Priority _priority, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Priority", _priority == null ? null : _priority.getMendixObject());
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.High").withParams(params).execute(context);
	}
	public static void image_LB_save(IContext context, myfirstmodule.proxies.UserImage _image)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("image", _image == null ? null : _image.getMendixObject());
		Core.microflowCall("MyFirstModule.Image_LB_save").withParams(params).execute(context);
	}
	public static void lB_proof_delete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.LB_proof_delete").withParams(params).execute(context);
	}
	public static void lBImagedelete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.LBImagedelete").withParams(params).execute(context);
	}
	public static void lBmedicalReportdelete_2(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.LBmedicalReportdelete_2").withParams(params).execute(context);
	}
	public static void lBNRICdelete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.LBNRICdelete").withParams(params).execute(context);
	}
	public static void low(IContext context, myfirstmodule.proxies.Priority _priority, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Priority", _priority == null ? null : _priority.getMendixObject());
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.Low").withParams(params).execute(context);
	}
	public static void medicalReportLBAttachments(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.MedicalReportLBAttachments").withParams(params).execute(context);
	}
	public static void medium(IContext context, myfirstmodule.proxies.Priority _priority, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Priority", _priority == null ? null : _priority.getMendixObject());
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.Medium").withParams(params).execute(context);
	}
	public static void nRIC_doc_save(IContext context, myfirstmodule.proxies.NRIC_documents _nRIC_documents)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NRIC_documents", _nRIC_documents == null ? null : _nRIC_documents.getMendixObject());
		Core.microflowCall("MyFirstModule.NRIC_doc_save").withParams(params).execute(context);
	}
	public static void nRILifeBeneficiaryAttachment(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.NRILifeBeneficiaryAttachment").withParams(params).execute(context);
	}
	public static void nRISettlorAttachmentMicroflow(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.NRISettlorAttachmentMicroflow").withParams(params).execute(context);
	}
	public static void nRISettlorsSpouseAttachment(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.NRISettlorsSpouseAttachment").withParams(params).execute(context);
	}
	public static void oCH_AutoSearch(IContext context, myfirstmodule.proxies.AutoSearch _autoSearch)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AutoSearch", _autoSearch == null ? null : _autoSearch.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_AutoSearch").withParams(params).execute(context);
	}
	public static void och_SetBoolean(IContext context, myfirstmodule.proxies.Revert _revert)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Revert", _revert == null ? null : _revert.getMendixObject());
		Core.microflowCall("MyFirstModule.och_SetBoolean").withParams(params).execute(context);
	}
	public static void oCL_CreateContact(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("MyFirstModule.OCL_CreateContact").withParams(params).execute(context);
	}
	public static void proofSettlorSpouse(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ProofSettlorSpouse").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Search redirect_UpdateContext(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.Redirect_UpdateContext").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Search.initialize(context, result);
	}
	public static void residualBeneAttachment(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ResidualBeneAttachment").withParams(params).execute(context);
	}
	public static void residualDocudelete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ResidualDocudelete").withParams(params).execute(context);
	}
	public static void review_imageViewFlow(IContext context, myfirstmodule.proxies.UserImage _userImage, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserImage", _userImage == null ? null : _userImage.getMendixObject());
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.Review_imageViewFlow").withParams(params).execute(context);
	}
	public static void reviewBankStnView(IContext context, myfirstmodule.proxies.Bank_statements _bank_statements, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Bank_statements", _bank_statements == null ? null : _bank_statements.getMendixObject());
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ReviewBankStnView").withParams(params).execute(context);
	}
	public static void reviewChequesView(IContext context, myfirstmodule.proxies.cheques _cheques, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("cheques", _cheques == null ? null : _cheques.getMendixObject());
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ReviewChequesView").withParams(params).execute(context);
	}
	public static void reviewCPF_documents_view(IContext context, myfirstmodule.proxies.CPF_documents _cPF_documents, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CPF_documents", _cPF_documents == null ? null : _cPF_documents.getMendixObject());
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ReviewCPF_documents_view").withParams(params).execute(context);
	}
	public static void reviewpageNRIC_view(IContext context, myfirstmodule.proxies.NRIC_documents _nRIC_documents, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NRIC_documents", _nRIC_documents == null ? null : _nRIC_documents.getMendixObject());
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.ReviewpageNRIC_view").withParams(params).execute(context);
	}
	public static void settlorBankStndelete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.SettlorBankStndelete").withParams(params).execute(context);
	}
	public static void settlorChequesdelete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.SettlorChequesdelete").withParams(params).execute(context);
	}
	public static void settlorCPFdelete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.SettlorCPFdelete").withParams(params).execute(context);
	}
	public static void settlorNRICdelete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.SettlorNRICdelete").withParams(params).execute(context);
	}
	public static void settlorSpouseCPFdelete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.SettlorSpouseCPFdelete").withParams(params).execute(context);
	}
	public static void settlorSpouseNRICdelete(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.SettlorSpouseNRICdelete").withParams(params).execute(context);
	}
	public static void sub_CloneElementObjects(IContext context, dynamicform.proxies.Element _element, dynamicform.proxies.Template _template)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element == null ? null : _element.getMendixObject());
		params.put("Template", _template == null ? null : _template.getMendixObject());
		Core.microflowCall("MyFirstModule.Sub_CloneElementObjects").withParams(params).execute(context);
	}
	public static void sub_CreateAndSendEmail(IContext context, myfirstmodule.proxies.Communication _communication, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Communication", _communication == null ? null : _communication.getMendixObject());
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		Core.microflowCall("MyFirstModule.Sub_CreateAndSendEmail").withParams(params).execute(context);
	}
	public static void test(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.test").withParams(params).execute(context);
	}
	public static void test_cancel(IContext context, myfirstmodule.proxies.NRIC_documents _nRIC_documents)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NRIC_documents", _nRIC_documents == null ? null : _nRIC_documents.getMendixObject());
		Core.microflowCall("MyFirstModule.test_cancel").withParams(params).execute(context);
	}
	public static void test_Microflow(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.test_Microflow").withParams(params).execute(context);
	}
	public static void userimageSettlor(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.UserimageSettlor").withParams(params).execute(context);
	}
	public static void userimageSettlorSpouse(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.UserimageSettlorSpouse").withParams(params).execute(context);
	}
	public static void viewBankStn_settlor(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewBankStn_settlor").withParams(params).execute(context);
	}
	public static void viewcheques_settlor(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewcheques_settlor").withParams(params).execute(context);
	}
	public static void viewCPF_settlor(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewCPF_settlor").withParams(params).execute(context);
	}
	public static void viewCPF_settlorSpouse(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewCPF_settlorSpouse").withParams(params).execute(context);
	}
	public static void viewImage_LB(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewImage_LB").withParams(params).execute(context);
	}
	public static void viewMedicalRport_LB(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewMedicalRport_LB").withParams(params).execute(context);
	}
	public static void viewNRIC_LifeBeneficiary(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewNRIC_LifeBeneficiary").withParams(params).execute(context);
	}
	public static void viewNRIC_settlor(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewNRIC_settlor").withParams(params).execute(context);
	}
	public static void viewNRIC_settlorSpouse(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewNRIC_settlorSpouse").withParams(params).execute(context);
	}
	public static void viewProof_LB(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewProof_LB").withParams(params).execute(context);
	}
	public static void viewResidualBene_docs(IContext context, myfirstmodule.proxies.Applicant _applicant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Applicant", _applicant == null ? null : _applicant.getMendixObject());
		Core.microflowCall("MyFirstModule.viewResidualBene_docs").withParams(params).execute(context);
	}
}
